from .schema import C

HEALTH = [
C("LLY", "Eli Lilly and Company", "health", "Indianapolis, Indiana, USA", 1876,
  "David Ricks", "NYSE", 1213.91, 0.90, 30.0, 72.0,
  [0.30, 0.24, 0.19, 0.15, 0.12], 0.28, 0.34, 0.082, 0.030,
  "Founded in 1876 by Colonel Eli Lilly, a Union Army veteran and pharmaceutical chemist, in Indianapolis, where it is still headquartered. David Ricks has been CEO since 2017. Lilly was the first company to mass-produce insulin and later the polio vaccine. Today it is defined by the incretin franchise: Mounjaro for type 2 diabetes and Zepbound for obesity, both tirzepatide. Its oral GLP-1 pill, Foundayo, received FDA approval on 1 April 2026, opening the market to patients unwilling to inject. Other products include Verzenio in oncology and donanemab for Alzheimer's.",
  [("Diabetes & Obesity (incretins)", 62), ("Oncology", 16), ("Immunology", 10), ("Neuroscience & Other", 12)],
  ["The obesity market is one of the largest addressable opportunities in pharmaceutical history and Lilly has the best-in-class molecule.",
   "Oral GLP-1 approval in April 2026 removes the injection barrier and expands the treatable population enormously.",
   "Manufacturing capacity investment has been aggressive and early, which has been the binding constraint for the whole category."],
  ["Payer pushback on pricing is intensifying as obesity drug spending becomes a visible line item in health budgets.",
   "Compounded and counterfeit GLP-1 supply undercuts pricing in the cash-pay segment.",
   "Patent expiry on tirzepatide arrives in the 2030s and the next franchise has to be built before then."],
  "One of the most consistently favoured large-cap pharma names, with the debate focused on pricing durability rather than demand. The stock reached $1,229 in July 2026 after running from $625 over twelve months.",
  "Foundayo launch metrics, incretin prescription trends, payer coverage decisions, Alzheimer's franchise uptake.",
  (5, 5, 5, 4)),

C("JNJ", "Johnson & Johnson", "health", "New Brunswick, New Jersey, USA", 1886,
  "Joaquin Duato", "NYSE", 263.04, 2.41, 15.0, 92.0,
  [0.06, 0.06, 0.05, 0.05, 0.04], 0.22, 0.24, 0.075, 0.024,
  "Founded in 1886 by three Johnson brothers in New Brunswick, New Jersey, originally making sterile surgical dressings. Joaquin Duato is CEO. After spinning off its consumer health business as Kenvue in 2023, J&J is a focused pharmaceutical and medical technology company. Innovative Medicine covers oncology (Darzalex, Carvykti), immunology (Tremfya, Stelara) and neuroscience. MedTech sells surgical robotics through Ottava, orthopaedics, cardiovascular devices including the Abiomed heart pump, and vision care. It carries a AAA-equivalent credit rating, rarer than a triple-A sovereign.",
  [("Innovative Medicine", 64), ("MedTech", 36)],
  ["Balance sheet strength is exceptional, giving it the ability to acquire growth when others cannot afford to.",
   "Diversification across pharma and devices smooths the patent cliffs that hit pure pharmaceutical companies.",
   "Over six decades of consecutive dividend increases, a record almost nothing in the market matches."],
  ["Stelara has lost exclusivity and biosimilar erosion is a real revenue headwind.",
   "Talc litigation remains unresolved and the potential liability is difficult to size with confidence.",
   "Mid single-digit growth means the stock is a yield and stability holding, not a compounder."],
  "Treated as the defensive anchor of healthcare portfolios. The recurring question is whether the pipeline can offset Stelara erosion without a large acquisition.",
  "Oncology pipeline readouts, MedTech procedure volumes, talc litigation developments.",
  (5, 2, 5, 5)),

C("NVO", "Novo Nordisk A/S", "health", "Bagsværd, Denmark", 1923,
  "Mike Doustdar", "NYSE (ADR) / Copenhagen", 52.00, 4.42, 8.0, 44.0,
  [0.10, 0.11, 0.10, 0.09, 0.08], 0.265, 0.29, 0.093, 0.028,
  "Formed from the 1989 merger of Novo Terapeutisk Laboratorium and Nordisk Insulinlaboratorium, both founded in the early 1920s to produce insulin in Denmark. Headquartered in Bagsværd and controlled by the Novo Nordisk Foundation. Mike Doustdar became CEO in 2025. Products: Ozempic and Rybelsus for type 2 diabetes, Wegovy for obesity — all semaglutide — plus a large insulin portfolio and rare disease treatments in haemophilia. Novo lost significant ground to Lilly through 2025 and 2026 as tirzepatide outperformed semaglutide on weight loss.",
  [("Diabetes care", 52), ("Obesity care", 40), ("Rare disease", 8)],
  ["Semaglutide remains an enormous global franchise with brand recognition that no competitor has matched.",
   "Massive manufacturing investment in Denmark and North Carolina secures supply for the next decade.",
   "The stock has de-rated so far that expectations are now genuinely low relative to the installed patient base."],
  ["Lilly's tirzepatide has consistently beaten semaglutide on weight loss in head-to-head data, and prescribers have noticed.",
   "The CagriSema trial results disappointed against the bar the company itself had set.",
   "Semaglutide patent expiry in Canada and other markets arrives sooner than in the US, opening generic entry."],
  "A classic fallen-quality debate. Bulls argue the de-rating overshot for a franchise still generating enormous cash; bears think the loss of category leadership is permanent.",
  "Obesity market share data, next-generation pipeline readouts, US pricing negotiations.",
  (4, 3, 4, 4)),

C("UNH", "UnitedHealth Group", "health", "Minnetonka, Minnesota, USA", 1977,
  "Stephen Hemsley", "NYSE", 425.36, 0.90, 55.0, 440.0,
  [0.07, 0.07, 0.06, 0.06, 0.05], 0.045, 0.055, 0.088, 0.026,
  "Founded in 1977 as Charter Med in Minnetonka, Minnesota. Stephen Hemsley returned as CEO in 2025 after the stock's collapse. Two halves: UnitedHealthcare, the largest US health insurer covering employer, individual, Medicare Advantage and Medicaid members; and Optum, which includes Optum Health (employing or affiliating with tens of thousands of physicians), Optum Rx (one of the three big pharmacy benefit managers) and Optum Insight (health data and analytics). The vertical integration between insurer and provider is both its strength and its regulatory vulnerability.",
  [("UnitedHealthcare", 55), ("Optum Health", 24), ("Optum Rx", 18), ("Optum Insight", 3)],
  ["Vertical integration lets Optum capture margin at multiple points in the same healthcare dollar.",
   "The stock fell from $625 to a low near $238 — the de-rating from the 2024-25 crisis has been severe and expectations are now low.",
   "Medicare Advantage demographics are a long-duration tailwind as the US population ages."],
  ["Medical cost ratios ran well above expectations through 2025, and the market lost confidence in management's ability to forecast them.",
   "Department of Justice scrutiny of Medicare Advantage risk-coding practices is an unresolved overhang.",
   "Pharmacy benefit managers are a bipartisan political target, and Optum Rx is one of the three largest."],
  "Among the most contested large caps in healthcare. Bulls see a franchise trading at a fraction of its historical multiple; bears argue the regulatory and cost-trend problems are structural, not cyclical.",
  "Medical loss ratio, Medicare Advantage rate notices, DOJ investigation developments, Optum Health margin.",
  (4, 2, 3, 4)),

C("ABBV", "AbbVie Inc.", "health", "North Chicago, Illinois, USA", 2013,
  "Robert Michael", "NYSE", 261.07, 1.77, 62.0, 62.0,
  [0.08, 0.07, 0.06, 0.05, 0.05], 0.30, 0.32, 0.080, 0.025,
  "Spun out of Abbott Laboratories in 2013 to separate the research pharmaceutical business. Robert Michael became CEO in 2024. AbbVie is built around immunology: Skyrizi and Rinvoq, the two successors to Humira, which was for years the best-selling drug in the world before losing exclusivity in 2023. It also owns Botox and the Allergan aesthetics portfolio, oncology assets including Imbruvica and Venclexta, and a neuroscience franchise with Vraylar and Ubrelvy. The stock rose 11.15% in the week to 21 July 2026.",
  [("Immunology", 47), ("Neuroscience", 16), ("Oncology", 14), ("Aesthetics", 13), ("Other", 10)],
  ["Skyrizi and Rinvoq have more than replaced Humira revenue, which is the hardest transition in pharma and AbbVie executed it.",
   "Aesthetics and Botox provide a cash-pay revenue stream insulated from drug pricing politics.",
   "One of the highest dividend yields among large-cap pharma with a strong coverage ratio."],
  ["Net debt above $60B from the Allergan acquisition is high relative to peers.",
   "The immunology category is crowded and biosimilar pressure eventually reaches Skyrizi and Rinvoq too.",
   "Aesthetics demand is discretionary and softened when consumers tightened spending."],
  "Generally viewed favourably on the strength of the Humira transition. The question is what replaces immunology growth into the 2030s.",
  "Skyrizi and Rinvoq prescription trends, aesthetics recovery, pipeline business development.",
  (4, 3, 4, 3)),

C("MRK", "Merck & Co., Inc.", "health", "Rahway, New Jersey, USA", 1891,
  "Robert Davis", "NYSE", 129.56, 2.51, 25.0, 65.0,
  [0.05, 0.04, -0.03, 0.02, 0.04], 0.26, 0.24, 0.082, 0.022,
  "Founded in 1891 as the US subsidiary of the German chemical firm Merck, becoming independent after the First World War. Headquartered in Rahway, New Jersey; Robert Davis is CEO. The company is defined by Keytruda, the PD-1 checkpoint inhibitor that is the best-selling drug in the world and treats a growing list of cancers. Other products include Gardasil for HPV, the Januvia diabetes franchise, and a large animal health division. Merck's central challenge is the Keytruda patent cliff arriving in 2028.",
  [("Oncology (Keytruda-led)", 50), ("Vaccines", 17), ("Animal Health", 12), ("Other pharma", 21)],
  ["Keytruda continues to add indications, and a subcutaneous formulation can extend the franchise's effective life.",
   "Animal health is a genuinely good, non-correlated business that the market largely ignores.",
   "The valuation already discounts a sharp Keytruda cliff, which is why our model deliberately builds a decline year into the forecast."],
  ["Keytruda is roughly half of revenue and loses exclusivity in 2028. This is one of the largest patent cliffs in industry history.",
   "Gardasil demand in China collapsed and has not recovered.",
   "The pipeline has not yet produced an asset of remotely comparable scale."],
  "The Keytruda cliff dominates every conversation. Bulls argue the market has over-discounted it and business development will fill the gap; bears say no pipeline can replace $30B of revenue.",
  "Subcutaneous Keytruda uptake, pipeline readouts, business development activity, Gardasil China trends.",
  (4, 1, 4, 4)),

C("AZN", "AstraZeneca PLC", "health", "Cambridge, United Kingdom", 1999,
  "Pascal Soriot", "Nasdaq (ADR) / LSE", 195.15, 1.44, 22.0, 58.0,
  [0.10, 0.09, 0.09, 0.08, 0.07], 0.185, 0.235, 0.084, 0.026,
  "Formed in 1999 from the merger of Sweden's Astra AB and Britain's Zeneca Group. Pascal Soriot has been CEO since 2012 and moved the headquarters and research base to Cambridge, England. AstraZeneca is strongest in oncology — Tagrisso, Imfinzi, Lynparza and the antibody-drug conjugate Enhertu, partnered with Daiichi Sankyo — plus biopharmaceuticals in cardiovascular, renal and metabolic disease including Farxiga, and respiratory and immunology. It has an unusually large China business for a Western pharmaceutical company.",
  [("Oncology", 42), ("BioPharmaceuticals (CVRM & R&I)", 45), ("Rare Disease (Alexion)", 13)],
  ["One of the deepest oncology pipelines in the industry, with antibody-drug conjugates a genuine platform advantage.",
   "Rare disease through Alexion provides high-priced, durable revenue with limited competition.",
   "Broad geographic diversification reduces dependence on US drug pricing policy."],
  ["Large China exposure carries both political and pricing risk that peers do not have.",
   "US tariff and drug pricing policy has been a persistent overhang for non-US pharmaceutical companies.",
   "Several late-stage readouts are binary and the stock reacts violently to them."],
  "Well regarded on pipeline depth. The recurring debate is how to value the China business and whether US policy risk is adequately discounted.",
  "Oncology trial readouts, Enhertu label expansion, China revenue trends, US pricing policy.",
  (4, 4, 4, 4)),

C("NVS", "Novartis AG", "health", "Basel, Switzerland", 1996,
  "Vasant Narasimhan", "NYSE (ADR) / SIX", 147.48, 1.91, 15.0, 54.0,
  [0.06, 0.05, 0.05, 0.04, 0.04], 0.28, 0.30, 0.078, 0.022,
  "Created in 1996 from the merger of Ciba-Geigy and Sandoz, both Basel chemical and pharmaceutical houses with roots in the 1750s. Vasant Narasimhan is CEO. After spinning off the Sandoz generics business in 2023 and the Alcon eye care business in 2019, Novartis is a focused innovative medicines company. Key products include Entresto for heart failure, Cosentyx in immunology, Kisqali in breast cancer, Kesimpta for multiple sclerosis, and the radioligand therapy Pluvicto — a genuinely differentiated cancer treatment that delivers radiation directly to tumour cells.",
  [("Oncology & Haematology", 40), ("Immunology & Neuroscience", 32), ("Cardio-Renal-Metabolic", 20), ("Other", 8)],
  ["Radioligand therapy is a differentiated platform with manufacturing complexity that acts as a barrier to entry.",
   "Post-spin-off, the portfolio is cleaner and margins have improved materially.",
   "Swiss domicile and strong cash generation support a reliable, growing dividend."],
  ["Entresto has begun losing exclusivity, removing a large revenue contributor.",
   "Growth is mid single digits, which limits the multiple the market will pay.",
   "Pipeline depends on a small number of high-value assets performing."],
  "Seen as a well-run, conservatively managed European pharma. The debate is whether the pipeline can sustain growth once Entresto erosion completes.",
  "Pluvicto expansion, Kisqali growth, Entresto erosion pace, pipeline readouts.",
  (4, 2, 5, 5)),

C("ISRG", "Intuitive Surgical", "health", "Sunnyvale, California, USA", 1995,
  "Gary Guthart", "Nasdaq", 560.00, 0.36, -8.5, 9.5,
  [0.16, 0.15, 0.14, 0.12, 0.11], 0.28, 0.32, 0.088, 0.030,
  "Founded in 1995 to commercialise robotic surgery research from SRI International. Gary Guthart has been CEO since 2010. Intuitive makes the da Vinci surgical system — a robotic platform that lets a surgeon operate through small incisions using instruments controlled from a console — and Ion, a robotic catheter for lung biopsy. The business model is razor-and-blade: systems are placed with hospitals, then Intuitive earns recurring revenue on instruments and accessories consumed in every procedure, plus service contracts.",
  [("Instruments & Accessories", 61), ("Systems", 26), ("Services", 13)],
  ["Recurring instrument revenue grows with procedure volume, independent of new system placements.",
   "Surgeons train on da Vinci during residency, which creates a professional lock-in that competitors cannot buy their way past.",
   "Enormous installed base of systems already placed, each generating consumable revenue for a decade."],
  ["The valuation is very demanding for a medical device company, on any earnings measure.",
   "Medtronic, J&J and several Chinese manufacturers are launching credible competing platforms.",
   "Hospital capital budgets tighten when credit conditions do, and system placements are the first thing deferred."],
  "Consistently regarded as a top-quality compounder. The objection is purely the price paid for that quality.",
  "Procedure volume growth, da Vinci 5 placements, competitive platform approvals, hospital capex trends.",
  (5, 4, 5, 5)),

C("VRTX", "Vertex Pharmaceuticals", "health", "Boston, Massachusetts, USA", 1989,
  "Reshma Kewalramani", "Nasdaq", 425.00, 0.26, -11.0, 12.0,
  [0.14, 0.13, 0.12, 0.11, 0.10], 0.34, 0.38, 0.090, 0.030,
  "Founded in 1989 by Joshua Boger in Cambridge, Massachusetts, with a then-radical commitment to structure-based rational drug design. Reshma Kewalramani has been CEO since 2020. Vertex effectively owns the cystic fibrosis market with Trikafta and its successor Alyftrek, treating the underlying protein defect rather than symptoms. It has diversified into Casgevy, the first approved CRISPR gene-editing therapy, developed with CRISPR Therapeutics for sickle cell disease, and Journavx, a non-opioid painkiller approved in 2025 for acute pain.",
  [("Cystic Fibrosis", 84), ("Pain, Gene Therapy & Other", 16)],
  ["A near-monopoly in cystic fibrosis with pricing power and patients who stay on therapy for life.",
   "Journavx addresses acute pain without opioid addiction risk, which is a very large market with obvious policy support.",
   "Large net cash position funds development without dilution."],
  ["Extreme concentration — cystic fibrosis is the overwhelming majority of revenue.",
   "Casgevy uptake has been slow because the treatment process is complex and expensive to administer.",
   "Cystic fibrosis patent protection eventually erodes and the diversification has to work before then."],
  "Respected for scientific execution. The debate is whether the non-cystic-fibrosis pipeline can become material before the core franchise matures.",
  "Journavx launch trajectory, Casgevy patient starts, cystic fibrosis reimbursement in new markets.",
  (5, 4, 5, 5)),

C("AMGN", "Amgen Inc.", "health", "Thousand Oaks, California, USA", 1980,
  "Robert Bradway", "Nasdaq", 374.15, 0.54, 52.0, 35.0,
  [0.06, 0.06, 0.05, 0.05, 0.04], 0.28, 0.29, 0.082, 0.024,
  "Founded in 1980 as Applied Molecular Genetics in Thousand Oaks, California, one of the original biotechnology companies. Robert Bradway has been CEO since 2012. Amgen's portfolio spans Repatha for cholesterol, Prolia and Evenity for osteoporosis, Tezspire for asthma, the oncology drug Blincyto, and a large biosimilars business. Its 2023 acquisition of Horizon Therapeutics added Tepezza for thyroid eye disease and Krystexxa for gout. MariTide, a monthly injectable obesity drug, is the company's most-watched pipeline asset.",
  [("General Medicine", 42), ("Oncology", 24), ("Rare Disease (Horizon)", 22), ("Biosimilars & Other", 12)],
  ["MariTide's monthly dosing would be a genuine differentiator against weekly GLP-1 injections.",
   "Rare disease assets from Horizon carry high prices and limited competition.",
   "Biosimilars provide a growing revenue stream that benefits as branded biologics lose exclusivity."],
  ["Around $52B of net debt from the Horizon deal is high and constrains further business development.",
   "Prolia and other mature products face biosimilar erosion of their own.",
   "MariTide is a binary event — the obesity market is unforgiving and Lilly and Novo are far ahead."],
  "Split between those buying the MariTide option and those focused on the debt load and mature base business.",
  "MariTide phase 3 data, Tepezza growth, debt paydown, biosimilar launches.",
  (4, 2, 4, 3)),

C("REGN", "Regeneron Pharmaceuticals", "health", "Tarrytown, New York, USA", 1988,
  "Leonard Schleifer", "Nasdaq", 630.00, 0.11, -12.0, 14.5,
  [0.07, 0.08, 0.08, 0.07, 0.07], 0.225, 0.25, 0.092, 0.028,
  "Founded in 1988 by Leonard Schleifer, a neurologist, with George Yancopoulos as chief scientist — both still run the company from Tarrytown, New York. Regeneron's platform technologies, VelocImmune and VelociSuite, generate fully human antibodies quickly and have produced an unusual hit rate. Key products: Eylea for retinal disease, Dupixent for atopic dermatitis and asthma, which is co-developed with Sanofi and is one of the fastest-growing drugs in the world, and Libtayo in oncology. It also runs a large human genetics sequencing programme.",
  [("Dupixent collaboration revenue", 44), ("Eylea", 32), ("Libtayo & Other", 24)],
  ["Dupixent keeps adding indications and is on track to become one of the largest drugs in the industry.",
   "The antibody discovery platform has repeatedly produced approved medicines, which is rare and hard to copy.",
   "Substantial net cash and no reliance on external financing."],
  ["Eylea faces aggressive biosimilar competition in the US, and that erosion is already visible in the numbers.",
   "Dupixent economics are shared with Sanofi, so Regeneron captures only part of the value.",
   "Concentration in two products means a single competitive setback moves the whole story."],
  "Well regarded scientifically, with the debate centred on how fast Eylea erodes versus how fast Dupixent grows.",
  "Eylea biosimilar share loss, Dupixent indication expansion, pipeline readouts in obesity and oncology.",
  (4, 3, 5, 5)),
]
