from .schema import C

AUTOS = [
C("TSLA", "Tesla, Inc.", "autos", "Austin, Texas, USA", 2003,
  "Elon Musk", "Nasdaq", 393.45, 3.55, -25.0, 102.0,
  [0.14, 0.16, 0.15, 0.13, 0.11], 0.07, 0.14, 0.115, 0.032,
  "Founded in 2003 by Martin Eberhard and Marc Tarpenning; Elon Musk joined as chairman in 2004 and has been CEO since 2008. Headquartered in Austin, Texas. Tesla makes the Model 3, Y, S and X, the Cybertruck and the Semi, at factories in Fremont, Shanghai, Berlin and Austin. Beyond vehicles it sells Powerwall and Megapack energy storage, operates the largest fast-charging network in the world, and is developing Full Self-Driving software, a robotaxi service and the Optimus humanoid robot. Energy storage has been the fastest-growing part of the business.",
  [("Automotive", 74), ("Energy Generation & Storage", 16), ("Services & Other", 10)],
  ["Energy storage is growing far faster than vehicles and carries better margins — Megapack demand from data centres and grids is enormous.",
   "The Supercharger network has become an industry standard that competitors now pay to access.",
   "Full Self-Driving and robotaxi represent genuine optionality that no conventional automaker has."],
  ["Automotive gross margins have compressed substantially as electric vehicle competition intensified, particularly from BYD.",
   "The valuation cannot be justified on the car business alone; it requires believing in autonomy and robotics.",
   "Key-person risk around Musk is real, and his attention is split across several companies including the newly public SpaceX."],
  "The most debated valuation in large-cap equities. Third-quarter 2026 deliveries of 486,532 beat consensus by about 25,000 and the shares rose, though energy storage deployments of 13.7 GWh fell short of expectations. Our model gives partial credit to energy storage but does not attempt to value robotaxi, which is why the output sits well below market.",
  "Q3 results, automotive gross margin ex-credits, energy storage deployments, FSD regulatory approvals, spending under the new $30 billion credit facilities.",
  (4, 4, 3, 5)),

C("TM", "Toyota Motor Corporation", "autos", "Toyota City, Japan", 1937,
  "Kenta Kon", "NYSE (ADR) / TSE", 196.08, 1.30, 95.0, 320.0,
  [0.04, 0.03, 0.03, 0.03, 0.03], 0.06, 0.07, 0.086, 0.020,
  "Founded in 1937 by Kiichiro Toyoda as a spin-off from his father's loom manufacturing business. Kenta Kon, previously the finance chief, became president and CEO in April 2026, succeeding Koji Sato; headquartered in Toyota City, Japan. Toyota is the largest carmaker in the world by volume, selling around 10 million vehicles a year under the Toyota and Lexus brands, plus Daihatsu and Hino. It pioneered hybrid technology with the Prius in 1997, and that decision looks increasingly astute as hybrid demand has outpaced pure electric in several markets. The Toyota Production System is still the manufacturing benchmark studied worldwide.",
  [("Automotive (Toyota & Lexus)", 90), ("Financial Services", 8), ("Other", 2)],
  ["Hybrid leadership is paying off precisely as consumers hesitate on full battery electric vehicles.",
   "Manufacturing efficiency produces industry-leading margins on mass-market vehicles.",
   "Trades at a low multiple of earnings with a large balance sheet, and announced a record ¥1 trillion buyback, about 4.2% of shares, in August 2026."],
  ["Late to battery electric vehicles relative to Chinese competitors, particularly in China itself.",
   "Yen strength reduces the translated value of overseas profits.",
   "US tariffs on imported vehicles are a direct cost, with Toyota projecting a ¥1.45 trillion drag for the current fiscal year."],
  "Viewed as the highest-quality traditional automaker, generally considered inexpensive. First-quarter operating profit fell 8.8% under tariffs, but in August 2026 Toyota raised its full-year operating income forecast to ¥3.4 trillion and announced its largest ever buyback. The concern is long-term positioning against Chinese electric vehicle makers.",
  "Global production volumes, hybrid mix, yen exchange rate, US tariff costs, buyback execution, China share.",
  (4, 2, 5, 5)),

C("BYDDY", "BYD Company Limited", "autos", "Shenzhen, China", 1995,
  "Wang Chuanfu", "OTC (ADR) / HKEX", 62.00, 2.92, -8.0, 155.0,
  [0.14, 0.13, 0.11, 0.10, 0.09], 0.035, 0.058, 0.115, 0.026,
  "Founded in 1995 by Wang Chuanfu as a rechargeable battery manufacturer in Shenzhen; it entered car making in 2003 by buying a struggling state automaker. Wang is still chairman and CEO. BYD is now the largest producer of electric and plug-in hybrid vehicles in the world, and it is vertically integrated to an extreme degree — it makes its own Blade batteries, semiconductors, motors and electronics. That integration is why it can undercut competitors on price. It also builds electric buses, and Warren Buffett's Berkshire Hathaway was an early shareholder.",
  [("Automobiles & related", 80), ("Mobile handset components & assembly", 18), ("Other", 2)],
  ["Vertical integration into batteries and semiconductors produces a structural cost advantage no Western automaker can match.",
   "Overseas expansion is growing far faster than the domestic business: overseas sales rose 154% year on year in September 2026, and the 2026 overseas target has been raised to 1.9–2.0 million vehicles.",
   "Plug-in hybrid technology addresses range anxiety in markets with weak charging infrastructure."],
  ["The Chinese domestic price war and weak home demand pushed first-half 2026 net profit down 20.5% and nine-month sales down 3.9%.",
   "European Union tariffs on Chinese electric vehicles directly target BYD's expansion strategy.",
   "Governance and disclosure standards for Chinese listings are a persistent concern for foreign investors."],
  "Widely acknowledged as the global cost leader in electric vehicles, but the Hong Kong shares have lost about 35% over the past year as domestic sales and profit fell. Exports are now the main support, and September 2026 sales of 463,561 were the highest monthly total of the year.",
  "Monthly sales volumes, overseas export mix and the 1.9–2.0 million overseas target, gross margin per vehicle, EU tariff rulings.",
  (4, 4, 4, 4)),

C("RACE", "Ferrari N.V.", "autos", "Maranello, Italy", 1939,
  "Benedetto Vigna", "NYSE / Borsa Italiana", 445.00, 0.179, 0.5, 7.6,
  [0.09, 0.08, 0.08, 0.07, 0.07], 0.24, 0.27, 0.080, 0.026,
  "Founded in 1939 by Enzo Ferrari in Maranello, Italy, initially as a racing team before building road cars. Spun out of Fiat Chrysler in 2015; Benedetto Vigna, a former STMicroelectronics executive, has been CEO since 2021. Ferrari deliberately produces fewer cars than it could sell — roughly 14,000 a year — which sustains scarcity and residual values. Revenue also comes from personalisation options, which carry very high margins, plus Formula One prize money and sponsorship, and brand licensing. It is best understood as a luxury goods company that happens to make cars.",
  [("Cars & spare parts", 76), ("Sponsorship, commercial & brand", 15), ("Engines & Other", 9)],
  ["Order books extend beyond two years, so revenue is effectively pre-sold and demand is not a variable.",
   "Personalisation revenue per car keeps rising and carries luxury-goods margins.",
   "Deliberate volume restraint protects pricing in a way conventional automakers cannot copy."],
  ["Trades at a luxury multiple, which leaves no room for a demand disappointment.",
   "The transition to electric powertrains risks diluting the engine sound and character customers pay for.",
   "The customer base is ultra-wealthy but small, and concentrated in a handful of markets."],
  "Treated as a luxury holding rather than an automotive one. The valuation and the electric transition are the two recurring debates.",
  "Shipment volumes, personalisation revenue per unit, order book length, electric model reception.",
  (5, 3, 5, 5)),

C("GM", "General Motors Company", "autos", "Detroit, Michigan, USA", 1908,
  "Mary Barra", "NYSE", 62.00, 0.94, 95.0, 190.0,
  [0.02, 0.02, 0.02, 0.02, 0.02], 0.045, 0.055, 0.100, 0.018,
  "Founded in 1908 by William Durant in Flint, Michigan; reorganised through bankruptcy in 2009. Mary Barra has been CEO since 2014, the first woman to lead a major global automaker. GM sells Chevrolet, GMC, Buick and Cadillac vehicles, with full-size pickup trucks and SUVs generating the overwhelming majority of profit. Its Ultium battery platform underpins its electric vehicles, GM Financial provides lending, and it operates Cruise autonomous driving after significantly scaling back that programme. Aggressive buybacks have materially reduced the share count.",
  [("GM North America", 84), ("GM Financial", 10), ("International & Other", 6)],
  ["Full-size trucks and SUVs remain enormously profitable and face limited competitive pressure.",
   "The share count has fallen sharply through buybacks, which lifts earnings per share independent of growth.",
   "Trades at a very low multiple of earnings, with the market assigning almost no value to future growth."],
  ["Electric vehicle investment has consumed capital without yet generating returns.",
   "US tariffs raise input costs on parts sourced from Mexico and Canada.",
   "The Chinese joint ventures, once a profit source, are now barely breaking even."],
  "A deep value debate that has moved in GM's favour in 2026, with the shares around $81–83 in late September after the full-year adjusted EBIT outlook was raised to $14–16 billion. Bears point to third-quarter US sales down 5.5% and Cox Automotive's forecast that GM will lose more US market share than any rival this year.",
  "Q3 results on 20 October 2026, North American truck pricing, US market share, EV programme losses, buyback pace, tariff developments, defence business growth.",
  (3, 1, 3, 3)),

C("STLA", "Stellantis N.V.", "autos", "Hoofddorp, Netherlands", 2021,
  "Antonio Filosa", "NYSE / Euronext", 12.50, 2.90, 20.0, 160.0,
  [0.02, 0.03, 0.03, 0.02, 0.02], 0.014, 0.032, 0.110, 0.016,
  "Created in 2021 by merging Fiat Chrysler Automobiles with France's PSA Group. Antonio Filosa became CEO in 2025 after a difficult period. Headquartered in Hoofddorp, Netherlands. Stellantis owns fourteen brands including Jeep, Ram, Dodge, Chrysler, Peugeot, Citroën, Opel, Fiat, Alfa Romeo and Maserati. Jeep and Ram in North America generate most of the profit. The company struggled badly in 2024 and 2025 with US inventory build-up, aggressive pricing and market share losses, and is in the middle of an operational reset.",
  [("North America", 42), ("Enlarged Europe", 38), ("South America & Other", 20)],
  ["Trades at a very low valuation after a near-60% share price fall in 2026, so expectations are minimal.",
   "Fourteen brands and a broad geographic footprint provide multiple routes to recovery.",
   "South American operations are genuinely strong and often overlooked."],
  ["Quality problems have produced a record recall year in 2026, including 1.5 million Ram trucks and 201,976 Jeeps, undermining the brand repair the turnaround depends on.",
   "European emissions regulations require electric vehicle sales that are currently loss-making.",
   "Brand proliferation creates complexity and marketing costs that peers do not carry."],
  "A turnaround with a very low valuation and correspondingly high uncertainty. The shares hit an all-time low of $4.43 in late September 2026, nearly 60% down on the year, even as Filosa reconfirmed guidance for mid-single-digit revenue growth and a low-single-digit operating margin and promised positive industrial free cash flow in 2027. Cheap has kept getting cheaper.",
  "US sales and dealer inventory, recall and quality costs, industrial free cash flow, tariff costs, FaSTLAne 2030 plan delivery.",
  (2, 1, 2, 3)),
]

GLOBAL = [
C("TCEHY", "Tencent Holdings Limited", "global", "Shenzhen, China", 1998,
  "Ma Huateng (Pony Ma)", "OTC (ADR) / HKEX", 88.00, 6.20, 15.0, 105.0,
  [0.09, 0.09, 0.08, 0.07, 0.07], 0.26, 0.28, 0.105, 0.026,
  "Founded in 1998 in Shenzhen by Pony Ma and four classmates, initially building an instant messaging service. Ma is still chairman and CEO. Tencent operates WeChat, which has over 1.3 billion users and functions as messaging, payments, social feed and app platform simultaneously — there is no Western equivalent. It is the largest video game company in the world by revenue, owning Riot Games and Supercell and holding stakes in Epic Games and many others. It also runs fintech through WeChat Pay, cloud services, music streaming, and a very large portfolio of minority stakes in listed and private companies.",
  [("Value-Added Services (games & social)", 50), ("Fintech & Business Services", 32), ("Online Advertising", 17), ("Other", 1)],
  ["WeChat is the most complete consumer platform in the world and is effectively unregulated as a competitor within China.",
   "The investment portfolio holds tens of billions in listed stakes that are not fully reflected in the valuation.",
   "Games are a high-margin, cash-generative business with strong intellectual property."],
  ["Chinese regulatory policy toward technology platforms can change abruptly and has done so before.",
   "US listing and delisting risk affects ADR holders specifically.",
   "Chinese consumer spending has been weak and advertising revenue follows it."],
  "Consensus generally sees it as inexpensive relative to Western platform peers, with the discount attributed to regulatory and geopolitical risk rather than business quality. Second-quarter 2026 revenue grew 11%, driven by AI-assisted advertising and steady games, but net profit missed estimates as capital expenditure rose 65%, so the near-term debate has shifted to the return on AI spending.",
  "Domestic game approvals, advertising revenue growth, AI capital expenditure and returns, WeChat mini-programme monetisation, regulatory signals.",
  (5, 3, 5, 5)),

C("BABA", "Alibaba Group Holding Limited", "global", "Hangzhou, China", 1999,
  "Eddie Wu", "NYSE (ADR) / HKEX", 145.00, 2.35, -25.0, 140.0,
  [0.08, 0.08, 0.07, 0.07, 0.06], 0.14, 0.18, 0.110, 0.026,
  "Founded in 1999 by Jack Ma and seventeen colleagues in his Hangzhou apartment. Eddie Wu became CEO in 2023. Alibaba runs Taobao and Tmall, the dominant Chinese e-commerce marketplaces, plus AliExpress and Lazada internationally, and Cainiao logistics. Alibaba Cloud is the largest cloud provider in China and has become the strategic priority as artificial intelligence demand grows — its Qwen open-weight models are widely used across Asia. It also holds a stake in Ant Group, which operates Alipay.",
  [("Taobao & Tmall (China commerce)", 44), ("Cloud Intelligence", 12), ("International Commerce", 14), ("Cainiao, Local Services & Other", 30)],
  ["Alibaba Cloud is the leading Chinese AI infrastructure provider, and cloud and AI revenue grew 45% to 48.4 billion yuan in the June 2026 quarter.",
   "The HK$80 billion placement in August 2026 gives the AI build-out dedicated funding without relying on e-commerce cash flow.",
   "The Qwen model family has real international adoption, giving Alibaba a genuine AI asset."],
  ["Domestic e-commerce competition from PDD and Douyin has permanently compressed take rates.",
   "AI spending turned quarterly free cash flow negative and the August 2026 placement diluted shareholders by about 3.7%, so per-share returns depend on that investment paying off.",
   "US-China policy risk affects both the listing and access to advanced semiconductors for the cloud business."],
  "A value-versus-geopolitics debate that has turned into an AI spending debate. The shares were down about 27% in 2026 by late September after five consecutive earnings misses and a dilutive $10.2 billion placement, although 45% cloud growth keeps the consensus price target well above the share price.",
  "Cloud revenue growth, customer management revenue, AI capital expenditure and free cash flow, September-quarter results in November, chip access for AI training.",
  (4, 3, 4, 5)),

C("005930", "Samsung Electronics Co., Ltd.", "global", "Suwon, South Korea", 1969,
  "Jun Young-hyun", "Korea Exchange", 220.00, 5.70, -60.0, 235.0,
  [0.18, 0.06, -0.06, 0.06, 0.07], 0.215, 0.185, 0.110, 0.024,
  "Founded in 1969 as Samsung Electric Industries in Suwon, South Korea, part of the Samsung chaebol established in 1938. Samsung is the only company that competes at scale in memory, foundry, smartphones and displays simultaneously. Its Device Solutions division makes DRAM, NAND and logic chips; Mobile Experience makes Galaxy phones; Visual Display makes televisions; and Samsung Display supplies OLED panels including to Apple. It reported record quarterly operating profit in 2026 on the memory upcycle, and its share price still fell on the news. ADR-equivalent pricing shown.",
  [("Device Solutions (semiconductors)", 45), ("Mobile eXperience", 33), ("Display", 13), ("Consumer Electronics", 9)],
  ["The only company with leading positions across memory, foundry, displays and handsets, which no competitor can match.",
   "Record operating profit in the 2026 memory cycle demonstrates the earnings power of the semiconductor division.",
   "Historically trades at a large discount to global peers because of the Korean market discount."],
  ["Memory is cyclical and Samsung's earnings swing more violently than almost any other large-cap technology company.",
   "Its foundry business has lost ground to TSMC; losses are narrowing on demand for HBM4 base dies, but the division is still loss-making.",
   "SK Hynix still leads in HBM supply to Nvidia, although Samsung expected its HBM4 revenue to more than triple in the third quarter of 2026."],
  "Viewed as inexpensive relative to its own earnings power but persistently discounted for governance and cyclicality. The shares fell 8.7% on 24 August 2026 after a record 90–110 trillion won shareholder return plan disappointed investors who wanted immediate buyback and cancellation details. Its HBM4 position with Nvidia remains the swing factor.",
  "Q3 preliminary results on 8 October 2026, buyback and cancellation details in January 2027, HBM4 share at Nvidia, DRAM pricing, foundry customer wins.",
  (4, 3, 4, 5)),

C("RELIANCE", "Reliance Industries Limited", "global", "Mumbai, India", 1966,
  "Mukesh Ambani", "NSE / BSE", 18.50, 13.53, 22.0, 120.0,
  [0.09, 0.09, 0.08, 0.08, 0.07], 0.09, 0.12, 0.105, 0.030,
  "Founded in 1966 by Dhirubhai Ambani as a textile trading business. His son Mukesh Ambani has led it since 2002 and turned it into India's largest company. Three engines: the original oil-to-chemicals business, including the world's largest single-site refinery at Jamnagar; Jio, which built a nationwide 4G and 5G network from scratch and became India's largest mobile operator with over 520 million customers; and Reliance Retail, the country's largest retailer by revenue. Jio Platforms is preparing an initial public offering in October 2026, and Retail is also expected to list separately. Prices shown per share in US dollar terms.",
  [("Oil to Chemicals", 40), ("Jio (telecom & digital)", 26), ("Retail", 29), ("Oil & Gas E&P", 5)],
  ["Jio has enormous operating leverage — the network is built and every additional subscriber is close to pure margin.",
   "Indian consumption growth is one of the strongest structural stories in global equities.",
   "The Jio Platforms IPO, expected to open on 21 October 2026 as India's largest at about $3.8 billion, should crystallise value the conglomerate structure obscures."],
  ["The oil-to-chemicals business is capital intensive and exposed to refining margin volatility.",
   "Capital allocation is controlled by a single family, which limits minority shareholder influence.",
   "Telecom tariff increases in India are politically sensitive and hard to push through."],
  "Held as the primary listed proxy for Indian consumption. With the Jio Platforms IPO set for late October 2026 and a reported price band implying a valuation of around ₹15 lakh crore, the debate has moved to how much of that value is reflected in Reliance's own share price and when Retail follows.",
  "Jio IPO pricing and listing (expected 28 October 2026), Jio average revenue per user, retail store expansion, refining margins, Retail listing timing.",
  (4, 4, 4, 4)),

C("INFY", "Infosys Limited", "global", "Bengaluru, India", 1981,
  "Salil Parekh", "NYSE (ADR) / NSE", 21.00, 4.14, -4.0, 20.0,
  [0.07, 0.08, 0.08, 0.07, 0.07], 0.19, 0.21, 0.098, 0.028,
  "Founded in 1981 by seven engineers led by N. R. Narayana Murthy with about $250 of borrowed capital, in Pune, now headquartered in Bengaluru. Salil Parekh has been CEO since 2018. Infosys provides information technology services to large enterprises worldwide: application development and maintenance, cloud migration, business process outsourcing and, increasingly, artificial intelligence implementation through its Topaz platform. Its clients are concentrated in financial services, retail and telecommunications in North America and Europe. It employs over 300,000 people.",
  [("Financial Services", 28), ("Retail & Consumer", 15), ("Communications", 12), ("Manufacturing, Energy & Other", 45)],
  ["Enterprises need help implementing AI, and systems integrators capture that spending before software vendors do.",
   "Very high return on capital with almost no debt and consistent dividend payments.",
   "Cost arbitrage remains meaningful and Infosys has scale in delivery centres competitors cannot easily build."],
  ["AI code generation is a genuine long-term threat to a business model priced by billable hours.",
   "Discretionary technology spending in banking and retail has been weak.",
   "Currency translation between the rupee and the dollar adds volatility."],
  "The central debate is whether AI expands the services opportunity or eventually destroys the labour arbitrage the model rests on. The market has leaned towards the bearish answer: by mid-September 2026 the Indian-listed shares were down 24.9% for the year.",
  "Q2 FY27 results on 23 October 2026, large deal total contract value, headcount and utilisation, discretionary spending recovery, AI deal mix.",
  (3, 3, 5, 5)),

C("PDD", "PDD Holdings Inc.", "global", "Dublin, Ireland", 2015,
  "Chen Lei", "Nasdaq (ADR)", 118.00, 1.39, -45.0, 62.0,
  [0.12, 0.12, 0.10, 0.09, 0.08], 0.215, 0.235, 0.138, 0.026,
  "Founded in 2015 by Colin Huang as Pinduoduo, a group-buying platform that used social sharing on WeChat to aggregate demand and drive prices down. Chen Lei is co-CEO; the holding company redomiciled to Dublin. PDD runs Pinduoduo in China, focused on value-conscious consumers and agricultural produce, and Temu, the cross-border marketplace that expanded into North America and Europe at extraordinary speed by shipping directly from Chinese manufacturers. Temu's growth has been driven by very heavy advertising spending.",
  [("Online marketplace services (China)", 62), ("Transaction services (incl. Temu)", 38)],
  ["Extremely capital-light — PDD does not hold inventory or own logistics, so incremental margins are very high.",
   "Large net cash position built from years of strong cash generation.",
   "Temu built global brand recognition faster than almost any consumer platform in history."],
  ["Temu's economics depend on de minimis import exemptions that regulators in the US and EU are removing; European monthly active users fell 30% after EU tariff changes on 1 July 2026.",
   "Marketing spend is enormous and the growth stops if it is reduced.",
   "Disclosure quality is thin even by Chinese ADR standards, and management rarely engages with investors."],
  "Divisive. Second-quarter 2026 revenue rose only 8% to 112.4 billion yuan and missed estimates, while non-GAAP net income of 28.5 billion yuan fell 13% but beat consensus, and the shares rose about 3% to $91.10. Bulls point to margins and 456.4 billion yuan of cash; bears focus on regulatory dependence, slowing Temu user numbers and opacity.",
  "Temu regulatory developments in the US and EU, Temu European user trends, marketing spend as a share of revenue, domestic take rate.",
  (3, 4, 3, 5)),
]

FRONTIER = [
C("SPCX", "SpaceX (Space Exploration Technologies)", "frontier", "Starbase, Texas, USA", 2002,
  "Elon Musk", "Nasdaq", 123.54, 13.20, -60.0, 30.0,
  [0.55, 0.42, 0.33, 0.26, 0.21], 0.02, 0.18, 0.130, 0.035,
  "Founded in 2002 by Elon Musk with the stated goal of making humanity multiplanetary. Headquartered at Starbase, Texas, with Gwynne Shotwell as President and COO. SpaceX completed the largest IPO in history on 12 June 2026, pricing at $135 and closing its first day at $160.95 for a market capitalisation above $2 trillion. Three businesses: launch, using the reusable Falcon 9 and the Starship system; Starlink satellite broadband, which passed 10.3 million customers across 160 markets and generated about 61% of 2025 revenue; and artificial intelligence, following the acquisition of xAI in February 2026.",
  [("Starlink broadband", 61), ("Launch services", 30), ("xAI & Other", 9)],
  ["Reusable rockets have cut launch costs by roughly an order of magnitude, and no competitor has matched it at scale.",
   "Starlink reached 12 million subscribers in the second quarter of 2026, double a year earlier, with a 38.6% operating margin on $4.29 billion of quarterly revenue.",
   "Vertical integration from rocket to satellite to ground terminal means SpaceX controls its own cost curve."],
  ["The AI segment posted a $1.26 billion operating loss in the second quarter of 2026, after $2.47 billion in the first, and quarterly capital spending of $18.4 billion far exceeded analyst forecasts.",
   "The stock traded as high as $225.64 in its first weeks, fell to around $110 in early August, and a much larger lock-up release in early December will add supply, so volatility is extreme.",
   "The valuation requires believing revenue can grow from $18.7 billion in 2025 to something enormous; Musk has publicly suggested roughly $1 trillion by 2030, which no credible model supports."],
  "Still sharply split. The first quarterly report on 4 August 2026 beat expectations, with revenue up 92% to $7.8 billion against a $6.9 billion consensus, but the shares fell because second-quarter capital spending of $18.4 billion annualises well above forecasts. Short sellers held about 35% of tradable shares in early August, and published valuations range from Morningstar's $63 fair value to Wedbush's $190 target.",
  "Starship cadence after the first orbital flight on 28 September 2026, early-December lock-up expiry, capital spending versus free cash flow, AI segment losses, Starlink subscriber additions.",
  (5, 5, 3, 4)),

C("COIN", "Coinbase Global, Inc.", "frontier", "Remote-first, USA", 2012,
  "Brian Armstrong", "Nasdaq", 340.00, 0.265, -8.0, 8.2,
  [0.22, 0.18, 0.15, 0.12, 0.11], 0.26, 0.30, 0.135, 0.030,
  "Founded in 2012 by Brian Armstrong and Fred Ehrsam and listed by direct listing in 2021. The company is remote-first with no formal headquarters. Coinbase is the largest regulated cryptocurrency exchange in the United States, earning transaction fees from retail and institutional trading. It also runs Coinbase Prime for institutions, provides custody for most US spot bitcoin exchange-traded funds, operates the Base layer-2 blockchain, and earns a large share of the interest income on USDC reserves through its partnership with Circle. It announced a partnership with JPMorgan in July 2026.",
  [("Transaction revenue", 52), ("Subscriptions & services (incl. USDC)", 44), ("Other", 4)],
  ["Regulatory clarity in the US has improved substantially, and Coinbase is the most compliant large venue.",
   "Subscription and services revenue, particularly stablecoin interest, is far less volatile than trading fees.",
   "Custody for the majority of US spot bitcoin ETFs is a recurring, high-margin franchise."],
  ["Transaction revenue is directly tied to crypto trading volumes, which collapse in bear markets.",
   "Interest income on USDC reserves falls if the Fed cuts rates — though the 2026 hawkish shift is currently a tailwind.",
   "Competition from traditional brokerages and offshore exchanges compresses fee rates."],
  "Treated as a leveraged proxy for crypto market activity with an improving recurring revenue base, but sentiment has cooled: the shares were around $182 in early October 2026, far below the 52-week high of $402.16, after a second quarter in which revenue fell 18.5% year on year. Analysts sit at a consensus Hold, with Bank of America arguing that stablecoin income benefits from the Fed's September 2026 rate hike even as trading volumes lag crypto prices.",
  "Crypto trading volumes, USDC balances, Base activity, regulatory developments, institutional adoption.",
  (4, 4, 3, 4)),

C("CRWV", "CoreWeave, Inc.", "frontier", "Livingston, New Jersey, USA", 2017,
  "Michael Intrator", "Nasdaq", 77.12, 0.49, 14.0, 8.5,
  [0.55, 0.40, 0.30, 0.22, 0.17], 0.05, 0.20, 0.145, 0.032,
  "Founded in 2017 by Michael Intrator, Brian Venturo and Brannin McBee as a cryptocurrency mining operation, then repurposed its GPU fleet for AI workloads. Headquartered in Livingston, New Jersey. CoreWeave is a specialised cloud provider that rents NVIDIA GPU capacity to AI labs and enterprises under long-term contracts, competing with the hyperscalers on speed of deployment rather than breadth of services. Microsoft and OpenAI have been among its largest customers. The stock fell nearly 14% on 1 July 2026 after Meta unveiled Meta Compute, a plan to resell its own surplus AI capacity to outside customers — a direct threat given that CoreWeave itself holds a $21 billion supply contract with Meta.",
  [("GPU cloud compute contracts", 96), ("Other services", 4)],
  ["Contracted backlog gives multi-year revenue visibility that is unusual for a company at this stage.",
   "Deploys new NVIDIA hardware faster than the hyperscalers, which matters enormously when capacity is scarce.",
   "Deep relationship with NVIDIA, which has itself invested in the company."],
  ["Customer concentration is extreme — a small number of contracts represent most of the revenue.",
   "The business is financed with substantial debt secured against GPUs, which depreciate quickly; quarterly interest expense reached $640 million in the second quarter of 2026 and is guided to $860–940 million for the third.",
   "If major customers turn into direct competitors by reselling their own surplus capacity, as Meta signalled with its July 2026 Meta Compute launch, the scarcity pricing this entire business model depends on erodes fast."],
  "Among the most volatile large caps in the market and a pure expression of the AI infrastructure debate. Second-quarter 2026 revenue more than doubled to $2.58 billion and backlog reached $104 billion, yet the shares traded around $85 in September, well below the May peak of $136.80, as investors weighed full-year capital spending guidance of $35–39 billion and rising interest costs. Analysts remain largely positive, with Jefferies reiterating Buy and a $150 target in October.",
  "Q3 results, backlog conversion, capital spending against the $35–39 billion guide, interest expense and debt terms, active power growth from 1.5 GW, GPU depreciation schedules, hyperscaler capex plans.",
  (2, 5, 2, 2)),

C("VRT", "Vertiv Holdings Co", "frontier", "Westerville, Ohio, USA", 1965,
  "Giordano Albertazzi", "NYSE", 185.00, 0.383, 2.0, 10.5,
  [0.24, 0.21, 0.18, 0.15, 0.13], 0.13, 0.17, 0.100, 0.028,
  "Originally the Emerson Network Power division, founded in 1965 and separated in 2016, then listed via a special purpose acquisition company in 2020. Giordano Albertazzi is CEO, headquartered in Westerville, Ohio. Vertiv makes the physical infrastructure that keeps data centres running: uninterruptible power supplies, busways, switchgear, precision cooling, and — most importantly for AI — liquid cooling systems. High-density AI racks generate too much heat for air cooling, which has made liquid cooling a requirement rather than an option and put Vertiv in a strong position.",
  [("Americas", 55), ("EMEA", 27), ("APAC", 18)],
  ["Liquid cooling is mandatory for high-density AI racks, and Vertiv is one of very few suppliers with scale.",
   "Order backlog has grown faster than revenue, indicating demand well ahead of delivery capability.",
   "Services and spare parts on installed equipment provide recurring revenue."],
  ["Directly exposed to any slowdown in data centre construction, which is the crowded consensus trade.",
   "Competition from Schneider Electric, Eaton and specialised cooling manufacturers is increasing.",
   "The stock is priced for sustained high growth and de-rates quickly on any stumble: it fell about 35% from its peak after management said in July 2026 that some second-quarter revenue had slipped on large multi-phase projects and supply constraints."],
  "A favoured picks-and-shovels way to own AI data centre build-out. The concern that everyone already knows the story was borne out when project delays disclosed on 29 July 2026 pushed the shares about 35% below their peak, though new coverage such as BMO's Outperform initiation in October argues the bad news is largely priced in.",
  "Q3 results around 28 October 2026, recovery of delayed project revenue, order growth and book-to-bill, liquid cooling revenue mix, hyperscaler capex.",
  (3, 5, 4, 4)),

C("ANET", "Arista Networks, Inc.", "frontier", "Santa Clara, California, USA", 2004,
  "Jayshree Ullal", "NYSE", 145.00, 1.27, -8.0, 9.5,
  [0.22, 0.19, 0.16, 0.13, 0.11], 0.33, 0.35, 0.095, 0.030,
  "Founded in 2004 by Andy Bechtolsheim, David Cheriton and Ken Duda. Jayshree Ullal has been CEO since 2008 and built it into the leading supplier of high-speed data centre networking. Arista sells Ethernet switches running its EOS operating system, a single software image across the entire product line that is a genuine advantage over competitors' fragmented software. Its customers are concentrated among hyperscalers — Microsoft and Meta have historically been the largest — and AI clusters require enormous quantities of high-bandwidth switching to connect thousands of accelerators.",
  [("Product (switching hardware)", 82), ("Services & software subscriptions", 18)],
  ["AI clusters need vastly more networking per server than traditional data centres, so Arista's content per rack rises.",
   "The single EOS software image is a real technical advantage that Cisco has never matched.",
   "Gross margins above 60% are exceptional for networking hardware."],
  ["Customer concentration among a handful of hyperscalers is severe, and they negotiate hard.",
   "Those same customers are developing their own switching silicon and white-box alternatives.",
   "Ethernet versus InfiniBand competition in AI fabrics is not fully settled, and NVIDIA controls the alternative."],
  "Regarded as the highest-quality networking asset, and recent results have reinforced that: second-quarter 2026 revenue rose 37.7% to $3.04 billion, ahead of expectations, with third-quarter guidance of about $3.3 billion. Customer concentration and the threat of in-house designs remain the recurring objections, but new coverage such as Bernstein's Outperform initiation in September 2026 has been positive.",
  "Hyperscaler capex, AI networking revenue disclosure, gross margin, competitive wins against white-box.",
  (4, 4, 5, 5)),

C("RKLB", "Rocket Lab Corporation", "frontier", "Long Beach, California, USA", 2006,
  "Peter Beck", "Nasdaq", 62.00, 0.52, -1.5, 0.75,
  [0.55, 0.45, 0.36, 0.28, 0.22], -0.05, 0.14, 0.150, 0.035,
  "Founded in 2006 by Peter Beck in New Zealand and now headquartered in Long Beach, California, listed via a special purpose acquisition company in 2021. Beck is still CEO. Rocket Lab launches small satellites on its Electron rocket, the second most frequently launched US orbital vehicle, and is developing Neutron, a medium-lift reusable rocket intended to compete directly with SpaceX's Falcon 9. Its Space Systems division — building satellite components, solar arrays, separation systems and complete spacecraft for other operators — actually generates the majority of revenue.",
  [("Space Systems", 72), ("Launch Services", 28)],
  ["Neutron would move Rocket Lab into the far larger medium-lift market where SpaceX currently has little competition.",
   "The Space Systems components business is already substantial and gives revenue while launch scales.",
   "Government and defence demand for responsive launch capability is growing with geopolitical tension."],
  ["The company is not yet consistently profitable and our model reflects a negative starting free cash flow margin.",
   "Neutron's first flight has slipped repeatedly; as of August 2026 the vehicle was due to reach the pad in the fourth quarter, and rocket development schedules almost always slip further.",
   "SpaceX's scale advantage in launch is enormous and now backed by public market capital after the June 2026 IPO."],
  "A speculative growth name where the thesis rests heavily on Neutron succeeding. Second-quarter 2026 revenue rose 62% to $234 million and backlog reached a record $2.36 billion, and Citi initiated at Buy with a $105 target in October, but the shares were around $74 in early October after a steep fall from their highs. Position sizing matters more than the price target here.",
  "Neutron first launch, closing of the Iridium acquisition, Electron launch cadence, Space Systems contract awards, cash burn.",
  (3, 5, 2, 3)),

C("IONQ", "IonQ, Inc.", "frontier", "College Park, Maryland, USA", 2015,
  "Niccolo de Masi", "NYSE", 55.00, 0.40, -1.2, 0.16,
  [0.68, 0.54, 0.43, 0.34, 0.27], -0.40, 0.06, 0.165, 0.038,
  "Founded in 2015 by Christopher Monroe and Jungsang Kim, commercialising trapped-ion quantum computing research from the University of Maryland and Duke. Headquartered in College Park, Maryland. IonQ builds quantum computers that hold individual ytterbium ions in electromagnetic traps and manipulate them with lasers, an approach with high qubit fidelity but slower gate speeds than superconducting designs. It sells systems directly, including a 256-qubit machine to the University of Cambridge in the first quarter of 2026, and provides cloud access through AWS, Azure and Google Cloud. It acquired SkyWater Technology for $1.8 billion to manufacture its own chips.",
  [("Quantum systems & cloud access", 100)],
  ["Trapped-ion qubits have the highest fidelity of any commercial approach, which matters more than raw qubit count.",
   "The SkyWater acquisition gives domestic chip manufacturing and vertical integration no other pure-play has.",
   "White House executive orders in June 2026 direct federal agencies to accelerate quantum adoption, with Defense Department deadlines through 2028."],
  ["Revenue guidance of $450–460 million for 2026 comes mostly from the newly acquired SkyWater foundry, so quantum revenue is still tiny relative to the market capitalisation — this is a research programme with a stock price attached.",
   "Cash burn is heavy and the company has repeatedly raised equity, diluting existing holders.",
   "DARPA's Quantum Benchmarking Initiative is designed to test whether any approach reaches utility scale by 2033, which is a long time to fund losses."],
  "Widely covered but honestly not valuable to model with a discounted cash flow. Sentiment improved in September 2026 after the guidance raise, the Superion 256 launch and an NVIDIA deployment, and Bank of America initiated at Buy with a $60 target, though much of the higher revenue outlook reflects the SkyWater foundry rather than quantum sales. Treat any quantum pure-play as a small speculative position, not a core holding.",
  "Superion 256 deliveries in 2027, quantum versus foundry revenue mix, bookings and backlog, cash runway, federal quantum contract awards, dilution.",
  (2, 5, 1, 3)),

C("MSTR", "Strategy Inc. (MicroStrategy)", "frontier", "Tysons Corner, Virginia, USA", 1989,
  "Phong Le", "Nasdaq", 93.33, 0.30, 8.0, 0.48,
  [0.05, 0.05, 0.05, 0.05, 0.05], 0.05, 0.10, 0.160, 0.025,
  "Founded in 1989 by Michael Saylor as a business intelligence software company. Phong Le is CEO; Saylor is executive chairman and drives strategy. Since 2020 the company has pursued an explicit treasury policy of acquiring and holding bitcoin, funded through convertible notes, preferred stock and at-the-market equity issuance. It renamed itself Strategy in 2025. The original enterprise analytics software business still exists and generates modest revenue, but the share price behaves almost entirely as a leveraged claim on bitcoin rather than as a software equity.",
  [("Bitcoin treasury (balance sheet)", 0), ("Enterprise analytics software", 100)],
  ["Provides leveraged bitcoin exposure through a regular brokerage account, which some mandates cannot obtain directly.",
   "Convertible note issuance has historically been executed at favourable terms during periods of high volatility.",
   "The software business, while small, generates cash that services some of the financing."],
  ["A discounted cash flow on the software business tells you almost nothing about the share price, and we want to be explicit about that.",
   "The premium to net asset value swings wildly and has at times exceeded 100%, which is a pure sentiment premium.",
   "Leverage cuts both ways — during the bitcoin drawdown in mid-2026 the company sold bitcoin to fund buybacks of its STRC preferred stock, showing that financing pressure is real."],
  "Not a conventional equity and not conventionally coverable. Our model values only the operating software business, so the fair value output is deliberately far below the market price. The shares more than doubled from late-June 2026 lows as bitcoin recovered and the company resumed buying, taking holdings to 848,000 BTC, and Citi raised its target to $240 in October; that gap is the bitcoin treasury and the sentiment premium, and readers should size any position accordingly.",
  "Bitcoin price, premium to net asset value, bitcoin sales or purchases, preferred stock issuance and buybacks, USD reserve, dilution from at-the-market sales.",
  (1, 1, 1, 2)),
]
