from .schema import C

CONSUMER = [
C("AAPL", "Apple Inc.", "consumer", "Cupertino, California, USA", 1976,
  "Tim Cook", "Nasdaq", 308.63, 14.30, 15.0, 425.0,
  [0.07, 0.07, 0.06, 0.06, 0.05], 0.26, 0.28, 0.084, 0.028,
  "Founded on 1 April 1976 by Steve Jobs, Steve Wozniak and Ronald Wayne. Tim Cook has been CEO since 2011, headquartered at Apple Park in Cupertino. The iPhone is roughly half of revenue; the rest comes from Mac, iPad, Apple Watch, AirPods and the Vision Pro headset. The Services business — the App Store, iCloud, Apple Music, Apple TV+, Apple Pay and the licensing payment Google makes to remain the default search engine in Safari — carries far higher margins than hardware and is the main driver of profit growth. Apple designs its own M-series and A-series silicon, manufactured by TSMC.",
  [("iPhone", 51), ("Services", 26), ("Wearables, Home & Accessories", 9), ("Mac", 8), ("iPad", 6)],
  ["Services revenue carries roughly 75% gross margins and grows without requiring a hardware refresh cycle.",
   "An installed base above two billion active devices is the largest premium consumer platform ever assembled.",
   "Buys back enormous quantities of stock every year, which compounds earnings per share even in flat revenue years."],
  ["Apple Intelligence has lagged competitors, and the perception that Apple is behind on AI has been a persistent overhang.",
   "The Google search default payment is a significant share of Services profit and is directly threatened by antitrust remedies.",
   "China is both a large market and the manufacturing base, which makes tariff and geopolitical risk two-sided."],
  "The most widely owned stock in the world and correspondingly well covered. The live debate is whether the AI gap matters commercially or whether the installed base makes Apple a fast follower with no penalty.",
  "iPhone upgrade cycle, Services growth rate, Google default ruling, Apple Intelligence rollout.",
  (5, 2, 5, 5)),

C("WMT", "Walmart Inc.", "consumer", "Bentonville, Arkansas, USA", 1962,
  "Doug McMillon", "NYSE", 112.76, 7.97, 30.0, 705.0,
  [0.05, 0.05, 0.05, 0.04, 0.04], 0.030, 0.042, 0.076, 0.026,
  "Founded in 1962 by Sam Walton in Rogers, Arkansas, still headquartered in nearby Bentonville. Doug McMillon is CEO. Walmart is the largest company in the world by revenue, serving roughly 250 million customers weekly across more than 10,500 stores. It crossed a $1T market capitalisation on 3 February 2026. Beyond retail, it has built three high-margin businesses that are changing the profit mix entirely: Walmart Connect advertising, Walmart Marketplace for third-party sellers, and Walmart+ membership. Sam's Club operates as a separate warehouse format.",
  [("Walmart US", 69), ("Walmart International", 18), ("Sam's Club", 13)],
  ["Advertising, marketplace and membership carry far higher margins than retail and are growing much faster than the base business.",
   "In an inflationary environment consumers trade down to Walmart, so it gains share exactly when others struggle.",
   "Grocery is roughly 60% of US sales, which makes traffic remarkably stable through downturns."],
  ["Retail operating margins are around 4%, so there is very little cushion for execution error.",
   "The 2026 oil shock raises both logistics costs and consumer stress simultaneously.",
   "The valuation has re-rated substantially and now embeds continued high-margin revenue mix shift."],
  "The consensus defensive retail holding, with the debate about how much of the advertising and marketplace re-rating is already reflected in a multiple far above its historical range.",
  "US comparable sales, e-commerce profitability, advertising revenue growth, grocery market share.",
  (5, 3, 5, 5)),

C("COST", "Costco Wholesale Corporation", "consumer", "Issaquah, Washington, USA", 1983,
  "Ron Vachris", "Nasdaq", 951.67, 0.444, -6.0, 275.0,
  [0.07, 0.07, 0.06, 0.06, 0.05], 0.024, 0.030, 0.078, 0.026,
  "Founded in 1983 in Seattle by Jim Sinegal and Jeffrey Brotman, merged with Price Club in 1993. Ron Vachris became CEO in 2024. Costco operates roughly 900 warehouses worldwide on a deliberately unusual model: it caps markups on merchandise at around 14%, sells a limited assortment in bulk, and earns most of its actual profit from annual membership fees. Renewal rates in the US and Canada exceed 92%. The Kirkland Signature private label has become one of the largest consumer brands in the world.",
  [("Merchandise sales", 98), ("Membership fees", 2)],
  ["Membership fee income is close to pure profit and renews at above 90%, which is extraordinary customer loyalty.",
   "Deliberately low merchandise margins create a price advantage competitors cannot match without destroying their own economics.",
   "Kirkland Signature commands genuine brand preference while carrying private label economics."],
  ["One of the most expensive large-cap retailers in the world on earnings, and it rarely gets cheaper.",
   "Membership fee increases are infrequent, so the profit step-ups they create are lumpy.",
   "International expansion is slow by design and limits the pace of unit growth."],
  "Universally admired operationally and almost universally considered expensive. That tension has persisted for a decade.",
  "Comparable sales excluding fuel, membership renewal rates, fee increase timing, warehouse openings.",
  (5, 3, 5, 5)),

C("PG", "The Procter & Gamble Company", "consumer", "Cincinnati, Ohio, USA", 1837,
  "Jon Moeller", "NYSE", 151.41, 2.34, 26.0, 85.0,
  [0.03, 0.03, 0.03, 0.03, 0.03], 0.19, 0.20, 0.070, 0.022,
  "Founded in 1837 in Cincinnati by William Procter, a candle maker, and James Gamble, a soap maker, who had married sisters. Jon Moeller is CEO. P&G owns a portfolio of consumer staples brands where each is a category leader: Tide and Ariel in laundry, Pampers in baby care, Gillette in grooming, Head & Shoulders and Pantene in hair care, Oral-B, Crest, Bounty, Charmin and SK-II. It deliberately exited dozens of smaller brands to concentrate on categories where scale and advertising spend create a durable advantage.",
  [("Fabric & Home Care", 35), ("Baby, Feminine & Family Care", 24), ("Beauty", 18), ("Health Care", 14), ("Grooming", 9)],
  ["Pricing power in staples is real — P&G raised prices through the inflation of 2021-23 with limited volume loss.",
   "Advertising scale creates a barrier private labels cannot overcome in most of its categories.",
   "Nearly seventy consecutive years of dividend increases, one of the longest records in the market."],
  ["Volume growth is close to zero, so the story depends entirely on price and mix.",
   "Private label share gains accelerate when consumers are stressed, and the 2026 oil shock is pressuring budgets.",
   "GLP-1 weight loss drugs are reducing snacking and grooming category consumption in ways that are hard to model."],
  "The archetypal defensive holding. The bear case is that low-single-digit growth does not justify a premium multiple when bond yields are above 4.5%.",
  "Organic sales growth split between price and volume, private label share data, input cost trends.",
  (5, 1, 5, 5)),

C("KO", "The Coca-Cola Company", "consumer", "Atlanta, Georgia, USA", 1892,
  "James Quincey", "NYSE", 84.14, 4.31, 30.0, 48.0,
  [0.05, 0.05, 0.04, 0.04, 0.04], 0.23, 0.25, 0.072, 0.024,
  "The Coca-Cola formula was created by pharmacist John Pemberton in 1886; the company was incorporated in 1892 in Atlanta, where it remains. James Quincey is CEO. Coca-Cola mostly sells concentrate to independent bottlers rather than finished drinks, which is why its margins are far higher than a beverage manufacturer's. Its portfolio extends well beyond the flagship cola to Sprite, Fanta, Minute Maid, Dasani and smartwater, Powerade, Costa Coffee, Topo Chico and BodyArmor. It has been shifting deliberately toward zero-sugar and non-carbonated categories.",
  [("Sparkling soft drinks", 68), ("Water, sports, coffee & tea", 19), ("Juice, dairy & plant-based", 13)],
  ["The concentrate model means Coca-Cola captures brand economics while bottlers carry the capital intensity.",
   "Unrivalled global distribution — the product is available in more places than almost any other manufactured good.",
   "Pricing power in emerging markets provides an inflation hedge."],
  ["Sugar taxes and health regulation keep expanding across markets.",
   "GLP-1 drugs suppress appetite and calorie consumption, which is a slow structural headwind for the category.",
   "A strong dollar reduces the value of the large share of profit earned overseas."],
  "A defensive core position, generally viewed as fairly valued. The bear case is structural volume decline in sparkling drinks over a long horizon.",
  "Organic revenue split between price and volume, emerging market case volumes, currency effects.",
  (5, 2, 5, 4)),

C("MCD", "McDonald's Corporation", "consumer", "Chicago, Illinois, USA", 1955,
  "Chris Kempczinski", "NYSE", 280.63, 0.703, 52.0, 27.0,
  [0.05, 0.05, 0.04, 0.04, 0.04], 0.31, 0.33, 0.076, 0.024,
  "The first McDonald's franchise was opened by Ray Kroc in Des Plaines, Illinois in 1955, building on a restaurant run by the McDonald brothers in San Bernardino. Chris Kempczinski is CEO, headquartered in Chicago. Around 95% of its roughly 43,000 restaurants are franchised, so McDonald's primarily collects rent and royalties rather than running restaurants. It is one of the largest commercial property owners in the world, because it typically owns or controls the land under its franchised locations — a detail that explains much of its financial resilience.",
  [("Franchised restaurant revenue", 62), ("Company-operated restaurants", 35), ("Other", 3)],
  ["The franchise and property model produces rent-like cash flows with very high margins and low capital needs.",
   "Value positioning means McDonald's tends to gain traffic when consumers trade down.",
   "Digital ordering, delivery and loyalty have raised average check and visit frequency."],
  ["Low-income consumer traffic weakened notably in 2025 and 2026 as household budgets tightened.",
   "Around $52B of net debt, held deliberately, is more expensive to service as rates stay higher.",
   "GLP-1 drugs reduce fast food consumption among an expanding patient population."],
  "Held as a defensive consumer name with property backing. The debate is over traffic among lower-income customers and the durability of value promotions.",
  "US comparable sales, traffic versus average check, international developmental licensed market trends.",
  (5, 2, 5, 3)),

C("HD", "The Home Depot, Inc.", "consumer", "Atlanta, Georgia, USA", 1978,
  "Ted Decker", "NYSE", 357.90, 0.995, 45.0, 165.0,
  [0.04, 0.05, 0.05, 0.04, 0.04], 0.09, 0.11, 0.084, 0.025,
  "Founded in 1978 by Bernie Marcus and Arthur Blank after both were fired from a hardware chain. Ted Decker is CEO, headquartered in Atlanta. Home Depot operates roughly 2,350 large-format home improvement stores across the US, Canada and Mexico. About half of sales go to professional contractors rather than consumers, and the acquisitions of SRS Distribution and GMS pushed it deeper into supplying roofing, landscaping and building products directly to trade customers, a market far larger than retail DIY.",
  [("Building materials & décor", 55), ("Hardlines", 25), ("Pro & specialty distribution", 20)],
  ["The professional contractor business is larger, stickier and less cyclical than consumer DIY.",
   "Housing stock in the US is old, and ageing homes require maintenance regardless of transaction volumes.",
   "Scale in distribution creates a cost advantage over regional suppliers."],
  ["Mortgage rates above 6% have frozen existing home sales, and home improvement spending follows moves.",
   "Large discretionary projects are deferred first when consumer confidence weakens.",
   "Debt taken on for the SRS and GMS acquisitions is more expensive in a higher-rate environment."],
  "Seen as a quality operator waiting for a housing turn. The disagreement is on timing — how long rates stay high and how long homeowners stay put.",
  "Comparable sales, big-ticket transaction growth, Pro segment performance, existing home sales data.",
  (4, 2, 5, 3)),

C("PEP", "PepsiCo, Inc.", "consumer", "Purchase, New York, USA", 1965,
  "Ramon Laguarta", "Nasdaq", 144.22, 1.37, 36.0, 93.0,
  [0.04, 0.04, 0.04, 0.03, 0.03], 0.13, 0.15, 0.074, 0.023,
  "Formed in 1965 by merging Pepsi-Cola with Frito-Lay, headquartered in Purchase, New York. Ramon Laguarta is CEO. Unlike Coca-Cola, PepsiCo is roughly 55% snacks and only 45% beverages, and the snack business — Lay's, Doritos, Cheetos, Ruffles, Tostitos and Quaker Oats — is significantly more profitable and faster growing than the drinks. It owns most of its own bottling, which lowers margins but gives it control of distribution. Gatorade dominates sports drinks and the portfolio has been shifted toward lower-sugar and functional products.",
  [("Frito-Lay & Quaker Foods North America", 33), ("PepsiCo Beverages North America", 28), ("International", 39)],
  ["Snacks are structurally more attractive than carbonated drinks, with better growth and less regulatory attention.",
   "Combined snack and beverage distribution gives real leverage with retailers.",
   "International markets provide a long runway where per-capita consumption is still low."],
  ["North American snack volumes have declined as consumers push back on price increases.",
   "GLP-1 adoption reduces snacking specifically, which hits Frito-Lay more than beverages.",
   "Owning bottling means more capital intensity and lower margins than Coca-Cola's model."],
  "Generally treated as reasonably valued relative to staples peers. The volume weakness in North American snacks is the main point of contention.",
  "Frito-Lay volume trends, international organic growth, productivity savings, pricing elasticity.",
  (5, 2, 4, 4)),

C("MC", "LVMH Moët Hennessy Louis Vuitton", "consumer", "Paris, France", 1987,
  "Bernard Arnault", "Euronext Paris", 535.00, 0.497, 12.0, 92.0,
  [0.05, 0.06, 0.06, 0.05, 0.05], 0.16, 0.19, 0.086, 0.024,
  "Created in 1987 by merging Louis Vuitton, founded 1854, with Moët Hennessy. Bernard Arnault has controlled and led it since 1989, building the world's largest luxury group. It owns roughly 75 maisons: Louis Vuitton and Dior in fashion and leather goods, which generate most of the profit; Tiffany, Bulgari and TAG Heuer in jewellery and watches; Sephora in selective retail; Moët & Chandon, Dom Pérignon and Hennessy in wines and spirits; and Guerlain and Parfums Christian Dior in perfumes and cosmetics. Prices quoted in euros.",
  [("Fashion & Leather Goods", 49), ("Selective Retailing (Sephora, DFS)", 19), ("Perfumes & Cosmetics", 12), ("Watches & Jewelry", 12), ("Wines & Spirits", 8)],
  ["Louis Vuitton and Dior have genuine pricing power — they raise prices annually and demand does not fall.",
   "Vertical integration into leather tanneries and workshops protects both quality and supply.",
   "Brand equity built over a century cannot be replicated by capital alone."],
  ["Chinese luxury demand, historically the growth engine, has been weak and the recovery keeps disappointing.",
   "The stock is well below its 52-week high of €652 and far below its all-time peak near €880.",
   "Luxury is discretionary and cyclical; aspirational buyers disappear first when confidence falls."],
  "A quality-versus-cycle debate. Bulls argue the franchise is intact and the shares are simply out of favour; bears see a Chinese demand reset that is structural rather than cyclical.",
  "Organic growth in Fashion & Leather Goods, Chinese consumer data, Sephora performance, US demand.",
  (5, 2, 5, 4)),

C("NESN", "Nestlé S.A.", "consumer", "Vevey, Switzerland", 1866,
  "Philipp Navratil", "SIX Swiss", 84.55, 2.55, 60.0, 105.0,
  [0.03, 0.03, 0.03, 0.03, 0.03], 0.13, 0.15, 0.072, 0.021,
  "Founded in 1866 by Henri Nestlé, a German pharmacist in Vevey, Switzerland, who developed an infant formula for babies unable to breastfeed. Philipp Navratil became CEO in 2025. Nestlé is the largest food company in the world, with over 2,000 brands: Nescafé and Nespresso in coffee, KitKat, Purina pet food, Gerber baby food, Maggi, San Pellegrino and Perrier waters, and a health science division selling medical nutrition. Pet care and coffee are the two most attractive parts of the portfolio. Prices quoted in Swiss francs.",
  [("Powdered & Liquid Beverages", 28), ("PetCare (Purina)", 21), ("Nutrition & Health Science", 17), ("Prepared Dishes & Confectionery", 20), ("Milk products & Water", 14)],
  ["Purina pet care is a genuinely excellent business — pet ownership is rising and owners do not trade down on pet food.",
   "Nespresso and Nescafé give exposure to coffee, one of the few staples categories with real premiumisation.",
   "Swiss franc reporting and a defensive portfolio make it a low-volatility holding."],
  ["Organic growth has been persistently below its own targets and management credibility has suffered.",
   "Coffee and cocoa input costs surged and passing them through has cost volume.",
   "The portfolio is arguably too broad, with several underperforming categories management has been slow to exit."],
  "A restructuring story rather than a growth story. The debate is whether new management will divest aggressively enough to re-rate the shares.",
  "Organic growth versus guidance, portfolio disposals, input cost pass-through, pet care momentum.",
  (5, 1, 4, 4)),

C("PM", "Philip Morris International", "consumer", "Stamford, Connecticut, USA", 2008,
  "Jacek Olczak", "NYSE", 182.27, 1.56, 45.0, 40.0,
  [0.07, 0.07, 0.06, 0.06, 0.05], 0.30, 0.33, 0.078, 0.024,
  "Spun off from Altria in 2008 to hold the international tobacco business, headquartered in Stamford, Connecticut. Jacek Olczak is CEO. The strategy is an explicit transition away from cigarettes: IQOS heated tobacco, now the leading smoke-free product in dozens of markets, and ZYN nicotine pouches, acquired through Swedish Match in 2022, which have grown extraordinarily fast in the United States. Smoke-free products already generate around 40% of revenue and carry higher margins than combustible cigarettes. It also sells Marlboro outside the US.",
  [("Combustible tobacco", 60), ("Smoke-free (IQOS, ZYN)", 40)],
  ["ZYN volume growth has been exceptional and the category has better economics than cigarettes.",
   "IQOS gives a credible path to converting smokers rather than simply managing decline.",
   "Extremely strong pricing power — tobacco price increases have historically outpaced volume declines every year."],
  ["Regulatory risk is permanent and can arrive suddenly, including outright category bans.",
   "Roughly $45B of net debt from the Swedish Match acquisition needs servicing.",
   "Many institutional investors are excluded from tobacco by mandate, which caps the buyer base."],
  "Regarded as the best-positioned tobacco company because of smoke-free mix. The exclusion of tobacco from many ESG mandates keeps a structural discount in place.",
  "ZYN shipment volumes, IQOS user growth, US regulatory decisions on nicotine pouches, pricing.",
  (5, 3, 4, 3)),

C("OR", "L'Oréal S.A.", "consumer", "Clichy, France", 1909,
  "Nicolas Hieronimus", "Euronext Paris", 360.00, 0.535, 3.0, 47.0,
  [0.05, 0.05, 0.05, 0.04, 0.04], 0.15, 0.17, 0.082, 0.024,
  "Founded in 1909 by chemist Eugène Schueller, who invented a safe synthetic hair dye. Nicolas Hieronimus is CEO; the Bettencourt Meyers family and Nestlé remain large shareholders. L'Oréal is the largest beauty company in the world across four divisions: Luxe with Lancôme, Yves Saint Laurent Beauté and Armani; Consumer Products with Maybelline, Garnier and L'Oréal Paris; Dermatological Beauty with La Roche-Posay, CeraVe and Vichy, the fastest-growing division; and Professional Products for salons. Prices quoted in euros.",
  [("Consumer Products", 37), ("L'Oréal Luxe", 34), ("Dermatological Beauty", 17), ("Professional Products", 12)],
  ["Dermatological beauty, particularly CeraVe and La Roche-Posay, is growing fast and is recommended by dermatologists, which is powerful marketing.",
   "Beauty has proven remarkably resilient in downturns — the so-called lipstick effect is real.",
   "Research and development spending is far higher than peers, producing genuine formulation advantages."],
  ["Chinese demand for premium beauty has been weak and China was the main growth engine.",
   "Competition from social-media-native brands is intense in colour cosmetics.",
   "The valuation has historically been high and leaves little room for growth disappointment."],
  "Viewed as the highest-quality beauty asset globally. The China recovery timing is the central uncertainty.",
  "Like-for-like growth by division, China travel retail, CeraVe and dermatological momentum.",
  (5, 3, 5, 5)),
]
