from .schema import C

ENERGY = [
C("XOM", "Exxon Mobil Corporation", "energy", "Spring, Texas, USA", 1870,
  "Darren Woods", "NYSE", 137.09, 4.18, 38.0, 355.0,
  [0.06, -0.02, 0.01, 0.02, 0.02], 0.09, 0.095, 0.088, 0.020,
  "Descends from John D. Rockefeller's Standard Oil, founded in 1870 and broken up in 1911; Exxon and Mobil, two of the successor companies, remerged in 1999. Darren Woods is CEO, headquartered in Spring, Texas. Exxon explores for and produces oil and gas, refines it into fuels and lubricants, and manufactures petrochemicals. Its highest-return assets are the Guyana offshore fields, among the best oil discoveries of the century, and the Permian Basin, expanded by the 2024 Pioneer Natural Resources acquisition. It is also investing in carbon capture and lithium.",
  [("Upstream (oil & gas production)", 62), ("Product Solutions (refining, chemicals)", 35), ("Low Carbon & Other", 3)],
  ["Guyana produces oil at among the lowest break-even costs in the industry, which protects cash flow if prices fall.",
   "Brent above $88 and Middle East supply disruption in 2026 have transformed near-term cash generation.",
   "Balance sheet strength allows counter-cyclical acquisition when weaker producers are distressed."],
  ["Commodity price exposure is the entire story — an Iran ceasefire could take $15 off Brent very quickly.",
   "Long-term oil demand faces structural decline as electric vehicle adoption compounds.",
   "Refining margins are volatile and capital-intensive with poor long-run returns."],
  "Held both as an energy investment and as a geopolitical hedge; the shares were up about 40% in 2026 by early September, slightly behind Chevron and the energy sector ETF. The core disagreement is on the timing of peak oil demand and how long crude holds near current levels rather than on Exxon's execution.",
  "Brent price and Middle East developments, Guyana production ramp, Permian volumes, buyback pace, outcome of Shell's US chemicals sale process.",
  (4, 2, 4, 5)),

C("CVX", "Chevron Corporation", "energy", "Houston, Texas, USA", 1879,
  "Mike Wirth", "NYSE", 169.20, 1.99, 25.0, 200.0,
  [0.05, -0.02, 0.01, 0.02, 0.02], 0.095, 0.10, 0.090, 0.020,
  "Another Standard Oil descendant, founded in 1879 as the Pacific Coast Oil Company. Mike Wirth is CEO; headquarters moved from California to Houston in 2024. Chevron's core assets are the Permian Basin, the Tengiz field in Kazakhstan following a large expansion project, deepwater Gulf of Mexico, and Australian liquefied natural gas at Gorgon and Wheatstone. The 2025 acquisition of Hess added a stake in the same Guyana development that Exxon operates. It runs a smaller refining footprint than Exxon and has historically prioritised the dividend above almost everything else.",
  [("Upstream", 78), ("Downstream (refining & chemicals)", 22)],
  ["The Hess acquisition secured a share of the highest-quality oil development of the last decade.",
   "Tengiz expansion adds significant low-cost production volume with the capital already spent.",
   "A long dividend growth record and lower leverage than most integrated peers."],
  ["Kazakhstan exposure carries political and export-route risk, particularly with regional conflict elevated.",
   "Higher beta to oil prices than Exxon because of the smaller downstream buffer.",
   "Venezuela has become a growth commitment of more than $7 billion over five years to roughly double output there, which raises exposure to the country's political and legal risk."],
  "Broadly seen as a quality integrated with strong capital return, and the September 2026 Venezuela expansion adds a long-dated growth option. Debate is on oil price assumptions rather than company-specific execution.",
  "Oil price, Tengiz ramp, Guyana share of production, Venezuela joint-venture expansion, dividend and buyback announcements.",
  (4, 2, 4, 5)),

C("SHEL", "Shell plc", "energy", "London, United Kingdom", 1907,
  "Wael Sawan", "NYSE (ADR) / LSE", 89.27, 2.90, 40.0, 290.0,
  [0.05, -0.03, 0.01, 0.02, 0.02], 0.072, 0.078, 0.092, 0.018,
  "Formed in 1907 by the merger of Royal Dutch Petroleum and the Shell Transport and Trading Company. Wael Sawan became CEO in 2023 and moved the sole headquarters to London. Shell is the largest liquefied natural gas trader in the world, which is its genuine differentiator — it buys, ships and sells LNG globally and earns trading margin on the volatility. It also has upstream oil production, a large refining and chemicals arm, and one of the biggest branded fuel retail networks. Sawan has scaled back renewable investment to prioritise cash returns.",
  [("Integrated Gas & LNG", 34), ("Upstream", 26), ("Marketing & Retail", 22), ("Chemicals & Products", 18)],
  ["The LNG trading business earns money from volatility itself, which is a rare and genuinely differentiated capability.",
   "European gas security concerns have structurally raised the value of flexible LNG supply.",
   "Trades at a persistent discount to US integrated majors despite comparable cash generation."],
  ["European energy policy and windfall taxes create political risk US peers do not face.",
   "The retreat from renewables has attracted criticism from European institutional investors.",
   "The valuation discount to Exxon and Chevron has persisted for years and shows no sign of closing."],
  "Held primarily for LNG exposure and capital return. The recurring question is whether the discount to US peers ever narrows.",
  "LNG trading results, European gas prices, buyback pace, portfolio disposals including the possible US chemicals sale.",
  (4, 2, 4, 4)),

C("TTE", "TotalEnergies SE", "energy", "Courbevoie, France", 1924,
  "Patrick Pouyanné", "NYSE (ADR) / Euronext", 68.00, 2.25, 26.0, 205.0,
  [0.04, -0.02, 0.02, 0.02, 0.02], 0.070, 0.078, 0.092, 0.020,
  "Founded in 1924 as Compagnie française des pétroles at the direction of the French government. Patrick Pouyanné has been CEO since 2014. TotalEnergies is the European major that committed most seriously to an integrated power strategy — it owns and operates a large renewable generation and electricity retail business alongside conventional oil and gas. Its LNG portfolio is second only to Shell's, and its upstream assets are spread across Africa, the Middle East, the North Sea and Brazil. It has significant exposure to Mozambique LNG, a project delayed for years by regional security problems.",
  [("Exploration & Production", 43), ("Integrated LNG", 24), ("Downstream & Chemicals", 22), ("Integrated Power", 11)],
  ["Integrated Power gives a credible energy transition strategy that most peers abandoned, and management now targets positive free cash flow in 2027 and a 12% return on capital by 2030.",
   "One of the highest dividend yields among the majors, and in September 2026 the board committed to growing the dividend by more than 5% a year through 2030.",
   "LNG position is strategically valuable in a Europe permanently reducing Russian gas dependence."],
  ["Mozambique LNG remains delayed and the capital deployed is not yet generating returns.",
   "African upstream assets carry political and security risk.",
   "European majors trade at persistent discounts and French tax policy is unpredictable."],
  "Favoured among European majors for the power strategy and yield. The September 2026 strategy update raised the fourth-quarter buyback to $2.5 billion from $1.5 billion and targeted 4% annual energy production growth to 2030, but the shares slipped and the debate remains whether renewables investment dilutes returns.",
  "Mozambique LNG construction progress, Integrated Power reaching positive free cash flow in 2027, quarterly buyback size, dividend policy, oil price.",
  (4, 2, 4, 4)),

C("COP", "ConocoPhillips", "energy", "Houston, Texas, USA", 1917,
  "Andy O'Brien", "NYSE", 118.00, 1.24, 17.0, 62.0,
  [0.07, -0.03, 0.01, 0.02, 0.02], 0.125, 0.135, 0.095, 0.018,
  "The modern company dates to the 2002 merger of Conoco and Phillips Petroleum, with roots back to 1917. Andy O'Brien, previously chief financial officer, became CEO on 1 September 2026, succeeding Ryan Lance, who became executive chair. In 2012 it spun off its refining business as Phillips 66, making ConocoPhillips the largest pure exploration and production company in the world — it finds and produces oil and gas but does not refine it. Core assets are the Permian, Eagle Ford and Bakken shale basins, Alaska including the Willow project, and liquefied natural gas positions in Qatar and at Port Arthur. It acquired Marathon Oil in 2024.",
  [("Lower 48 (shale)", 55), ("Alaska & International", 27), ("Canada & LNG", 18)],
  ["Pure upstream exposure gives more direct leverage to oil prices than the integrated majors.",
   "A deep inventory of low-cost shale drilling locations extends well beyond a decade.",
   "LNG export positions diversify away from pure crude price exposure."],
  ["No refining means no downstream cushion when crude prices fall — the earnings swing is much wider.",
   "Shale decline rates are steep and require continuous reinvestment simply to hold production flat.",
   "Alaska projects face persistent environmental and permitting litigation."],
  "Seen as the highest-quality large independent producer. Second-quarter 2026 earnings beat expectations on higher prices even as production fell about 6% year on year, and the bull and bear cases remain essentially a view on the oil price.",
  "Production trend under new CEO Andy O'Brien, cost per barrel, oil price, LNG contract signings, progress towards the targeted $7 billion free cash flow inflection by 2029.",
  (4, 2, 4, 5)),

C("LIN", "Linde plc", "energy", "Woking, United Kingdom", 1879,
  "Sanjiv Lamba", "Nasdaq", 546.64, 0.463, 19.0, 34.0,
  [0.06, 0.06, 0.05, 0.05, 0.05], 0.22, 0.25, 0.078, 0.024,
  "Founded in 1879 by Carl von Linde, who invented industrial refrigeration; merged with Praxair in 2018 to create the largest industrial gas company in the world. Sanjiv Lamba is CEO. Linde produces and distributes oxygen, nitrogen, argon, hydrogen and carbon dioxide to steelmakers, chemical plants, electronics fabs, hospitals and food processors. The business model is unusually attractive: gases are supplied under fifteen-year take-or-pay contracts from plants built on the customer's site, so revenue is contracted and switching is effectively impossible.",
  [("Americas", 37), ("EMEA", 27), ("APAC", 26), ("Engineering & Other", 10)],
  ["On-site plants under long take-or-pay contracts produce utility-like revenue with industrial margins.",
   "Semiconductor fabs consume enormous volumes of ultra-pure gases, so Linde benefits directly from the chip build-out.",
   "Clean hydrogen projects offer long-dated growth optionality with contracted offtake."],
  ["Industrial production volumes are cyclical and Europe has been in a manufacturing recession.",
   "Energy costs are a large input, and the 2026 oil and gas spike compresses margins until contracts reprice.",
   "The valuation is high for an industrial and rarely offers an attractive entry point."],
  "Regarded as one of the best industrial business models in existence. The objection is that the market already knows it.",
  "Volume growth by region, project backlog, pricing versus energy costs, hydrogen contract wins.",
  (5, 3, 5, 5)),

C("BHP", "BHP Group Limited", "energy", "Melbourne, Australia", 1885,
  "Brandon Craig", "NYSE (ADR) / ASX", 78.00, 2.53, 12.0, 55.0,
  [0.04, 0.02, 0.03, 0.03, 0.03], 0.185, 0.195, 0.095, 0.020,
  "Founded in 1885 as the Broken Hill Proprietary Company at a silver and lead mine in New South Wales. Brandon Craig, previously head of the Americas business, became CEO on 1 July 2026, succeeding Mike Henry; the company is headquartered in Melbourne. BHP is the largest mining company in the world by market value. Western Australian iron ore, among the lowest-cost operations globally, supplies Chinese steel mills, but copper, produced at Escondida in Chile and Olympic Dam in Australia, overtook it in fiscal 2026 to provide 54% of group EBITDA. It also produces metallurgical coal for steelmaking and is developing the Jansen potash project in Canada, with first production expected in mid-2027. Copper is the strategic growth priority.",
  [("Iron Ore", 52), ("Copper", 34), ("Coal & Other", 14)],
  ["Copper demand is structurally supported by electrification, grid investment and data centre construction.",
   "Western Australian iron ore has among the lowest costs per tonne in the industry, so it stays profitable at low prices.",
   "Jansen potash, 84% complete with first production expected in mid-2027, adds a genuinely new commodity exposure with long-life reserves."],
  ["Iron ore earnings depend almost entirely on Chinese construction, which has been structurally weak.",
   "Mining is capital intensive with long lead times and frequent cost overruns.",
   "Commodity price volatility makes earnings and dividends unpredictable."],
  "Now held mainly as a copper and electrification play, with copper providing more than half of EBITDA in fiscal 2026 and an iron ore cash engine attached. After a strong run most analysts rate the shares a hold, and the China property downturn remains the central concern.",
  "Copper output and the new Escondida concentrator, iron ore price and Chinese steel output, Jansen first production in mid-2027, quarterly operational review in October.",
  (4, 2, 4, 4)),

C("NEE", "NextEra Energy, Inc.", "energy", "Juno Beach, Florida, USA", 1925,
  "John Ketchum", "NYSE", 78.00, 2.06, 82.0, 26.0,
  [0.07, 0.07, 0.06, 0.06, 0.05], 0.26, 0.29, 0.072, 0.024,
  "Founded in 1925 as Florida Power & Light. John Ketchum is CEO, headquartered in Juno Beach, Florida. NextEra is two businesses in one: FPL, a regulated utility serving about 12 million Floridians with predictable, rate-regulated returns; and NextEra Energy Resources, the largest generator of wind and solar power in the world, which sells electricity under long-term contracts. Data centre power demand has transformed the outlook for the competitive business, and NextEra has restarted work on nuclear capacity to serve it. In May 2026 it agreed to acquire Dominion Energy in an all-stock deal valued at about $66.8 billion; shareholders of both companies approved it in September 2026 and it is expected to close in the second half of 2027, subject to regulatory approval.",
  [("Florida Power & Light (regulated)", 62), ("NextEra Energy Resources", 35), ("Other", 3)],
  ["AI data centres need enormous quantities of firm, clean power and are willing to sign twenty-year contracts to get it.",
   "The regulated Florida utility provides stable, growing earnings in a state with strong population growth.",
   "The largest renewable development pipeline in the country, with land and interconnection queue positions already secured."],
  ["Utilities are heavily leveraged and rising interest rates directly raise the cost of that capital.",
   "US federal policy support for renewables has become less certain.",
   "Florida is exposed to hurricane damage and the associated restoration costs."],
  "Viewed as the primary listed way to own data centre power demand. The pending all-stock acquisition of Dominion Energy, which management says will lift adjusted earnings growth to about 9% a year through 2032, now faces a lengthy regulatory review including in Virginia, and rate sensitivity remains the main headwind.",
  "Dominion merger regulatory approvals, renewables backlog additions, data centre power agreements, Florida rate case outcomes, interest costs.",
  (4, 3, 4, 3)),

C("RIO", "Rio Tinto Group", "energy", "London, United Kingdom", 1873,
  "Simon Trott", "NYSE (ADR) / LSE", 72.00, 1.62, 8.0, 54.0,
  [0.04, 0.03, 0.03, 0.03, 0.03], 0.165, 0.175, 0.095, 0.020,
  "Founded in 1873 when investors bought ancient copper mines along Spain's Rio Tinto river. Dual-listed in London and Sydney; Simon Trott became CEO in 2025. Rio Tinto is the world's second-largest mining company. Its Pilbara iron ore operations in Western Australia are the profit engine. It also produces aluminium, where it is one of the largest Western producers, copper at Kennecott, Escondida and the enormous Oyu Tolgoi underground mine in Mongolia, and lithium following the Arcadium acquisition. Oyu Tolgoi is the key growth asset.",
  [("Iron Ore", 55), ("Aluminium", 22), ("Copper", 18), ("Minerals & Lithium", 5)],
  ["Oyu Tolgoi ramps toward becoming one of the largest copper mines in the world through the 2030s.",
   "Aluminium exposure benefits from electrification and Western supply constraints.",
   "The Arcadium acquisition gave real lithium scale at a cyclical low in lithium prices."],
  ["Same Chinese iron ore dependence as BHP, and in August and September 2026 China's state buyer CMRG told some steel mills to pause purchases of Rio's Pilbara Blend to strengthen its negotiating position.",
   "Mongolian political risk affects the single most important growth project.",
   "Simandou in Guinea will add substantial new iron ore supply to an already well-supplied market."],
  "A copper growth story wrapped around an iron ore cash engine. Debate centres on iron ore price assumptions, Simandou's impact on global supply and how much pricing power China's centralised state buyer now holds over Pilbara sales.",
  "Oyu Tolgoi production ramp, iron ore price and CMRG contract talks, Simandou start-up timing, lithium prices.",
  (4, 2, 4, 4)),
]

INDUSTRIALS = [
C("GE", "GE Aerospace", "industrials", "Evendale, Ohio, USA", 1892,
  "H. Lawrence Culp Jr.", "NYSE", 377.52, 1.06, 12.0, 42.0,
  [0.12, 0.11, 0.10, 0.09, 0.08], 0.20, 0.25, 0.086, 0.026,
  "General Electric was founded in 1892 through the merger of Thomas Edison's electric company with Thomson-Houston. After breaking into three companies, GE Aerospace is the surviving core, led by Larry Culp. It designs and manufactures jet engines: the LEAP engine, produced through the CFM joint venture with Safran, powers most narrowbody aircraft delivered today, and the GE9X powers the Boeing 777X. The economics of the business are in aftermarket services — engines are sold near cost and profit is earned over decades on spare parts and maintenance contracts.",
  [("Commercial Engines & Services", 76), ("Defense & Propulsion Technologies", 24)],
  ["The installed base of roughly 45,000 commercial engines generates decades of high-margin aftermarket revenue.",
   "Airlines are flying older aircraft longer because of delivery delays, which increases shop visits and spare parts demand.",
   "LEAP holds a dominant position on the narrowbody platforms that will be built through the 2030s."],
  ["Supply chain constraints have limited engine deliveries; the $11.75 billion CPP castings acquisition announced in September 2026 targets that bottleneck but is not expected to close until the second half of 2027.",
   "Aviation demand is cyclical and directly exposed to fuel costs, which surged in 2026.",
   "The stock has already re-rated substantially since the break-up and expectations are high."],
  "One of the better-regarded industrial stories of the cycle, built on aftermarket economics. The CPP deal, priced at about 18 times projected 2027 EBITDA including synergies, adds integration and valuation questions to the existing pushback on the share price after a strong run.",
  "Engine shop visit volumes, spare parts pricing, LEAP delivery rate, defence orders, regulatory approval of the CPP acquisition.",
  (5, 4, 5, 4)),

C("CAT", "Caterpillar Inc.", "industrials", "Irving, Texas, USA", 1925,
  "Joe Creed", "NYSE", 963.53, 0.470, 36.0, 66.0,
  [0.08, 0.06, 0.05, 0.05, 0.04], 0.16, 0.18, 0.090, 0.024,
  "Formed in 1925 from the merger of Holt Manufacturing and C. L. Best Tractor, both pioneers of track-type tractors. Joe Creed became CEO in 2025, headquartered in Irving, Texas. Caterpillar makes construction and mining equipment, diesel and natural gas engines, and — increasingly important — the large reciprocating engines and turbines from its Solar Turbines unit that provide backup and prime power for data centres. Cat Financial provides equipment financing. The dealer network, largely independent and family-owned, is a major competitive advantage.",
  [("Construction Industries", 40), ("Energy & Transportation", 34), ("Resource Industries", 20), ("Financial Products", 6)],
  ["Data centre power generation demand has become a genuine new growth driver for the Energy & Transportation segment.",
   "The independent dealer network provides service coverage competitors cannot replicate.",
   "Aftermarket parts and service revenue smooths the equipment sales cycle."],
  ["Construction equipment demand is cyclical and directly tied to interest rates and non-residential building.",
   "Mining capital spending depends on commodity prices that have been volatile.",
   "The shares ran from $391 to about $1,063 and then fell roughly 21% from that high by mid-August 2026 despite record results, showing how quickly sentiment can turn."],
  "The debate is whether data centre power demand justifies a structurally higher multiple for what has always been a cyclical machinery business. Second-quarter 2026 adjusted EPS beat expectations by a wide margin and guidance was raised, yet the shares pulled back from their high; the average analyst rating is a moderate buy.",
  "Dealer inventory levels, backlog, power generation orders, construction end-market data.",
  (4, 3, 4, 4)),

C("RTX", "RTX Corporation", "industrials", "Arlington, Virginia, USA", 1922,
  "Christopher Calio", "NYSE", 199.25, 1.33, 36.0, 84.0,
  [0.08, 0.08, 0.07, 0.06, 0.06], 0.11, 0.14, 0.082, 0.024,
  "Formed in 2020 by merging Raytheon with United Technologies, with roots to 1922. Christopher Calio is CEO. Three businesses: Collins Aerospace, which makes aircraft interiors, avionics and landing systems; Pratt & Whitney, which builds the GTF engines for the Airbus A320neo and the F135 for the F-35 fighter; and Raytheon, which produces Patriot and NASAMS air defence systems, Tomahawk and AMRAAM missiles. Air defence demand has risen sharply given conflicts in Europe and the Middle East, and the backlog is at record levels.",
  [("Collins Aerospace", 33), ("Pratt & Whitney", 33), ("Raytheon (defense)", 34)],
  ["Air and missile defence demand is at generational highs, and the backlog extends years out.",
   "Commercial aerospace aftermarket is recovering strongly as flight hours rise.",
   "The defence backlog provides revenue visibility few industrials can match, reinforced by multi-year Raytheon awards worth up to $20.7 billion for AMRAAM and $24.4 billion for SM-6 in September and October 2026."],
  ["The Pratt & Whitney GTF powder metal contamination issue has cost billions and grounded aircraft.",
   "Government contracts often carry fixed-price terms, so cost inflation is absorbed by RTX not the customer.",
   "Defence budgets are politically determined and can be cut with little warning."],
  "Held as the primary missile defence beneficiary, and the AMRAAM and SM-6 multi-year awards add to an already record backlog. Even so, the shares fell about 10% in the month to mid-September 2026 on valuation concerns, and GTF remediation remains the recurring uncertainty.",
  "Defence bookings and multi-year missile production ramps, GTF inspection completion, commercial aftermarket growth, backlog conversion.",
  (5, 3, 4, 3)),

C("GEV", "GE Vernova Inc.", "industrials", "Cambridge, Massachusetts, USA", 2024,
  "Scott Strazik", "NYSE", 1113.11, 0.271, -8.0, 40.0,
  [0.14, 0.13, 0.11, 0.10, 0.09], 0.11, 0.19, 0.095, 0.028,
  "Spun out of General Electric in April 2024 to hold the energy businesses. Scott Strazik is CEO. GE Vernova makes gas turbines, in which it is one of only three credible global suppliers alongside Siemens Energy and Mitsubishi; grid equipment including high-voltage transformers and switchgear, which is in severe global shortage; and wind turbines, the weakest part of the portfolio. Data centre electricity demand has produced a gas turbine order backlog stretching years into the future, and the electrification segment has become the profit story.",
  [("Power (gas turbines)", 45), ("Electrification (grid)", 33), ("Wind", 22)],
  ["Gas turbine slots are sold out for years — this is one of the genuine physical bottlenecks in the AI build-out.",
   "Grid equipment shortages give pricing power that transformer makers have not had in decades.",
   "Electrification margins have expanded far faster than expected since the spin-off."],
  ["The wind business has been consistently loss-making with warranty and quality problems.",
   "The stock rose from $530 to $1,175 in twelve months and, even after falling about 22% from its high by September 2026, still prices in sustained execution.",
   "Large equipment orders carry long lead times and fixed-price risk if input costs rise."],
  "One of the strongest performers of the electrification theme, though the shares were about 22% below their 52-week high in early September 2026. The debate is whether the order backlog converts at the margins management is guiding to.",
  "Gas turbine orders and pricing, electrification margin, wind segment losses, backlog conversion, Venezuela grid programme, BWRX-300 small reactor orders.",
  (4, 5, 4, 5)),

C("BA", "The Boeing Company", "industrials", "Arlington, Virginia, USA", 1916,
  "Kelly Ortberg", "NYSE", 235.00, 0.79, 45.0, 82.0,
  [0.15, 0.14, 0.12, 0.10, 0.08], 0.03, 0.11, 0.105, 0.026,
  "Founded in 1916 by William Boeing in Seattle. Kelly Ortberg became CEO in 2024, brought in to fix a company damaged by the 737 MAX crashes, a door plug failure in 2024, quality escapes and a costly strike. Boeing builds commercial aircraft — the 737 MAX, 787 Dreamliner and the delayed 777X — plus defence systems including the KC-46 tanker, F-15EX and satellites, and Global Services for maintenance and parts. It operates in a duopoly with Airbus, and the order backlog exceeds 5,500 aircraft.",
  [("Commercial Airplanes", 50), ("Defense, Space & Security", 32), ("Global Services", 18)],
  ["A backlog of over 5,500 aircraft represents years of contracted demand that cannot go elsewhere — Airbus has no spare capacity.",
   "Free cash flow inflects sharply as production rates recover toward pre-crisis levels.",
   "Global Services is a stable, high-margin business insulated from production problems."],
  ["Certification remains the bottleneck: the FAA halted MAX 10 certification in September 2026 over a cockpit software flaw, and the 777-9 timeline is slipping into 2027.",
   "Fixed-price defence contracts have generated repeated multi-billion-dollar charges.",
   "Around $45B of net debt built up through years of cash burn constrains flexibility."],
  "A recovery story where the timing has repeatedly disappointed. The shares fell almost 7% on 28 September 2026 when the FAA halted MAX 10 certification over a software flaw, though the F/A-XX fighter award and a ratified engineers' contract removed two sources of uncertainty. Bulls point to the backlog and duopoly; bears note that Boeing has missed nearly every target it has set since 2019.",
  "Monthly 737 and 787 delivery rates, MAX 10 software fix and certification, 777X certification, any Northrop protest of the F/A-XX award, defence charges, free cash flow.",
  (4, 4, 2, 2)),

C("HON", "Honeywell International", "industrials", "Charlotte, North Carolina, USA", 1906,
  "Vimal Kapur", "Nasdaq", 218.00, 0.635, 22.0, 40.0,
  [0.06, 0.06, 0.05, 0.05, 0.04], 0.16, 0.18, 0.084, 0.024,
  "Traces to a 1906 thermostat business and the 1999 merger of AlliedSignal and Honeywell. Vimal Kapur is chairman and CEO. After spinning off Solstice Advanced Materials and then Honeywell Aerospace, which began trading separately on Nasdaq in June 2026, the remaining company operates as Honeywell Technologies, a pure-play automation business. Building Automation supplies control and safety systems for hospitals, airports, data centres and commercial buildings. Process Automation and Technology serves LNG plants, refineries, life sciences and utilities, and added Johnson Matthey's Catalyst Technologies business in 2026. Industrial Automation is the third segment. It retains a large stake in Quantinuum, the quantum computing company that listed in June 2026.",
  [("Industrial Automation", 42), ("Building Automation", 33), ("Energy & Sustainability Solutions", 25)],
  ["Management describes it as the only large pure-play automation company in public markets, so it can now be valued against automation peers rather than as a conglomerate.",
   "Around a quarter of revenue sits in high-growth markets such as data centres, semiconductor fabs and life sciences that management says are growing roughly 10% a year.",
   "The retained Quantinuum stake gives exposure to a leading quantum computing company that carries almost no weight in the valuation."],
  ["Two spin-offs in under two years leave stranded costs and execution risk for the smaller remaining company.",
   "Industrial automation demand is tied to capital spending cycles that have been soft.",
   "Guidance for 3–4% organic sales growth in 2026 is modest for a company now marketed as a growth-focused automation pure-play."],
  "No longer a sum-of-the-parts story: with Aerospace spun off in June 2026, it is judged as a pure-play automation company. The first post-split results beat estimates and guidance was raised, but the debate is whether automation growth can justify a premium multiple.",
  "Automation orders, data-centre and semiconductor fab demand, Process Automation recovery, Catalyst Technologies integration, Quantinuum stake value.",
  (4, 2, 4, 4)),

C("LMT", "Lockheed Martin Corporation", "industrials", "Bethesda, Maryland, USA", 1912,
  "James Taiclet", "NYSE", 490.00, 0.232, 18.0, 74.0,
  [0.05, 0.05, 0.05, 0.04, 0.04], 0.09, 0.10, 0.080, 0.022,
  "Formed in 1995 from the merger of Lockheed and Martin Marietta, with roots to 1912. James Taiclet is CEO, headquartered in Bethesda, Maryland. Lockheed is the largest defence contractor in the world. The F-35 Lightning II fighter programme is the single largest weapons programme in history and accounts for roughly a quarter of revenue. It also builds the Black Hawk helicopter through Sikorsky, missile defence systems including THAAD and PAC-3, HIMARS rocket artillery, hypersonic weapons and classified space systems.",
  [("Aeronautics (F-35)", 40), ("Missiles & Fire Control", 22), ("Rotary & Mission Systems", 24), ("Space", 14)],
  ["Missile and munitions demand has risen sharply, and a seven-year PAC-3 MSE production contract awarded around the start of August 2026 locks in Patriot interceptor work through 2035.",
   "The F-35 programme runs for decades with sustainment revenue that exceeds the original production value.",
   "Backlog provides multi-year revenue visibility with a customer that does not default."],
  ["F-35 deliveries have been delayed by software and engine upgrade problems.",
   "Fixed-price development contracts have produced repeated losses across the industry.",
   "US defence budget allocation is shifting toward autonomous and space systems, where Lockheed is less dominant."],
  "Held for backlog visibility and geopolitical exposure, reinforced by the multiyear PAC-3 award in August 2026. The concern is programme execution and margin pressure on fixed-price work.",
  "F-35 delivery and sustainment rates, PAC-3 production ramp, munitions production expansion, budget appropriations.",
  (5, 2, 4, 4)),

C("DE", "Deere & Company", "industrials", "Moline, Illinois, USA", 1837,
  "John May", "NYSE", 520.00, 0.269, 55.0, 48.0,
  [0.05, 0.06, 0.05, 0.05, 0.04], 0.13, 0.15, 0.088, 0.024,
  "Founded in 1837 by John Deere, a blacksmith who designed a steel plough that could cut through Midwest prairie soil. John May is CEO, headquartered in Moline, Illinois. Deere makes agricultural equipment — tractors, combines, sprayers — plus construction and forestry machinery through its Wirtgen and Hitachi partnerships. Its precision agriculture technology, including See & Spray and autonomous tractors, is sold as a technology subscription layered on top of the hardware, which is changing the revenue mix toward recurring software.",
  [("Production & Precision Agriculture", 42), ("Small Agriculture & Turf", 22), ("Construction & Forestry", 26), ("Financial Services", 10)],
  ["Precision agriculture subscriptions add recurring, high-margin revenue to a cyclical equipment business.",
   "Dealer network and brand loyalty among farmers are extraordinarily durable.",
   "Global food demand grows steadily while arable land does not, which supports long-term equipment intensity."],
  ["Farm incomes have fallen with lower crop prices, and equipment purchases follow farm income closely.",
   "High interest rates make equipment financing expensive for buyers.",
   "Used equipment inventories have built up, which delays new purchases."],
  "A cyclical trough story with a technology overlay. After a fiscal third-quarter beat in August 2026, management raised its net income outlook to $4.75–5.0 billion and called fiscal 2026 the bottom of the agricultural equipment cycle, while construction and small agriculture are offsetting a roughly 10% fall in large agriculture sales. The debate is how quickly large agriculture recovers and how much tariffs, expected to cost about $1 billion a year, eat into the rebound.",
  "Fiscal 2027 outlook with fourth-quarter results, large agriculture equipment orders, tariff costs, used inventory levels, precision ag adoption.",
  (5, 2, 4, 3)),

C("SIE", "Siemens AG", "industrials", "Munich, Germany", 1847,
  "Roland Busch", "Frankfurt / XETRA", 235.00, 0.79, 30.0, 88.0,
  [0.06, 0.06, 0.05, 0.05, 0.04], 0.11, 0.14, 0.084, 0.024,
  "Founded in 1847 by Werner von Siemens in Berlin to build telegraph systems. Roland Busch is CEO, headquartered in Munich. Siemens is Europe's largest industrial technology company. Digital Industries sells factory automation hardware and industrial software including the Siemens NX and Simcenter design tools acquired through Mentor Graphics and Altair. Smart Infrastructure supplies electrical distribution and building systems, a direct beneficiary of data centre construction. Mobility builds trains and rail signalling. It also holds a large stake in Siemens Healthineers, which it plans to spin off to shareholders, with votes planned for February 2027. Prices quoted in euros.",
  [("Digital Industries", 30), ("Smart Infrastructure", 30), ("Mobility", 20), ("Healthineers stake & Other", 20)],
  ["Smart Infrastructure benefits directly from data centre electrical demand: orders rose 42% to a record €8 billion in the third fiscal quarter of 2026, with data-centre orders near €6 billion over nine months.",
   "Industrial software is a genuinely high-margin business growing faster than the hardware around it.",
   "European industrial policy and defence-adjacent infrastructure spending support the order book."],
  ["Automation demand depends on Chinese and German manufacturing activity; China automation orders recovered 17% in the third fiscal quarter of 2026, but the recovery is not yet proven durable.",
   "The conglomerate structure attracts a valuation discount despite repeated portfolio simplification.",
   "Currency translation adds volatility for non-euro investors."],
  "A European industrial with a genuine electrification tailwind, trading near record highs after record third-quarter orders and an EPS outlook raised to €11.20–11.50 in August 2026. The conglomerate discount remains the recurring objection, which the planned Healthineers spin-off is meant to narrow.",
  "Fiscal 2026 results and 2027 guidance, Smart Infrastructure data-centre orders, Digital Industries China demand, Healthineers spin-off vote in February 2027, share buyback execution.",
  (4, 3, 4, 4)),
]
