"""Expansion coverage — the next 50 largest US-listed companies.

All US-listed on purpose: the free Finnhub tier covers US securities, so every
price here updates automatically. Foreign primaries would need ADR lines or a
paid feed.

Prices below are starting values only. The first scheduled run overwrites every
one of them with a live quote, so they exist purely so the site builds before
the first fetch. Revenue, share count and net debt do NOT auto-update — those
are modelling inputs and should be revisited when a company reports.
"""

from companies.schema import C

EXPANSION = [

    # ===================== SEMICONDUCTORS =====================
    C("ADI", "Analog Devices, Inc.", "semis", "Wilmington, Massachusetts, USA", 1965,
      "Vincent Roche", "Nasdaq", 245.00, 0.485, 5.0, 10.4,
      [0.14, 0.12, 0.10, 0.08, 0.07], 0.33, 0.36, 0.090, 0.028,
      "Founded in 1965 by Ray Stata and Matthew Lorber. Vincent Roche has run it since 2013. Analog Devices makes the chips that connect the physical world to the digital one — amplifiers, converters and power management parts that turn temperature, pressure, sound and motion into data a processor can use. The 2017 Linear Technology and 2021 Maxim Integrated acquisitions built one of the two dominant analog franchises. Analog parts sell for a few dollars but stay in a product for a decade or more, which makes the revenue unusually durable compared with digital chips.",
      [("Industrial", 44), ("Automotive", 30), ("Communications", 13), ("Consumer", 13)],
      ["Analog designs stay in production for 10+ years, so revenue is far stickier than in digital semiconductors.",
       "Content per car rises with every electrification and driver-assistance feature.",
       "Roughly 65% gross margins with modest capital intensity, since analog does not need leading-edge fabs."],
      ["Industrial and automotive end markets are cyclical; after industrial revenue rose 53% year on year in the July 2026 quarter, the risk is now a cyclical peak rather than a slow recovery.",
   "Texas Instruments is adding significant capacity, which threatens the pricing discipline that has held in analog.",
   "Growth is structurally slower than the digital and AI side of semiconductors."],
      "No longer viewed as a compounder in a slow patch: fiscal third-quarter 2026 revenue rose 40% to $4.02 billion, led by industrial and communications, and fourth-quarter guidance of $4.3 billion topped estimates. The debate has shifted to how long the upturn lasts and whether the higher multiple is justified.",
      "Fiscal Q4 results, industrial order momentum, communications and data-centre demand, automotive content wins, gross margin trajectory.",
      (5, 3, 4, 5)),

    C("MRVL", "Marvell Technology, Inc.", "semis", "Santa Clara, California, USA", 1995,
      "Matt Murphy", "Nasdaq", 92.00, 0.87, 3.5, 6.2,
      [0.32, 0.26, 0.20, 0.15, 0.12], 0.24, 0.30, 0.110, 0.030,
      "Founded in 1995 by Sehat Sutardja, Weili Dai and Pantas Sutardja. Matt Murphy became CEO in 2016 and refocused the company entirely on data infrastructure. Marvell designs custom silicon for hyperscalers — chips built to one customer's specification rather than sold off the shelf — plus the electro-optics and networking parts that move data between servers. Its custom AI silicon programmes with a small number of very large cloud customers are the whole growth story.",
      [("Data Center", 73), ("Enterprise Networking", 11), ("Carrier Infrastructure", 8), ("Consumer & Auto", 8)],
      ["Custom AI silicon is the one credible alternative to buying merchant GPUs, and Marvell is one of only two companies doing it at scale.",
       "Electro-optics content grows with every increase in data-centre interconnect speed.",
       "Design wins lock in multi-year revenue because a custom chip cannot be second-sourced."],
      ["Extreme customer concentration — a handful of hyperscalers drive the majority of growth, and any one of them insourcing would be severe.",
       "Broadcom is the larger and better-established custom silicon competitor.",
       "The legacy consumer, carrier and enterprise businesses are shrinking and mask the underlying data-centre growth."],
      "Widely held as a second way to own the AI build-out, and the expanded Google custom-chip agreement in July 2026 sharply lifted the shares. Record second-quarter revenue of $2.74 billion and raised guidance still left the stock down about 10% the next day, as investors focused on lower gross margin guidance and Google revenue arriving later. The argument remains how durable custom silicon share is once hyperscalers build internal teams.",
      "Google TPU programme revenue ramp, Q3 FY27 results against the $3.15 billion guide, gross margin as custom silicon grows, optical DSP share, hyperscaler capex guidance.",
      (4, 5, 3, 4)),

    C("SNPS", "Synopsys, Inc.", "semis", "Sunnyvale, California, USA", 1986,
      "Sassine Ghazi", "Nasdaq", 495.00, 0.155, -2.0, 6.6,
      [0.16, 0.14, 0.12, 0.10, 0.09], 0.30, 0.34, 0.090, 0.030,
      "Founded in 1986 by Aart de Geus, who ran it until 2024 when Sassine Ghazi took over. Synopsys makes electronic design automation software — the tools every chip company uses to design, simulate and verify silicon before it is manufactured. It also licenses silicon IP: pre-built, pre-verified circuit blocks that customers drop into their own designs. Together with Cadence it forms a duopoly that is effectively unavoidable for anyone designing a modern chip.",
      [("Design Automation", 65), ("Design IP", 35)],
      ["A genuine duopoly with Cadence. Switching EDA vendors mid-design is close to impossible, so revenue is subscription-like and highly visible.",
   "Every new chip design needs more verification, so tool spend rises with complexity regardless of unit volumes.",
   "AI chip proliferation means more customers designing more silicon; new multi-year deals announced in September 2026 with OpenAI and Amazon extend Synopsys into AI-assisted design and custom silicon IP."],
      ["Growth depends on customers' R&D budgets, which are discretionary in a downturn.",
       "Valuation embeds a lot of durability — this has rarely been a cheap stock.",
       "China exposure is a persistent regulatory risk for design tools."],
      "Treated as a picks-and-shovels way to own semiconductor complexity without the cycle, and the pushback has mostly been valuation. The shares slid towards a 52-week low in mid-September 2026 despite a fiscal third-quarter beat, then rose about 10% on 1 October after the investor day set a fiscal 2027 revenue target of $11.15 billion and a roughly $1 billion buyback.",
      "Fiscal Q4 results, delivery against the fiscal 2027 revenue target, OpenAI and Amazon deal ramp, IP attach rates, backlog growth, China licensing rules.",
      (5, 4, 5, 5)),

    C("CDNS", "Cadence Design Systems, Inc.", "semis", "San Jose, California, USA", 1988,
      "Anirudh Devgan", "Nasdaq", 310.00, 0.273, -1.5, 4.8,
      [0.15, 0.13, 0.11, 0.10, 0.09], 0.31, 0.34, 0.090, 0.030,
      "Formed in 1988 from the merger of SDA Systems and ECAD. Anirudh Devgan became CEO in 2021. Cadence is the other half of the EDA duopoly, selling the software used to design and verify integrated circuits, plus hardware emulation systems that let engineers test a chip design before committing to silicon. It has pushed into system-level simulation, applying the same computational approach to aerospace, automotive and molecular design.",
      [("Core EDA", 70), ("IP", 14), ("System Design & Analysis", 16)],
      ["Duopoly economics with Synopsys, and roughly 90% recurring revenue.",
       "Hardware emulation is a genuine differentiator and carries strong pricing power.",
       "System design and analysis opens a market well beyond semiconductors."],
      ["Same customer R&D dependency as Synopsys.",
       "Consistently expensive, so the stock is sensitive to any growth disappointment.",
       "Export controls on advanced design tools remain a live issue."],
      "Bracketed with Synopsys as a high-quality compounder. Debate centres on which of the two is better positioned in AI chip design.",
      "Emulation hardware orders, recurring revenue mix, system design growth, export policy.",
      (5, 4, 5, 5)),

    C("NXPI", "NXP Semiconductors N.V.", "semis", "Eindhoven, Netherlands", 1953,
      "Rafael Sotomayor", "Nasdaq", 225.00, 0.25, 8.0, 12.6,
      [0.09, 0.10, 0.09, 0.08, 0.07], 0.26, 0.30, 0.095, 0.028,
      "Spun out of Philips in 2006, with roots going back to Philips Semiconductors in 1953. Rafael Sotomayor is CEO. NXP is one of the largest automotive chip suppliers, making the processors, radar sensors, secure elements and battery management systems that go into modern vehicles. It is Nasdaq-listed despite being Dutch-headquartered, which is why it appears in this coverage.",
      [("Automotive", 56), ("Industrial & IoT", 18), ("Mobile", 12), ("Communication Infrastructure", 14)],
      ["Automotive semiconductor content per vehicle keeps rising regardless of how many cars are sold.",
       "Radar and secure car access are high-barrier businesses with long design cycles.",
       "Design wins lock in revenue for the life of a vehicle platform, typically 5–7 years."],
      ["Automotive is more than half of revenue and grew only 12% year on year in the second quarter of 2026, well behind industrial and communications infrastructure, so softer car production would weigh heavily.",
   "Chinese domestic chipmakers are moving up the value chain in automotive.",
   "Heavier debt load than analog peers limits flexibility."],
      "Seen as cheap relative to analog peers, with the discount attributed to automotive cyclicality and China exposure. Growth has returned, with second-quarter 2026 revenue up 19.5% and third-quarter guidance above consensus, and management says data-centre revenue should exceed $500 million in 2026. The stock closed at $238.08 on 25 September 2026 against an average analyst target of about $306.",
      "Q3 results, auto production forecasts, data-centre and physical AI revenue, radar design wins, China competitive dynamics.",
      (4, 3, 3, 4)),

    # ===================== SOFTWARE & INTERNET =====================
    C("IBM", "International Business Machines Corporation", "software", "Armonk, New York, USA", 1911,
      "Arvind Krishna", "NYSE", 285.00, 0.93, 40.0, 63.0,
      [0.06, 0.06, 0.05, 0.05, 0.04], 0.20, 0.23, 0.085, 0.025,
      "Founded in 1911 as the Computing-Tabulating-Recording Company and renamed IBM in 1924. Arvind Krishna became CEO in 2020 and reoriented the company around hybrid cloud and AI, spinning off the managed infrastructure business as Kyndryl in 2021. The 2019 Red Hat acquisition is the strategic centre: OpenShift gives enterprises a way to run workloads across their own data centres and multiple public clouds. Consulting and the mainframe business fund a substantial dividend.",
      [("Software", 45), ("Consulting", 33), ("Infrastructure", 20), ("Financing & Other", 2)],
      ["Red Hat and OpenShift give IBM a defensible position in hybrid cloud that the hyperscalers cannot easily replicate.",
   "Deep enterprise and government relationships create long, sticky contracts.",
   "Mainframe revenue carries very high margins, although the 2026 Z shortfall showed it is more deal-dependent and cyclical than bulls had assumed."],
      ["Overall growth is low single digit, so the equity story rests on margin and multiple rather than expansion.",
       "Consulting is exposed to enterprise IT budget cycles.",
       "Competing against AWS, Azure and Google Cloud with a fraction of their capital investment."],
      "Sentiment soured after the second quarter of 2026, when a shortfall in Z mainframe sales left revenue up only 1% and the shares fell 25% in a single day; they were down 26% for the year by the end of September. Bulls point to resilient software and steady consulting demand; bears to low underlying growth and the reliability of mainframe cycles.",
      "Z mainframe deal closures, third-quarter 2026 results, software segment growth, Red Hat bookings, consulting backlog, free cash flow guidance.",
      (4, 2, 3, 4)),

    C("CSCO", "Cisco Systems, Inc.", "software", "San Jose, California, USA", 1984,
      "Chuck Robbins", "Nasdaq", 72.00, 3.95, 10.0, 56.0,
      [0.07, 0.06, 0.05, 0.05, 0.04], 0.24, 0.26, 0.085, 0.025,
      "Founded in 1984 by Leonard Bosack and Sandy Lerner, two Stanford staff who wanted to connect incompatible campus networks. Chuck Robbins has been CEO since 2015. Cisco makes the routers, switches and security products that carry most enterprise network traffic, and has been shifting from selling hardware boxes to selling software subscriptions. The 2024 Splunk acquisition added a large observability and security analytics business.",
      [("Networking", 50), ("Security", 20), ("Collaboration", 9), ("Observability & Services", 21)],
      ["Enormous installed base and switching costs — replacing enterprise networking gear is disruptive and rarely worth it.",
       "AI data centres need vastly more networking capacity, which plays to Cisco's core.",
       "The subscription shift makes revenue more predictable and supports a higher multiple."],
      ["Arista and white-box vendors have taken meaningful share in high-performance data-centre switching.",
   "AI infrastructure is diluting margins: adjusted gross margin fell to 66.3% from 68.4% in the fourth quarter of fiscal 2026.",
   "Splunk was expensive and integration risk is real."],
      "No longer seen purely as an income holding: product orders rose 35% in the fourth quarter of fiscal 2026 and AI infrastructure orders reached $9.3bn for the year. The shares nonetheless fell after the August 2026 results, with gross margin compression and high expectations after a 60% rally in 2026 weighing.",
      "AI infrastructure orders and the $7.5bn fiscal 2027 AI revenue expectation, gross margin trend, security attach rates, annual recurring revenue growth, Splunk integration.",
      (4, 2, 3, 4)),

    C("INTU", "Intuit Inc.", "software", "Mountain View, California, USA", 1983,
      "Sasan Goodarzi", "Nasdaq", 333.13, 0.56, 3.0, 17.5,
      [0.13, 0.12, 0.11, 0.10, 0.09], 0.30, 0.34, 0.090, 0.028,
      "Founded in 1983 by Scott Cook and Tom Proulx to make personal finance software. Sasan Goodarzi has been CEO since 2019. Intuit owns TurboTax and QuickBooks, giving it dominant positions in US consumer tax filing and small business accounting, plus Credit Karma and Mailchimp. The businesses are unusually defensible: switching accounting software mid-year is painful, and tax filing is an annual habit reinforced by having last year's return already stored.",
      [("Small Business & Self-Employed", 58), ("Consumer (TurboTax)", 27), ("Credit Karma", 9), ("ProTax", 6)],
      ["QuickBooks is the default small business accounting standard in the US, with very low churn.",
       "TurboTax benefits from an annual recurring habit and stored prior-year data.",
       "AI-assisted tax and bookkeeping is a natural fit that could raise both pricing and attach rates."],
      ["Persistent political pressure in the US for free government-run tax filing.",
   "Small business formation and health drive QuickBooks, so a recession hits directly.",
   "Fiscal 2027 guidance of 9–10% revenue growth, with TurboTax at 2–3% and Mailchimp flat to down, marks a clear slowdown from 14% in fiscal 2026."],
      "Still regarded as a high-quality software franchise, but expectations were reset in August 2026 when fiscal 2027 revenue guidance came in below consensus and the shares fell about 12% in early trading. Management cited weaker Mailchimp growth, a shrinking desktop ecosystem and deliberate changes to TurboTax, and Stifel warned the changes will take longer to work through.",
      "TurboTax customer growth after pricing changes, Global Business Solutions growth, Mailchimp stabilisation, AI feature monetisation, regulatory developments.",
      (5, 4, 4, 5)),

    C("PANW", "Palo Alto Networks, Inc.", "software", "Santa Clara, California, USA", 2005,
      "Nikesh Arora", "Nasdaq", 354.02, 0.66, -2.5, 9.2,
      [0.15, 0.14, 0.12, 0.11, 0.10], 0.27, 0.32, 0.100, 0.030,
      "Founded in 2005 by Nir Zuk, who had helped build the first stateful firewall at Check Point. Nikesh Arora, previously of Google and SoftBank, became CEO in 2018 and drove an aggressive acquisition programme, culminating in the purchase of identity security specialist CyberArk. Palo Alto sells network security, cloud security, security operations and identity software, and has pushed a platformisation strategy — persuading customers to consolidate multiple point vendors onto one platform in exchange for better pricing.",
      [("Network Security", 55), ("Cloud Security (Prisma)", 25), ("Security Operations (Cortex)", 20)],
      ["Security budgets are among the last things enterprises cut.",
       "Platform consolidation displaces multiple competitors at once and deepens lock-in.",
       "AI creates genuinely new attack surfaces, which expands the addressable market."],
      ["Platformisation involves giving away product early to win the consolidation, which pressures near-term revenue.",
       "Crowded competitive field including CrowdStrike, Zscaler, Fortinet and Microsoft.",
       "Microsoft bundling security into E5 licences is a structural threat to the whole sector."],
      "Well regarded on execution, but the shares fell about 8% after the fiscal 2026 results as next-generation security ARR missed expectations and fiscal 2027 guidance implied 22–23% ARR growth; Raymond James noted the beat decelerated in a healthy environment. The debate has moved to how much growth is organic after CyberArk and whether that pace supports the valuation.",
      "Next-generation security ARR against the $11.075–11.175bn fiscal 2027 guide, CyberArk identity cross-sell, platformisation deal count, remaining performance obligations.",
      (4, 4, 4, 4)),

    C("ACN", "Accenture plc", "software", "Dublin, Ireland", 1989,
      "Julie Sweet", "NYSE", 330.00, 0.63, -3.0, 66.0,
      [0.07, 0.07, 0.06, 0.06, 0.05], 0.15, 0.17, 0.085, 0.026,
      "Separated from Arthur Andersen in 1989 and renamed Accenture in 2001. Julie Sweet has been CEO since 2019. Accenture is the largest technology consultancy in the world, employing around 750,000 people to design and implement systems for large enterprises and governments. It sits between clients and every major software vendor, which gives it an unusually clear view of where corporate technology spending is heading — and a large early book of generative AI work.",
      [("Consulting", 51), ("Managed Services", 49)],
      ["Scale and breadth make it the default partner for large multi-year transformation programmes.",
       "Generative AI bookings have grown quickly, and enterprises rarely deploy AI without an integrator.",
       "Managed services revenue is recurring and cushions consulting cyclicality."],
      ["Discretionary consulting spend is one of the first budget lines cut in a downturn.",
       "A people business — margins depend on utilisation and wage inflation, and there is no operating leverage from software.",
       "AI could eventually automate parts of the implementation work Accenture sells."],
      "Viewed as a barometer for enterprise tech spending, but the shares fell through 2026 on concern that generative AI would reduce demand for labour-intensive consulting and outsourcing, and guidance was lowered in June. A fourth-quarter beat, record large-deal bookings and fiscal 2027 guidance of 3–6% local-currency growth lifted the shares about 22% after the October 2026 results, easing but not settling that debate.",
      "New bookings and large-deal volumes, AI-related demand, headcount and utilisation, first-quarter fiscal 2027 results.",
      (5, 3, 5, 4)),

    C("BKNG", "Booking Holdings Inc.", "software", "Norwalk, Connecticut, USA", 1996,
      "Glenn Fogel", "Nasdaq", 216.00, 0.81, 10.0, 24.5,   # 25-for-1 split, Apr 2026
      [0.09, 0.08, 0.08, 0.07, 0.06], 0.31, 0.34, 0.090, 0.026,
      "Founded in 1996 as Priceline and renamed Booking Holdings in 2018 after its most valuable asset, the Amsterdam-based Booking.com acquired in 2005. Glenn Fogel has been CEO since 2017. It is the largest online travel agency in the world, connecting travellers with hotels, flights and rental cars and taking a commission. Its European hotel network is the deepest of any platform, and the business converts an unusually high share of revenue into free cash flow.",
      [("Agency bookings", 55), ("Merchant bookings", 39), ("Advertising & Other", 6)],
      ["Genuine two-sided network effect: properties list where the travellers are, travellers search where the properties are.",
       "Asset-light with very high free cash flow conversion and aggressive share buybacks.",
       "European hotel supply is fragmented and hard for competitors to replicate."],
      ["Travel demand is highly cyclical and sensitive to shocks, as 2020 demonstrated.",
   "Google, Airbnb, hotel direct-booking programmes and now AI agents such as Meta's Muse, launched in September 2026, all compete for the same customer.",
   "Regulatory pressure in Europe on platform practices and rate parity clauses."],
      "Still regarded as the best-run business in online travel, but the shares fell 5% in a day in September 2026 after Meta launched Muse, an AI agent able to book directly with airlines and hotels. The debate has moved from post-pandemic normalisation to whether AI agents disintermediate aggregators.",
      "Room night growth, take rate, AI agent distribution and competition, direct booking mix, European regulatory decisions.",
      (5, 3, 4, 5)),

    # ===================== HEALTHCARE =====================
    C("PFE", "Pfizer Inc.", "health", "New York, New York, USA", 1849,
      "Albert Bourla", "NYSE", 26.00, 5.68, 55.0, 62.0,
      [0.03, 0.04, 0.04, 0.03, 0.02], 0.17, 0.22, 0.085, 0.022,
      "Founded in 1849 by cousins Charles Pfizer and Charles Erhart in Brooklyn. Albert Bourla has been CEO since 2019 and oversaw the Comirnaty COVID-19 vaccine, which briefly made Pfizer the highest-revenue pharmaceutical company in the world before demand collapsed. The company spent much of that windfall on acquisitions, most significantly $43bn for Seagen in 2023 to build an antibody-drug conjugate oncology franchise. The central question is whether that pipeline can offset a heavy patent cliff.",
      [("Oncology", 27), ("Primary Care", 26), ("Specialty Care", 24), ("Hospital & Other", 23)],
      ["Seagen gives Pfizer a genuine position in antibody-drug conjugates, one of the most productive areas in oncology.",
       "The dividend yield is among the highest in large-cap pharma and is covered by current cash flow.",
       "Expectations are low enough that pipeline surprises are asymmetric to the upside."],
      ["A severe patent cliff through the late 2020s affecting Eliquis, Prevnar and several others.",
       "The COVID revenue collapse was faster and deeper than management guided, which damaged credibility.",
       "Heavy debt load taken on to fund Seagen limits further business development."],
      "One of the more divided large-cap pharma names. Second-quarter 2026 results beat expectations, the revenue range was raised to $60.5–62.5bn and the CEO bought about $1m of stock in August; bears still point to the patent cliff, including Eliquis exclusivity loss around 2028, and a mixed acquisition record.",
      "MEVPRO-1 mevrometostat prostate cancer readout in the fourth quarter of 2026, oncology pipeline readouts, patent cliff mitigation, delivery of the $9.7bn cost savings target, third-quarter results on 3 November 2026.",
      (3, 2, 3, 3)),

    C("TMO", "Thermo Fisher Scientific Inc.", "health", "Waltham, Massachusetts, USA", 1956,
      "Marc Casper", "NYSE", 540.00, 0.38, 30.0, 43.0,
      [0.07, 0.08, 0.07, 0.06, 0.06], 0.20, 0.24, 0.085, 0.026,
      "Formed by the 2006 merger of Thermo Electron, founded in 1956, and Fisher Scientific. Marc Casper has been CEO since 2009 and has made the company the largest life sciences supplier in the world through relentless acquisition. Thermo Fisher sells the instruments, reagents, consumables and contract manufacturing services that pharmaceutical companies, hospitals and academic labs depend on. It profits from drug development activity itself, regardless of which drugs succeed.",
      [("Laboratory Products & Biopharma Services", 55), ("Life Sciences Solutions", 17), ("Analytical Instruments", 17), ("Specialty Diagnostics", 11)],
      ["Sells to the entire industry rather than betting on individual drugs — a picks-and-shovels position in biopharma.",
       "Consumables and reagents are recurring revenue tied to installed instruments.",
       "An exceptional acquisition track record, with a repeatable integration playbook."],
      ["Pharmaceutical R&D budgets and biotech funding drive demand, and both have been under pressure.",
       "China represents a meaningful share of revenue and has been weak.",
       "The post-pandemic normalisation in lab spending has taken longer than expected."],
      "Held in high regard as a compounder, and sentiment has improved: the shares rose about 25% in the three months to early October 2026. Deutsche Bank and JPMorgan both turned more positive, citing end-market improvement, a path to high-single-digit growth by 2028 and demand from US pharmaceutical manufacturing reshoring.",
      "Third-quarter results on 21 October 2026, biotech funding conditions, China demand, bioproduction orders, pharma R&D budgets.",
      (5, 3, 4, 5)),

    C("ABT", "Abbott Laboratories", "health", "Abbott Park, Illinois, USA", 1888,
      "Robert Ford", "NYSE", 135.00, 1.74, 5.0, 42.0,
      [0.07, 0.07, 0.07, 0.06, 0.06], 0.19, 0.23, 0.080, 0.026,
      "Founded in 1888 by physician Wallace Abbott. Robert Ford has been CEO since 2020. Abbott spans four quite different businesses: medical devices, diagnostics, established pharmaceuticals sold mainly in emerging markets, and nutrition products including Similac and Ensure. The acquisition of Exact Sciences added Cologuard and a cancer screening franchise to diagnostics. Its most important growth asset is FreeStyle Libre, a continuous glucose monitor that has become the standard of care for diabetes management and is expanding into non-insulin-dependent users.",
      [("Medical Devices", 45), ("Diagnostics", 22), ("Nutrition", 18), ("Established Pharmaceuticals", 15)],
      ["FreeStyle Libre is a category leader in a large and still-underpenetrated diabetes market.",
       "Genuine diversification across four businesses smooths the earnings profile.",
       "Structural heart and electrophysiology device franchises are growing well above company average."],
      ["COVID testing revenue has fully normalised, creating a multi-year comparison drag.",
       "Ongoing litigation relating to preterm infant formula creates a tail risk that is hard to size.",
       "Dexcom competes directly and aggressively in continuous glucose monitoring."],
      "Viewed as a steady, defensive compounder. Rothschild & Co Redburn upgraded the shares to Buy in October 2026, arguing Exact Sciences strengthens diagnostics growth and margins; the $385m settlement in September 2026 closed the government's 2022 formula recall case, leaving preterm formula litigation and Libre growth as the main swing factors.",
      "Libre user growth and the Libre Duo launch, Cologuard and SimpleScreen CRC uptake, structural heart procedure volumes, preterm formula litigation, third-quarter results.",
      (5, 3, 4, 5)),

    C("DHR", "Danaher Corporation", "health", "Washington, D.C., USA", 1969,
      "Julie Sawyer Montgomery", "NYSE", 215.00, 0.72, 14.0, 24.0,
      [0.06, 0.08, 0.08, 0.07, 0.06], 0.22, 0.26, 0.085, 0.026,
      "Founded in 1969 as a real estate trust and rebuilt as an industrial conglomerate by the Rales brothers. Rainer Blair, CEO from 2020, handed over on 1 October 2026 to Julie Sawyer Montgomery, who joined Danaher in 2017. Danaher has spent the last decade transforming itself into a pure life sciences and diagnostics company, spinning off its industrial businesses as Fortive and Veralto. The Danaher Business System — a rigorous continuous-improvement methodology applied to every acquisition — is the operational core of the company and is widely imitated.",
      [("Biotechnology", 27), ("Life Sciences", 30), ("Diagnostics", 43)],
      ["Cytiva and Pall give Danaher a leading position in bioprocessing, the equipment used to manufacture biologic drugs.",
       "Around 75% of revenue is recurring consumables and services.",
       "The Danaher Business System has a long, verifiable record of improving acquired businesses."],
      ["Bioprocessing demand fell sharply as customers worked through pandemic-era inventory, and the recovery has been slow.",
       "China is a meaningful market and remains weak.",
       "Valuation still reflects a premium quality rating that recent growth has not supported."],
      "Long regarded as one of the best-run companies in healthcare. The bear case centres on bioprocessing normalisation timing, and the October 2026 handover from Rainer Blair to Julie Sawyer Montgomery adds a leadership transition to watch.",
      "New CEO's priorities, bioprocessing order recovery, China demand, respiratory testing volumes, margin trajectory.",
      (5, 3, 4, 5)),

    C("BMY", "Bristol-Myers Squibb Company", "health", "Princeton, New Jersey, USA", 1887,
      "Christopher Boerner", "NYSE", 52.00, 2.03, 40.0, 48.0,
      [0.02, 0.03, 0.04, 0.04, 0.03], 0.24, 0.27, 0.090, 0.020,
      "Traces to Bristol-Myers, founded 1887, merged with Squibb in 1989. Christopher Boerner became CEO in late 2023. Bristol Myers Squibb sells Eliquis, the leading blood thinner, and Opdivo, a foundational cancer immunotherapy. Both face loss of exclusivity within a few years, and the company has made a series of large acquisitions — Karuna, RayzeBio, Mirati — to rebuild the pipeline. Cobenfy, a novel schizophrenia treatment from Karuna, is the most important new launch.",
      [("Oncology", 40), ("Cardiovascular", 27), ("Immunology", 20), ("Neuroscience & Other", 13)],
      ["Cobenfy is the first genuinely new mechanism in schizophrenia in decades and addresses a large underserved population.",
       "Trades at one of the lowest multiples in large-cap pharma with a substantial dividend.",
       "Strong current cash generation funds both the dividend and continued business development."],
      ["Eliquis and Opdivo together represent a very large share of revenue and both face exclusivity loss.",
       "Recent acquisitions have been expensive and have not yet demonstrated returns.",
       "US drug pricing reform disproportionately affects the highest-revenue products."],
      "A classic value-versus-patent-cliff debate, now focused on a cluster of pipeline readouts. In October 2026 Leerink downgraded to Market Perform with a $59 target, doubting milvexian against Eliquis, admilparant and Cobenfy in Alzheimer's disease psychosis, while Piper Sandler had raised its target to $82 in September on the same milestones.",
      "Milvexian atrial fibrillation data, admilparant phase 3 in pulmonary fibrosis, Cobenfy in Alzheimer's disease psychosis, Cobenfy launch trajectory, Eliquis exclusivity timeline, third-quarter results on 29 October 2026.",
      (3, 2, 3, 3)),

    C("GILD", "Gilead Sciences, Inc.", "health", "Foster City, California, USA", 1987,
      "Daniel O'Day", "Nasdaq", 115.00, 1.25, 18.0, 28.5,
      [0.05, 0.05, 0.05, 0.04, 0.04], 0.32, 0.35, 0.085, 0.022,
      "Founded in 1987 by Michael Riordan, a 29-year-old physician. Daniel O'Day has been CEO since 2019. Gilead built the modern HIV treatment franchise — Biktarvy is the most prescribed HIV regimen in the world — and later transformed hepatitis C from a chronic condition into a curable one. That cure destroyed its own market, an unusual case of clinical success undermining commercial value. The company has since spent heavily to build an oncology franchise, with mixed results.",
      [("HIV", 68), ("Oncology", 12), ("Liver Disease", 11), ("Other", 9)],
      ["Biktarvy has dominant share in HIV treatment with high barriers and very strong margins.",
       "Lenacapavir, a long-acting injectable, could substantially expand the HIV prevention market.",
       "Free cash flow generation is exceptional and supports a large dividend."],
      ["Heavy dependence on a single therapeutic area — around two thirds of revenue is HIV.",
       "The oncology expansion, particularly Trodelvy and the Immunomedics acquisition, has disappointed relative to its cost.",
       "HIV patent exclusivity begins to erode in the 2030s and the replacement is not yet visible."],
      "Viewed as a cash-generative franchise with a concentration problem, but sentiment has improved, with the shares up nearly 20% in 2026 by late August. Lenacapavir uptake in prevention and new combinations such as Bixlenvo, approved in August 2026, are the main swing factors.",
      "Lenacapavir prevention uptake and international access deals, Bixlenvo launch, Biktarvy share, oncology pipeline, third-quarter results on 29 October 2026.",
      (4, 3, 4, 4)),

    C("ELV", "Elevance Health, Inc.", "health", "Indianapolis, Indiana, USA", 1946,
      "Gail Boudreaux", "NYSE", 410.00, 0.23, 22.0, 175.0,
      [0.06, 0.06, 0.05, 0.05, 0.05], 0.035, 0.042, 0.085, 0.026,
      "Traces to Blue Cross of Indiana, founded 1946, and became Anthem before renaming to Elevance in 2022. Gail Boudreaux has been CEO since 2017. Elevance is one of the largest US health insurers, holding Blue Cross Blue Shield licences across 14 states, and covers roughly 45 million members across commercial, Medicare and Medicaid plans. Carelon, its health services arm, is an attempt to follow UnitedHealth's Optum model of owning care delivery as well as insurance.",
      [("Commercial & Specialty", 43), ("Government Business", 45), ("Carelon Services", 12)],
      ["Blue Cross Blue Shield brand licences are effectively irreplaceable competitive positions in their states.",
       "Carelon diversifies away from pure insurance underwriting into higher-margin services.",
       "Scale advantages in negotiating provider rates are meaningful and compounding."],
      ["Medicaid redeterminations left a sicker member pool; management calls 2026 the trough year for Medicaid margins and is exiting the Washington, D.C. and Louisiana Medicaid markets.",
   "Medicare Advantage reimbursement rates have tightened and utilisation has run above expectations.",
   "Health insurance is politically exposed in a way few industries are."],
      "Trades at a discount to UnitedHealth, which most attribute to Carelon being less developed than Optum. In September 2026 management reaffirmed 2026 adjusted EPS of at least $27, said third-quarter results were tracking ahead of plan and targeted at least 12% EPS growth in 2027.",
      "Third-quarter results on 21 October 2026, Medicaid rate adequacy, Medicare Advantage margin recovery, star ratings, Carelon growth.",
      (4, 3, 3, 4)),

    C("MDT", "Medtronic plc", "health", "Dublin, Ireland", 1949,
      "Geoffrey Martha", "NYSE", 95.00, 1.28, 18.0, 33.5,
      [0.05, 0.05, 0.05, 0.05, 0.04], 0.19, 0.22, 0.080, 0.025,
      "Founded in 1949 by Earl Bakken in a Minneapolis garage, repairing medical equipment before building the first wearable external pacemaker. Geoffrey Martha has been CEO since 2020. Medtronic is the largest pure-play medical device company in the world, spanning cardiac rhythm management, cardiac ablation, surgical robotics and neuromodulation. Its diabetes business was listed separately as MiniMed in March 2026, and in September 2026 Medtronic launched an exchange offer to complete the separation. Its Irish domicile dates from the 2015 Covidien acquisition.",
      [("Cardiovascular", 37), ("Neuroscience", 29), ("Medical Surgical", 25), ("Diabetes", 9)],
      ["Enormous installed base and long-standing surgeon relationships create real switching friction.",
   "Pulsed field ablation is a genuinely new cardiac technology where Medtronic entered early, and cardiac ablation revenue rose 88% in the first quarter of fiscal 2027.",
   "Procedure volumes have recovered well and the demographic tailwind is durable."],
      ["Growth has trailed peers such as Boston Scientific and Stryker for several years.",
       "The Hugo surgical robot is far behind Intuitive's da Vinci in adoption.",
       "Diabetes has lost share to Dexcom and Abbott in continuous glucose monitoring."],
      "Generally seen as a solid but slower-growing franchise, though momentum has improved: the first quarter of fiscal 2027 beat expectations and organic growth guidance was raised to 7.25–7.75%. Pulsed field ablation and completion of the MiniMed separation are the main points of debate.",
      "MiniMed exchange offer result (expires 9 October 2026), pulsed field ablation adoption, Hugo and Sentire robot placements, procedure volume growth.",
      (4, 2, 3, 4)),

    # ===================== FINANCIALS =====================
    C("WFC", "Wells Fargo & Company", "financials", "San Francisco, California, USA", 1852,
      "Charles Scharf", "NYSE", 78.00, 3.30, 0.0, 82.0,
      [0.04, 0.05, 0.05, 0.04, 0.04], 0.24, 0.28, 0.100, 0.025,
      "Founded in 1852 by Henry Wells and William Fargo to serve the California gold rush. Charles Scharf became CEO in 2019 with a mandate to fix the bank after the 2016 fake accounts scandal, which led to an unprecedented Federal Reserve asset cap that constrained the balance sheet for seven years. Wells Fargo is one of the largest US retail banks, with a deposit franchise spanning consumer banking, commercial lending, wealth management and a growing corporate and investment bank.",
      [("Consumer Banking & Lending", 37), ("Commercial Banking", 22), ("Corporate & Investment Banking", 25), ("Wealth & Investment Management", 16)],
      ["Removal of the Federal Reserve asset cap frees the balance sheet to grow for the first time since 2018.",
       "A large, low-cost deposit base is one of the most valuable assets in banking.",
       "Significant cost reduction is still available after years of elevated regulatory spending."],
      ["Consumer credit quality deteriorates in a recession, and Wells has meaningful card and auto exposure.",
       "Commercial real estate exposure, particularly office, remains a concern.",
       "The reputational damage from the accounts scandal took years to repair and constrains regulatory goodwill."],
      "The asset cap removal is largely priced in, and 2026 is seen as a transition year while Wells rebuilds its growth engine. In October 2026 Morgan Stanley upgraded the shares to Overweight and a top pick, forecasting a 17% return on tangible common equity in the second half of 2027, while several brokers trimmed targets on deposit costs and normalising capital-markets activity.",
      "Third-quarter results on 13 October 2026, net interest income guidance, loan growth post asset cap, return on tangible common equity, expense reduction.",
      (3, 3, 3, 4)),

    C("C", "Citigroup Inc.", "financials", "New York, New York, USA", 1812,
      "Jane Fraser", "NYSE", 92.00, 1.87, 0.0, 81.0,
      [0.03, 0.04, 0.04, 0.04, 0.03], 0.20, 0.26, 0.105, 0.025,
      "Traces to the City Bank of New York, founded 1812. Jane Fraser became CEO in 2021, the first woman to lead a major US bank, and has run an aggressive simplification programme — exiting consumer banking in more than a dozen countries and reorganising into five reporting segments. Citigroup's genuine differentiator is its treasury and trade solutions business, which moves money across borders for multinational corporations in a way few competitors can match.",
      [("Services", 27), ("Markets", 25), ("Banking", 15), ("US Personal Banking", 25), ("Wealth", 8)],
      ["Treasury and trade solutions is a genuinely differentiated global business with high barriers to entry.",
       "Trades at a substantial discount to tangible book value, the widest among large US banks.",
       "The simplification programme has real cost reduction still to come."],
      ["A long history of restructuring plans that did not deliver, which weighs on credibility.",
       "Consent orders relating to risk management and data infrastructure remain outstanding.",
       "Emerging market exposure adds volatility that domestic-focused peers do not carry."],
      "The classic value case in US banking — cheap for identifiable reasons, with the argument being whether Fraser's restructuring finally closes the gap. The shares fell with other bank stocks in early October 2026 as Treasury yields rose, leaving Citi at roughly 11 times forward earnings, level with Bank of America and below JPMorgan.",
      "Third-quarter results on 13 October 2026, Banamex deconsolidation in early 2027, return on tangible common equity progress, expense targets, consent order resolution, capital returns.",
      (3, 2, 3, 3)),

    C("SCHW", "The Charles Schwab Corporation", "financials", "Westlake, Texas, USA", 1971,
      "Rick Wurster", "NYSE", 90.00, 1.82, 0.0, 21.0,
      [0.08, 0.08, 0.07, 0.06, 0.06], 0.32, 0.36, 0.095, 0.028,
      "Founded in 1971 by Charles Schwab as a discount brokerage, undercutting the fixed commissions that prevailed before deregulation. Rick Wurster became CEO in January 2025, succeeding Walt Bettinger. Schwab is the largest US retail brokerage with several trillion dollars in client assets, and earns money three ways: net interest on client cash, asset management fees, and trading revenue. The 2020 TD Ameritrade acquisition consolidated the industry substantially.",
      [("Net Interest Revenue", 50), ("Asset Management Fees", 33), ("Trading Revenue", 13), ("Other", 4)],
      ["Enormous scale in retail brokerage creates cost advantages competitors cannot match.",
       "Client assets grow with markets and with net new accounts, giving natural operating leverage.",
       "Cash sorting pressure from the rate cycle has largely worked through."],
      ["Earnings are highly sensitive to interest rates through the client cash balance.",
       "Clients moving cash to higher-yielding alternatives compresses the most profitable revenue line.",
       "Zero-commission trading removed a revenue stream permanently and increased reliance on net interest."],
      "Recovery from the 2023 deposit stress has been the dominant theme, and asset gathering remains strong: core net new assets were a record $64.8 billion for August 2026 while client cash fell to 8.8% of client assets. The debate is the normalised earnings power once cash sorting fully ends.",
      "Fall Business Update on 15 October 2026, net new asset growth, client cash balances, net interest margin, margin lending balances.",
      (4, 3, 3, 4)),

    C("SPGI", "S&P Global Inc.", "financials", "New York, New York, USA", 1860,
      "Martina Cheung", "NYSE", 545.00, 0.305, 10.0, 14.5,
      [0.08, 0.08, 0.07, 0.07, 0.06], 0.35, 0.38, 0.085, 0.028,
      "Traces to Henry Varnum Poor's 1860 publication analysing railroad finances. Martina Cheung became CEO in November 2024. S&P Global operates one of the two dominant credit rating agencies, owns the S&P 500 and other benchmark indices, and sells market data and commodity price assessments through Platts. The 2022 IHS Markit merger substantially expanded the data business. The index franchise is the crown jewel: passive funds pay a fee based on assets tracking indices S&P owns.",
      [("Market Intelligence", 36), ("Ratings", 34), ("Indices", 16), ("Commodity Insights", 14)],
      ["The index business collects fees on trillions of passive assets with almost no incremental cost.",
       "Credit ratings is a regulated duopoly with Moody's, and issuers have no practical alternative.",
       "Recurring subscription revenue across data businesses gives high visibility."],
      ["Ratings revenue is tied to debt issuance volumes, which fall sharply when rates rise.",
   "Regulatory attention to rating agency conflicts of interest never fully goes away.",
   "Investors worry that AI tools could erode demand for parts of the data and analytics business, a concern that has weighed on the shares through 2026."],
      "Regarded as one of the best business models in financials. The shares were down about 21% for the year by late September 2026 as concern grew that AI could erode the data and analytics business, shifting the debate from price towards the durability of the franchise.",
      "Debt issuance volumes, index assets under management, subscription renewal rates, Vitality revenue, OpenZeppelin acquisition closing.",
      (5, 4, 4, 5)),

    C("PGR", "The Progressive Corporation", "financials", "Mayfield Village, Ohio, USA", 1937,
      "Tricia Griffith", "NYSE", 265.00, 0.585, 0.0, 75.0,
      [0.11, 0.10, 0.09, 0.08, 0.07], 0.11, 0.13, 0.090, 0.026,
      "Founded in 1937 by Joseph Lewis and Jack Green, initially insuring drivers other companies rejected. Tricia Griffith has been CEO since 2016. Progressive is one of the largest US auto insurers and has been taking share consistently for years. Its advantage is pricing sophistication — segmenting drivers more finely than competitors, and using telematics through the Snapshot programme to price on actual driving behaviour rather than demographic proxies.",
      [("Personal Auto", 73), ("Commercial Lines", 15), ("Property", 12)],
      ["Consistently better underwriting results than the industry, reflected in a combined ratio below 100 in most years.",
       "Direct distribution avoids agent commissions and structurally lowers the cost base.",
       "Telematics data advantage compounds — more driving data means better pricing means better risk selection."],
      ["Auto insurance is cyclical: periods of strong profitability attract competition and pricing softens.",
       "Severe weather and catastrophe losses hit the property segment hard.",
       "Rate increases that restored profitability may now slow policy growth."],
      "Widely admired as the best operator in personal auto insurance. Monthly results through August 2026 showed earnings falling year on year, with the August combined ratio at 89.3 against 83.1 a year earlier while policies in force still grew 7%. The question is where the cycle is, not whether the company executes.",
      "Combined ratio, policies in force growth, rate adequacy, catastrophe losses.",
      (5, 4, 4, 5)),

    C("CB", "Chubb Limited", "financials", "Zurich, Switzerland", 1882,
      "Evan Greenberg", "NYSE", 300.00, 0.40, 0.0, 58.0,
      [0.06, 0.06, 0.06, 0.05, 0.05], 0.16, 0.18, 0.085, 0.026,
      "Chubb traces to 1882 in New York; the current company was formed when ACE acquired Chubb in 2016 and took its name. Evan Greenberg has been CEO since 2004. Chubb is the largest publicly traded property and casualty insurer in the world, writing commercial and high-net-worth personal insurance across some 54 countries. It is known for underwriting discipline — willingness to shrink premium volume rather than write business at inadequate rates.",
      [("North America Commercial", 40), ("Overseas General", 27), ("North America Personal", 12), ("Life & Other", 21)],
      ["Consistent underwriting profitability across cycles, which is rare in property and casualty insurance.",
       "Global footprint gives access to markets most US insurers cannot reach.",
       "Rising interest rates increase investment income on the float without any underwriting change."],
      ["Catastrophe exposure is inherent and climate trends make historical loss data less predictive.",
       "Commercial insurance pricing is cyclical and has passed its peak in several lines.",
       "Reserve adequacy for long-tail liability lines is difficult for outsiders to verify."],
      "Regarded as the highest-quality underwriter in the sector. Debate focuses on where commercial pricing goes from here.",
      "Combined ratio, commercial rate change, catastrophe losses, investment income.",
      (5, 3, 4, 5)),

    C("PYPL", "PayPal Holdings, Inc.", "financials", "San Jose, California, USA", 1998,
      "Enrique Lores", "Nasdaq", 72.00, 0.98, -5.0, 32.0,
      [0.07, 0.07, 0.06, 0.06, 0.05], 0.19, 0.23, 0.100, 0.028,
      "Founded in 1998 as Confinity, merged with Elon Musk's X.com, acquired by eBay in 2002 and spun back out in 2015. Enrique Lores, formerly chief executive of HP, became CEO in March 2026, replacing Alex Chriss. PayPal processes online payments for merchants and consumers, owns Venmo and Braintree, and handles well over a trillion dollars of payment volume annually. The strategic problem is that its branded checkout business is highly profitable while its unbranded processing business is not.",
      [("Branded Checkout", 30), ("Braintree & Unbranded", 40), ("Venmo", 12), ("Other Value Added Services", 18)],
      ["Around 430 million active accounts create genuine two-sided network effects.",
       "Venmo is culturally embedded with younger US consumers and remains substantially under-monetised.",
       "Strong free cash flow and an aggressive buyback at a depressed multiple."],
      ["Transaction margin has compressed as low-margin Braintree volume grew faster than branded checkout.",
       "Apple Pay, Shop Pay and other native checkout options attack the core branded business directly.",
       "A long record of guidance revisions has damaged management credibility."],
      "One of the more contested large-cap names. A Stripe and Advent International consortium that had offered $60.50 a share in July 2026 abandoned its pursuit in late August, and the shares fell 12.7% to $53.66 on 28 August. Bulls see cheap cash flow and a turnaround under Lores; bears see structural erosion of the profitable segment.",
      "Lores turnaround plan and cost savings, branded checkout growth, transaction margin dollars, Venmo monetisation, active account trends.",
      (3, 3, 4, 3)),

    # ===================== CONSUMER, RETAIL & LUXURY =====================
    C("NKE", "NIKE, Inc.", "consumer", "Beaverton, Oregon, USA", 1964,
      "Elliott Hill", "NYSE", 68.00, 1.48, 2.0, 48.0,
      [0.02, 0.05, 0.06, 0.06, 0.05], 0.11, 0.15, 0.085, 0.026,
      "Founded in 1964 as Blue Ribbon Sports by Phil Knight and his former track coach Bill Bowerman, renamed Nike in 1971. Elliott Hill, a 32-year Nike veteran who had retired, returned as CEO in October 2024 to reverse a strategic misstep: the previous management had pulled back from wholesale retail partners to push direct-to-consumer, ceding shelf space to competitors. Nike remains the largest athletic footwear and apparel brand in the world by a wide margin.",
      [("Footwear", 68), ("Apparel", 27), ("Equipment & Other", 5)],
      ["The strongest brand in athletic apparel, built over six decades of athlete endorsement and marketing.",
       "Rebuilding wholesale relationships restores access to shelf space Nike gave up.",
       "Innovation pipeline and sport franchises give repeatable product cycles."],
      ["On Running, Hoka and New Balance have taken meaningful share in running, Nike's heartland.",
   "Greater China revenue fell 26% on a currency-neutral basis in fiscal Q1 2027 during a marketplace reset, and management expects conditions there to worsen through the year.",
   "Guidance for a high-single-digit revenue decline in fiscal 2027 puts the dividend payout above 100% of adjusted earnings at the midpoint, limiting room for error."],
      "A turnaround story where most agree on the diagnosis and disagree on the timeline. The October 2026 guidance for a high-single-digit revenue decline in fiscal 2027, against a Street expectation of about 2%, pushed that timeline out, and the shares fell about 8.5% in early trading after already losing about 45% in 2026.",
      "Pace cost programme savings, Greater China marketplace reset, wholesale order books, gross margin, running category share.",
      (4, 3, 4, 5)),

    C("SBUX", "Starbucks Corporation", "consumer", "Seattle, Washington, USA", 1971,
      "Brian Niccol", "Nasdaq", 98.00, 1.14, 25.0, 36.5,
      [0.04, 0.06, 0.06, 0.06, 0.05], 0.11, 0.15, 0.085, 0.026,
      "Founded in 1971 in Pike Place Market selling coffee beans; Howard Schultz transformed it into a coffeehouse chain after a trip to Milan. Brian Niccol, who had turned around Chipotle, became CEO in September 2024 with a mandate to fix deteriorating store throughput and a diluted brand experience. The 'Back to Starbucks' plan focuses on simplifying the menu, improving service times and restoring the cafe environment that mobile ordering had eroded.",
      [("North America", 74), ("International", 20), ("Channel Development", 6)],
      ["One of the most recognised consumer brands globally, with pricing power that has held through inflation.",
       "The rewards programme has tens of millions of active members and drives repeat visits.",
       "Niccol's Chipotle turnaround is a directly relevant and successful precedent."],
      ["The turnaround is expensive: labour investment of at least $500 million and store renovations left the fiscal Q3 2026 operating margin at 12.9%, against 15.8% two years earlier.",
   "China has been particularly weak, with aggressive low-price local competition from Luckin.",
   "Unionisation efforts across US stores create ongoing labour cost and reputational pressure."],
      "A turnaround that is now showing up in the numbers: global comparable sales rose 7.9% in fiscal Q3 2026, with North American transactions up 4.5%. The question has shifted from whether traffic returns to whether margins recover, with management targeting an operating margin of up to 15% by fiscal 2028.",
      "Fiscal fourth-quarter results, North America store closures, operating margin recovery, transaction growth, China performance, store renovation programme.",
      (4, 3, 3, 5)),

    C("LOW", "Lowe's Companies, Inc.", "consumer", "Mooresville, North Carolina, USA", 1921,
      "Marvin Ellison", "NYSE", 255.00, 0.56, 33.0, 83.0,
      [0.02, 0.04, 0.05, 0.05, 0.04], 0.11, 0.13, 0.085, 0.025,
      "Founded in 1921 as a hardware store in North Wilkesboro, North Carolina. Marvin Ellison, previously CEO of JCPenney and a Home Depot veteran, has led since 2018. Lowe's is the second largest home improvement retailer in the US, operating over 1,700 stores. Its customer base skews more towards do-it-yourself homeowners than Home Depot's, which is more weighted to professional contractors — a mix difference that matters a great deal to the cycle.",
      [("DIY Consumer", 70), ("Professional Contractor", 25), ("Online", 5)],
      ["Home improvement is a rational duopoly with Home Depot, and both have pricing discipline.",
       "US housing stock is old and under-supplied, which supports long-run renovation demand.",
       "Substantial operating margin improvement has been delivered under Ellison."],
      ["High mortgage rates have frozen housing turnover, and people renovate when they move.",
       "Big-ticket discretionary projects are the first thing deferred when consumers feel squeezed.",
       "Weaker professional contractor mix than Home Depot, and pros spend more consistently."],
      "Viewed as a quality operator held back by the housing cycle. In August 2026 Lowe's cut its 2026 outlook to the low end of its range, including roughly flat comparable sales and adjusted EPS of about $12.25, after July comparable sales fell 1.2%. Most models assume a recovery when rates fall.",
      "Comparable sales, big-ticket transaction trends, pro customer growth and the FBM and ADG acquisitions, promotional intensity, housing turnover data.",
      (4, 2, 3, 4)),

    C("TGT", "Target Corporation", "consumer", "Minneapolis, Minnesota, USA", 1902,
      "Michael Fiddelke", "NYSE", 105.00, 0.455, 14.0, 107.0,
      [0.02, 0.03, 0.04, 0.04, 0.04], 0.055, 0.07, 0.090, 0.024,
      "Founded in 1902 as the Dayton Dry Goods Company; the first Target store opened in 1962. Michael Fiddelke, previously chief operating officer, became CEO in February 2026, succeeding Brian Cornell. Target occupies an unusual position in US retail — cheaper than department stores but with more design credibility than pure discounters, built on exclusive owned brands and designer collaborations. Roughly half of revenue comes from discretionary categories, which makes it more cyclical than a grocery-weighted competitor.",
      [("Beauty & Household Essentials", 27), ("Food & Beverage", 22), ("Apparel & Accessories", 16), ("Hardlines", 17), ("Home Furnishings", 18)],
      ["Owned brands generate higher margins than national brands and cannot be price-compared directly.",
       "Stores double as fulfilment centres, which makes same-day delivery economics far better than pure e-commerce.",
       "Strong brand affinity with a higher-income customer than most discount retailers."],
      ["Heavy discretionary mix means sales fall faster than grocery-led peers when consumers trade down.",
       "Walmart has been taking share from higher-income shoppers, historically Target's core.",
       "Inventory and shrink management problems have repeatedly caught the company out."],
      "Seen as a good retailer in a difficult discretionary environment, but the second quarter of 2026 gave the Fiddelke turnaround credibility: comparable sales rose 3.8% on a 3.6% rise in traffic and full-year EPS guidance was raised to $9.90 to $10.90, helped by tariff refunds. The shares reached a near two-year high in late August before slipping after the company withdrew a criticised Halloween costume.",
      "Third-quarter results in November 2026, traffic and comparable sales, home and apparel recovery, gross margin excluding tariff refunds, market share versus Walmart.",
      (3, 2, 3, 4)),

    C("TJX", "The TJX Companies, Inc.", "consumer", "Framingham, Massachusetts, USA", 1976,
      "Ernie Herrman", "NYSE", 140.00, 1.12, 2.0, 57.0,
      [0.06, 0.06, 0.06, 0.05, 0.05], 0.10, 0.12, 0.080, 0.026,
      "Founded in 1976 with the first T.J. Maxx store. Ernie Herrman has been CEO since 2016. TJX operates T.J. Maxx, Marshalls and HomeGoods, buying excess inventory from brands and department stores at steep discounts and selling it at prices well below full retail. The treasure-hunt format — constantly changing assortment, no guarantee an item will be there next visit — drives unusually high visit frequency and has proved remarkably resistant to e-commerce.",
      [("Marmaxx (US)", 55), ("HomeGoods", 17), ("TJX Canada", 9), ("TJX International", 19)],
      ["The off-price model gains share in downturns as consumers trade down, and holds it in recoveries.",
       "Buying opportunistically means the model actually benefits from industry-wide inventory gluts.",
       "Treasure-hunt merchandising is genuinely difficult to replicate online."],
      ["Depends on other retailers over-ordering; a disciplined industry reduces available inventory.",
       "Very limited e-commerce presence compared with the rest of retail.",
       "Freight and wage inflation compress margins in a low-gross-margin model."],
      "One of the most consistently well-regarded retailers. In August 2026 TJX raised its full-year EPS guidance to $5.31 to $5.36 and lifted its long-term store target to 7,500, although Marmaxx comparable sales rose only 1% on what management called self-inflicted merchandising errors. The main debate is whether merchandise availability tightens.",
      "Marmaxx comparable sales recovery, merchandise margin, inventory availability, store growth towards the 7,500 target.",
      (5, 3, 5, 5)),

    C("MO", "Altria Group, Inc.", "consumer", "Richmond, Virginia, USA", 1847,
      "Sal Mancuso", "NYSE", 62.00, 1.68, 24.0, 20.5,
      [-0.01, 0.0, 0.01, 0.01, 0.01], 0.45, 0.47, 0.080, 0.015,
      "Traces to 1847 as Philip Morris in London; the US business separated from Philip Morris International in 2008 and renamed Altria. Sal Mancuso, previously chief financial officer, succeeded Billy Gifford as CEO in May 2026. Altria sells Marlboro and other cigarette brands exclusively in the United States, along with oral nicotine products including on! pouches and NJOY e-vapor. The business is in structural volume decline, offset by consistent price increases — a strategy that works until it does not.",
      [("Smokeable Products", 88), ("Oral Tobacco", 11), ("Other", 1)],
      ["Extraordinary margins and free cash flow conversion, funding one of the highest dividend yields in the S&P 500.",
       "Marlboro has held roughly 42% US cigarette share for decades, giving genuine pricing power.",
       "Regulatory barriers make new entry into cigarettes effectively impossible."],
      ["US cigarette volumes decline every year, and the rate of decline has been accelerating.",
       "Illicit disposable vapes have taken share and enforcement has been ineffective.",
       "Menthol ban proposals and nicotine reduction rules are existential regulatory risks."],
      "An income holding where the entire argument is whether price increases can keep outrunning volume decline.",
      "Cigarette shipment volumes, net price realisation, on! pouch growth, FDA regulatory actions.",
      (3, 1, 3, 4)),

    C("MDLZ", "Mondelez International, Inc.", "consumer", "Chicago, Illinois, USA", 2012,
      "Dirk Van de Put", "Nasdaq", 68.00, 1.29, 18.0, 36.5,
      [0.03, 0.04, 0.04, 0.04, 0.04], 0.13, 0.16, 0.080, 0.025,
      "Created in 2012 when Kraft Foods split, with Mondelez taking the global snacks business. Dirk Van de Put has been CEO since 2017. The portfolio is built on Oreo, Cadbury, Milka, Toblerone and Ritz — brands with genuine emotional attachment in their home markets. Roughly 40% of revenue comes from emerging markets, giving it more growth exposure than most packaged food companies but also more currency volatility.",
      [("Biscuits & Baked Snacks", 51), ("Chocolate", 32), ("Gum & Candy", 10), ("Beverages & Cheese", 7)],
      ["Iconic brands with strong local heritage — Cadbury in the UK, Milka in Germany, Oreo globally.",
       "Emerging market exposure provides volume growth that developed-market food companies lack.",
       "Snacking is one of the more resilient food categories through economic cycles."],
      ["Cocoa prices reached record highs, severely compressing chocolate margins.",
       "GLP-1 weight-loss drugs are a genuine long-term question for snacking volumes.",
       "Private label competition has intensified as consumers seek value."],
      "The cocoa cost shock dominates near-term discussion, though in September 2026 management raised its revenue outlook for the year while holding EPS guidance, choosing to reinvest the extra profit in marketing and distribution. Longer term, the GLP-1 debate splits opinion sharply.",
      "Cocoa cost hedging, pricing versus volume mix, emerging market growth, GLP-1 impact evidence.",
      (4, 2, 4, 4)),

    # ===================== ENERGY & MATERIALS =====================
    C("SLB", "SLB (Schlumberger Limited)", "energy", "Houston, Texas, USA", 1926,
      "Olivier Le Peuch", "NYSE", 40.00, 1.42, 10.0, 36.0,
      [0.05, 0.05, 0.05, 0.04, 0.04], 0.14, 0.17, 0.100, 0.024,
      "Founded in 1926 by brothers Conrad and Marcel Schlumberger, who pioneered electrical measurement of rock formations downhole. Olivier Le Peuch has been CEO since 2019. SLB is the largest oilfield services company in the world, providing the technology and expertise that oil companies use to find and produce hydrocarbons — seismic imaging, drilling, well completion and production optimisation. It sells to producers rather than owning reserves, so it is a bet on activity levels rather than on the oil price directly.",
      [("Well Construction", 33), ("Reservoir Performance", 25), ("Production Systems", 27), ("Digital & Integration", 15)],
      ["International and offshore markets, where SLB is strongest, have longer investment cycles than US shale.",
       "Digital and AI-enabled reservoir services carry far higher margins than traditional field work.",
       "Technological depth in complex deepwater and unconventional work creates real barriers."],
      ["Entirely dependent on customer capital spending, which collapses when oil prices fall.",
       "The energy transition creates long-term terminal value uncertainty that is hard to model.",
       "Operations in politically unstable regions carry contract and asset risk."],
      "Viewed as the highest-quality operator in oilfield services. The bear case is structural rather than company-specific.",
      "Third-quarter results on 23 October 2026, international rig counts, offshore project sanctions, digital revenue growth, Middle East activity including the Aramco well construction contracts.",
      (4, 3, 4, 4)),

    C("EOG", "EOG Resources, Inc.", "energy", "Houston, Texas, USA", 1985,
      "Ezra Yacob", "NYSE", 130.00, 0.55, -1.0, 24.0,
      [0.02, 0.03, 0.03, 0.03, 0.02], 0.25, 0.27, 0.095, 0.020,
      "Originally Enron Oil & Gas, separated from Enron in 1999 well before its collapse. Ezra Yacob has been CEO since 2021. EOG is one of the largest US independent oil and gas producers, concentrated in the Permian Basin, Eagle Ford and Delaware Basin. It built a reputation for capital discipline before the rest of the shale industry adopted it, focusing on returns per well rather than production growth — an approach that looked conservative for years and then looked prescient.",
      [("Crude Oil & Condensate", 66), ("Natural Gas Liquids", 17), ("Natural Gas", 17)],
      ["Among the lowest-cost producers in US shale, profitable at oil prices where competitors are not.",
   "A low-leverage balance sheet, with net debt of about $3.0 billion or 8.7% of total capitalisation at June 2026, which is unusual and valuable in a cyclical commodity business.",
   "A long record of capital discipline and returning cash rather than chasing volume growth."],
      ["Revenue is entirely driven by commodity prices the company cannot influence.",
       "US shale is a depleting resource base requiring continuous reinvestment to hold production flat.",
       "Regulatory and permitting risk on federal land and around emissions rules."],
      "Regarded as the best-managed US shale producer. Second-quarter 2026 results beat consensus, with $2.8 billion of free cash flow on a realised oil price of about $98 a barrel. The debate is about oil prices and inventory depth, not execution.",
      "Oil price realisations, well productivity, capital return announcements, inventory life, UAE exploration results.",
      (4, 2, 4, 4)),

    C("PSX", "Phillips 66", "energy", "Houston, Texas, USA", 2012,
      "Mark Lashier", "NYSE", 130.00, 0.41, 17.0, 145.0,
      [0.01, 0.02, 0.02, 0.02, 0.02], 0.035, 0.045, 0.095, 0.020,
      "Spun out of ConocoPhillips in 2012, though the Phillips name dates to 1917. Mark Lashier has been CEO since 2022. Phillips 66 refines crude oil into petrol, diesel and jet fuel, operates midstream pipelines and storage, markets fuel through branded stations, and holds a 50% stake in the CPChem petrochemicals joint venture. Refining economics depend on the crack spread — the gap between crude cost and refined product prices — which is volatile and outside management control.",
      [("Refining", 55), ("Midstream", 20), ("Marketing & Specialties", 19), ("Chemicals", 6)],
      ["Midstream and marketing provide steadier cash flow that partially offsets refining volatility.",
       "US refining capacity has been shrinking, which structurally supports crack spreads for survivors.",
       "Aggressive capital returns through buybacks and a substantial dividend."],
      ["Refining margins are extremely volatile and can swing the entire earnings profile in a quarter.",
       "Long-term fuel demand faces obvious pressure from vehicle electrification.",
       "Refineries are capital-intensive assets with significant maintenance and environmental liabilities."],
      "Sentiment has turned more positive as refining margins surged, with the realised margin reaching $24.08 per barrel in the second quarter of 2026 and the shares setting an all-time high above $274 in September. BMO raised its target to $310 in September 2026, pointing to momentum across the integrated portfolio and the midstream growth outlook.",
      "Third-quarter results on 28 October 2026, crack spreads, refinery utilisation, Western Gateway Pipeline progress, capital return pace.",
      (3, 2, 3, 3)),

    C("OXY", "Occidental Petroleum Corporation", "energy", "Houston, Texas, USA", 1920,
      "Richard Jackson", "NYSE", 48.00, 0.98, 25.0, 27.0,
      [0.02, 0.03, 0.03, 0.03, 0.02], 0.22, 0.25, 0.100, 0.020,
      "Founded in 1920 and built into a major by Armand Hammer. Richard Jackson was promoted to president and chief executive in 2026, succeeding Vicki Hollub, who had led the company since 2016 as the first woman to run a large US oil producer. Occidental produces oil and gas primarily in the Permian Basin, the Gulf of Mexico and the Middle East, and sold its OxyChem chemicals business to Berkshire Hathaway in a $9.7 billion deal completed at the start of 2026. Berkshire Hathaway holds a large stake. The company is also the most committed major to direct air capture, building carbon removal facilities in Texas.",
      [("Oil & Gas", 89), ("Midstream & Marketing", 11)],
      ["High-quality Permian acreage with low breakeven costs.",
   "Free cash flow before working capital reached $3.0 billion in the second quarter of 2026, the highest since the third quarter of 2022.",
   "Berkshire's continued accumulation is a meaningful signal of long-term confidence."],
      ["Leverage built up through the 2019 Anadarko acquisition and the 2024 CrownRock deal still matters, although principal debt fell to $11.8 billion in the second quarter of 2026.",
   "Direct air capture is capital-intensive and its economics remain unproven at scale.",
   "Preferred shares held by Berkshire carry an 8% dividend that consumes cash flow."],
      "Second-quarter 2026 production of 1,433 Mboed beat the top of guidance. With principal debt cut to $11.8 billion and management moving towards a $10 billion milestone, the debate is shifting from the balance sheet to free cash flow and capital returns.",
      "Third-quarter results on 9 November 2026, progress to the $10 billion debt milestone, Permian well productivity, carbon capture project milestones.",
      (3, 2, 2, 3)),

    C("DUK", "Duke Energy Corporation", "energy", "Charlotte, North Carolina, USA", 1904,
      "Harry Sideris", "NYSE", 125.00, 0.78, 83.0, 31.0,
      [0.05, 0.06, 0.06, 0.05, 0.05], 0.16, 0.19, 0.070, 0.024,
      "Traces to 1904 and the Catawba Power Company. Harry Sideris became CEO in 2025, succeeding Lynn Good. Duke Energy is one of the largest US regulated utilities, serving around 8.4 million electricity customers across the Carolinas, Florida, Indiana, Ohio and Kentucky. As a regulated monopoly it earns an authorised return on its invested capital base, which makes earnings unusually predictable — and makes capital investment, rather than sales growth, the main driver of profit.",
      [("Electric Utilities & Infrastructure", 89), ("Gas Utilities & Infrastructure", 8), ("Commercial Renewables & Other", 3)],
      ["Regulated monopoly with authorised returns produces highly predictable earnings.",
       "Data centre load growth in the Southeast is driving the strongest demand outlook in decades.",
       "Large capital expenditure programme grows the rate base, and with it earnings."],
      ["Very heavy debt load, and higher interest rates raise financing costs directly.",
       "Returns are set by state regulators, so political decisions cap the upside.",
       "Hurricane and storm exposure in the Carolinas and Florida creates recurring restoration costs."],
      "Held for the dividend and the data-centre demand story. Second-quarter 2026 adjusted EPS rose to $1.43 from $1.25, 2026 guidance of $6.55 to $6.80 was reaffirmed, and management expects to earn in the top half of its 5% to 7% growth range from 2028; regulatory outcomes and financing costs remain the main variables.",
      "Rate case outcomes, data centre load growth, capital plan updates, interest expense.",
      (4, 3, 2, 5)),

    C("SO", "The Southern Company", "energy", "Atlanta, Georgia, USA", 1945,
      "Christopher Womack", "NYSE", 95.00, 1.10, 62.0, 27.0,
      [0.05, 0.06, 0.06, 0.05, 0.05], 0.17, 0.20, 0.070, 0.024,
      "Founded in 1945. Christopher Womack has been CEO since 2023. Southern Company serves around 9 million customers across Georgia, Alabama and Mississippi through its regulated utilities. It completed Vogtle Units 3 and 4 in 2023 and 2024 — the first newly constructed nuclear reactors in the United States in over three decades, delivered years late and billions over budget, but now producing carbon-free baseload power exactly as data centre demand accelerates in Georgia.",
      [("Alabama Power", 27), ("Georgia Power", 42), ("Southern Power & Gas", 31)],
      ["Vogtle gives Southern the largest nuclear generating capacity of any US utility, valuable for carbon-free baseload.",
   "Georgia regulators approved in August 2026 a contract to serve OpenAI's 3,200 MW Effingham County project, with OpenAI paying the full infrastructure costs.",
   "Constructive regulatory relationships in its core states."],
      ["Vogtle's cost overruns were severe and the recovery has been contentious with regulators.",
       "High leverage in a higher-rate environment.",
       "Nuclear operations carry low-probability but high-severity risk."],
      "The data centre demand narrative in Georgia remains the dominant bull argument, reinforced by the approved OpenAI contract and a September 2026 nuclear uprate agreement with Google. Bears focus on leverage and regulatory lag.",
      "Third-quarter results on 5 November 2026, PSC decision on the Google nuclear uprate agreement, Georgia load growth, Vogtle operating performance.",
      (4, 3, 2, 5)),

    # ===================== INDUSTRIALS & DEFENCE =====================
    C("UNP", "Union Pacific Corporation", "industrials", "Omaha, Nebraska, USA", 1862,
      "Jim Vena", "NYSE", 240.00, 0.60, 31.0, 24.5,
      [0.04, 0.05, 0.05, 0.04, 0.04], 0.24, 0.28, 0.080, 0.025,
      "Chartered by Congress in 1862 to build the eastern portion of the first transcontinental railroad. Jim Vena became CEO in 2023. Union Pacific operates around 32,000 route miles across the western two-thirds of the United States, hauling coal, grain, chemicals, industrial products and intermodal containers. It has agreed to acquire Norfolk Southern in an $85 billion deal that would add an eastern network; the transaction is under Surface Transportation Board review, with completion expected in the second half of 2027. Railroads are close to un-replicable — no one is building a competing transcontinental network — which gives the industry unusual structural pricing power.",
      [("Bulk", 33), ("Industrial", 36), ("Premium & Intermodal", 31)],
      ["The rail network is a genuinely irreplaceable asset with enormous barriers to entry.",
       "Rail is substantially more fuel-efficient than trucking, a structural cost and emissions advantage.",
       "Precision scheduled railroading has delivered real and durable margin improvement."],
      ["Volumes track industrial production and are cyclical.",
   "Coal, historically a major freight category, is in permanent structural decline.",
   "The $85 billion Norfolk Southern acquisition still needs Surface Transportation Board approval and faces organised opposition, and service problems during any integration would draw regulatory intervention."],
      "The pending Norfolk Southern acquisition now dominates the debate. The Surface Transportation Board unanimously rejected requests to dismiss the revised application in September 2026, keeping the review on course for a targeted close in the second half of 2027, while the companies point to about $1 billion of annual operating savings.",
      "Third-quarter results on 22 October 2026, Surface Transportation Board review of the Norfolk Southern merger, carload volumes, operating ratio.",
      (5, 3, 4, 5)),

    C("UPS", "United Parcel Service, Inc.", "industrials", "Atlanta, Georgia, USA", 1907,
      "Carol Tomé", "NYSE", 98.00, 0.85, 20.0, 91.0,
      [0.01, 0.03, 0.04, 0.04, 0.03], 0.075, 0.10, 0.085, 0.024,
      "Founded in 1907 in Seattle as a messenger service by 19-year-old Jim Casey. Carol Tomé, previously Home Depot's finance chief, became CEO in 2020. UPS operates one of the largest package delivery networks in the world, with its own airline and a vast ground fleet. Its strategy under Tomé has been 'better not bigger' — deliberately shedding low-margin volume, including deliberately reducing its Amazon business, in favour of higher-yielding healthcare and small business shipments.",
      [("US Domestic Package", 68), ("International Package", 19), ("Supply Chain Solutions", 13)],
      ["An integrated global network that would cost an enormous amount to replicate.",
       "Healthcare logistics is a high-margin, high-growth segment where UPS is investing heavily.",
       "Deliberately reducing Amazon volume improves the average margin per package."],
      ["Volume declines have been steeper than the margin improvement has offset.",
       "The 2023 Teamsters contract substantially raised the cost base ahead of the volume recovery.",
       "Amazon's own logistics network keeps expanding and competes directly."],
      "One of the more contested industrials. With the Amazon volume glide-down and network reconfiguration completed in June 2026 and a new global operating model in place from September, attention is moving to whether yield gains and healthcare growth can restore earnings; bears still point to structural volume loss.",
      "US domestic revenue per piece, healthcare revenue growth, cost per piece, peak-season performance, third-quarter results.",
      (3, 2, 3, 4)),

    C("ETN", "Eaton Corporation plc", "industrials", "Dublin, Ireland", 1911,
      "Paulo Ruiz", "NYSE", 365.00, 0.39, 8.0, 25.5,
      [0.09, 0.09, 0.08, 0.07, 0.06], 0.17, 0.21, 0.085, 0.028,
      "Founded in 1911 in Bloomfield, New Jersey, making truck axles. Paulo Ruiz became CEO in 2025, succeeding Craig Arnold. Eaton makes electrical power management equipment — switchgear, circuit protection, power distribution units and backup systems. It has become one of the clearest beneficiaries of data centre construction, because every megawatt of computing capacity requires substantial electrical infrastructure to deliver, distribute and protect power. It bought Boyd Thermal for $9.55 billion in March 2026 and has agreed to separate its Vehicle and eMobility businesses through a Reverse Morris Trust with Dana, expected to close in the first quarter of 2027.",
      [("Electrical Americas", 47), ("Electrical Global", 24), ("Aerospace", 14), ("Vehicle & eMobility", 15)],
      ["Data centre electrical demand is growing faster than almost any other industrial end market.",
       "Grid modernisation and electrification create a multi-year structural investment cycle.",
       "Record backlog gives unusual revenue visibility for an industrial company."],
      ["A meaningful share of the valuation now rests on data centre capital spending continuing.",
   "Vehicle and eMobility remain exposed to a slower-than-expected EV transition until the planned Reverse Morris Trust with Dana, expected in the first quarter of 2027, is completed.",
   "The stock has re-rated substantially, so expectations are high."],
      "Widely held as a way to own AI infrastructure outside semiconductors. The bear argument is valuation and capex concentration.",
      "Electrical segment orders, data centre backlog, book-to-bill ratio, Mobility separation with Dana in the first quarter of 2027, COL Group acquisition close.",
      (5, 4, 4, 4)),

    C("EMR", "Emerson Electric Co.", "industrials", "St. Louis, Missouri, USA", 1890,
      "Lal Karsanbhai", "NYSE", 135.00, 0.57, 8.0, 18.0,
      [0.05, 0.06, 0.06, 0.05, 0.05], 0.17, 0.21, 0.085, 0.026,
      "Founded in 1890 as Emerson Electric Manufacturing, originally making electric motors and fans. Lal Karsanbhai has been CEO since 2021 and has reshaped the company into a pure-play automation business, divesting the climate technologies unit and acquiring control of National Instruments and Aspen Technology. Emerson sells the control systems, measurement instruments and software that run industrial processes in refineries, chemical plants and factories.",
      [("Final Control", 25), ("Measurement & Analytical", 26), ("Discrete Automation", 15), ("Control Systems & Software", 20), ("AspenTech", 14)],
      ["Automation demand is supported by reshoring, labour scarcity and energy transition capital spending.",
       "Installed base of control systems generates recurring aftermarket and service revenue.",
       "The portfolio reshaping has meaningfully raised the quality of the earnings mix."],
      ["Process automation spending follows the capital cycles of energy and chemicals customers.",
       "Integrating AspenTech and National Instruments carries execution risk.",
       "Competes against Siemens, ABB, Schneider and Honeywell, all formidable."],
      "Seen as a well-executed portfolio transformation. Management raised its fiscal 2026 outlook in August 2026 to adjusted EPS of about $6.55 and free cash flow of about $3.6 billion, with around $1 billion of buybacks planned for the year; debate remains about the durability of the automation capital cycle.",
      "Fiscal 2026 fourth-quarter results and 2027 guidance, underlying orders growth, AspenTech performance, backlog conversion.",
      (4, 3, 4, 4)),

    C("GD", "General Dynamics Corporation", "industrials", "Reston, Virginia, USA", 1952,
      "Phebe Novakovic", "NYSE", 320.00, 0.27, 8.0, 48.0,
      [0.06, 0.06, 0.05, 0.05, 0.04], 0.08, 0.10, 0.080, 0.024,
      "Formed in 1952, with roots in the Electric Boat Company founded in 1899. Phebe Novakovic has been CEO since 2013; in October 2026 the board elected president Danny Deep to succeed her on 1 January 2027, when she becomes executive chairman. General Dynamics builds nuclear submarines through Electric Boat, combat vehicles including the Abrams tank, and IT systems for government — and separately owns Gulfstream, the business jet manufacturer. That combination of defence and luxury aviation is unique among the primes and gives it a quite different profile from Lockheed or Northrop.",
      [("Aerospace (Gulfstream)", 25), ("Marine Systems", 29), ("Combat Systems", 18), ("Technologies", 28)],
      ["Submarine construction is a sole-source capability with a decades-long backlog under the Columbia and Virginia programmes.",
       "AUKUS and the broader naval build-out support demand well beyond the current decade.",
       "Gulfstream provides commercial diversification the other defence primes lack."],
      ["Submarine production has faced well-documented supply chain and workforce constraints causing delays.",
       "Business jet demand is cyclical and tied to corporate profits and high-net-worth wealth.",
       "Fixed-price defence contracts expose the company to cost inflation it cannot pass on."],
      "Viewed favourably for the submarine backlog. Execution on production rates and Gulfstream deliveries drives most of the variance.",
      "CEO transition to Danny Deep on 1 January 2027, submarine delivery schedules, Gulfstream order book and deliveries, defence budget outcomes, backlog.",
      (4, 3, 4, 5)),

    C("NOC", "Northrop Grumman Corporation", "industrials", "Falls Church, Virginia, USA", 1939,
      "Kathy Warden", "NYSE", 570.00, 0.145, 14.0, 41.0,
      [0.05, 0.05, 0.05, 0.04, 0.04], 0.075, 0.095, 0.080, 0.024,
      "Formed by the 1994 merger of Northrop, founded 1939, and Grumman. Kathy Warden has been CEO since 2019. Northrop's most important programme is the B-21 Raider, the next-generation stealth bomber, alongside the Sentinel intercontinental ballistic missile programme that will replace the ageing Minuteman III. It also has a large space business. The company is concentrated in exactly the areas the US is prioritising for nuclear modernisation.",
      [("Aeronautics Systems", 28), ("Space Systems", 27), ("Mission Systems", 27), ("Defense Systems", 18)],
      ["The B-21 and Sentinel programmes represent decades of committed government spending.",
       "Nuclear triad modernisation has unusually strong bipartisan political support.",
       "Deep classified programme portfolio that competitors cannot easily contest."],
      ["The B-21 is a fixed-price development contract and has already produced significant charges.",
       "Sentinel has faced major cost overruns and a Nunn-McCurdy breach review.",
       "Heavy dependence on the US government means budget politics drive the business."],
      "The strategic position is well regarded; the concern is margin risk on fixed-price development work. Missile defence has become an added support after Northrop signed framework agreements worth more than $3 billion in August 2026 to supply PAC-3 MSE and THAAD rocket motors and components.",
      "Third-quarter results on 20 October 2026, B-21 production milestones and charges, Sentinel flight test in 2027, defence budget appropriations, free cash flow.",
      (4, 3, 3, 5)),

    # ===================== TELECOM & MEDIA =====================
    C("T", "AT&T Inc.", "telecom", "Dallas, Texas, USA", 1885,
      "John Stankey", "NYSE", 29.00, 7.20, 120.0, 123.0,
      [0.02, 0.02, 0.02, 0.02, 0.02], 0.14, 0.17, 0.075, 0.020,
      "Traces to the American Telephone and Telegraph Company incorporated in 1885. John Stankey has been CEO since 2020. After an expensive and unsuccessful diversification into media — DirecTV and Time Warner, both since divested — AT&T has refocused entirely on connectivity: wireless service for around 118 million subscribers and a fibre broadband build targeting more than 60 million locations by the end of 2030, helped by fibre assets bought from Lumen in February 2026. The strategy is now deliberately unglamorous and the market has responded better to that than to the media era.",
      [("Mobility", 66), ("Business Wireline", 17), ("Consumer Wireline", 14), ("Other", 3)],
      ["Fibre broadband has better economics and lower churn than the copper and cable it replaces.",
       "Wireless is a rational three-player market with disciplined pricing.",
       "Free cash flow comfortably covers a dividend yielding well above the market."],
      ["An extremely large debt load built up during the media acquisition era.",
       "Wireless subscriber growth is essentially a share-shift game in a saturated market.",
       "Fibre construction is capital-intensive with long payback periods."],
      "An income holding where the story is deleveraging and fibre returns. In October 2026 AT&T agreed to place the Lumen fibre assets into a 50/50 wholesale joint venture with GIP and CPP Investments, with proceeds at closing earmarked for reaching net debt of about 2.5 times adjusted EBITDA within roughly three years.",
      "Third-quarter results, fibre joint venture closing in the first half of 2027, postpaid phone net additions, net debt reduction, CFO succession.",
      (3, 2, 2, 4)),

    C("VZ", "Verizon Communications Inc.", "telecom", "New York, New York, USA", 1983,
      "Dan Schulman", "NYSE", 44.00, 4.21, 145.0, 134.0,
      [0.02, 0.02, 0.02, 0.02, 0.02], 0.13, 0.16, 0.075, 0.020,
      "Formed in 2000 from Bell Atlantic, itself created in the 1983 AT&T breakup. Dan Schulman, previously CEO of PayPal, took over in October 2025. Verizon operates the largest US wireless network by subscribers and has historically positioned on network quality at premium prices. It has been slower than competitors to grow subscribers and is pushing fixed wireless access — using spare 5G capacity to deliver home broadband — as its main growth vector.",
      [("Consumer", 76), ("Business", 23), ("Other", 1)],
      ["Network quality reputation supports premium pricing and low churn among high-value customers.",
       "Fixed wireless broadband monetises existing spectrum with very little incremental capital.",
       "The dividend yield is among the highest in the S&P 500 and has been raised annually for years."],
      ["The heaviest debt burden of the three major US carriers.",
       "Consistently weaker postpaid phone subscriber growth than T-Mobile.",
       "Very large spectrum purchases have not yet translated into commensurate returns."],
      "Held primarily for income. New leadership from outside telecom is the main new variable in the story.",
      "Postpaid phone net additions, fixed wireless subscriber growth, free cash flow, strategic direction under new leadership.",
      (3, 2, 2, 4)),

    C("TMUS", "T-Mobile US, Inc.", "telecom", "Bellevue, Washington, USA", 1994,
      "Srini Gopalan", "Nasdaq", 240.00, 1.14, 78.0, 82.0,
      [0.04, 0.04, 0.04, 0.03, 0.03], 0.18, 0.22, 0.080, 0.024,
      "Traces to VoiceStream Wireless, acquired by Deutsche Telekom in 2001. Srini Gopalan became CEO in November 2025, succeeding Mike Sievert. The 2020 Sprint merger transformed T-Mobile from a distant third to a genuine scale competitor, and crucially handed it a deep mid-band spectrum position that let it build 5G coverage faster than either rival. It has taken subscriber share consistently ever since, and the 'Un-carrier' positioning still resonates.",
      [("Postpaid Services", 62), ("Prepaid Services", 8), ("Equipment & Other", 30)],
      ["The best mid-band 5G spectrum position in the US, which translated into a real coverage lead.",
       "Consistently the strongest subscriber growth of the three major carriers.",
       "Sprint merger synergies have exceeded original targets."],
      ["Sprint integration synergies are largely realised, so that earnings tailwind is ending.",
   "Growth increasingly depends on fixed wireless and rural expansion rather than core share gains, and management expects higher account churn while it migrates customers off legacy rate plans.",
   "Deutsche Telekom's majority ownership limits governance independence."],
      "Still regarded as the best-executing US carrier, but sentiment has cooled: the shares hit a one-year low of about $166 in September 2026, down 17% for the year, as management deliberately slowed account growth while modernising legacy plans. Investors are also weighing spectrum auction spending in 2027 and 2028 and a CFO handover to Jessica Uhl.",
      "Third-quarter results on 28 October 2026, postpaid net account additions, fixed wireless growth, CFO transition, spectrum auction spending.",
      (4, 3, 3, 4)),

    C("CMCSA", "Comcast Corporation", "telecom", "Philadelphia, Pennsylvania, USA", 1963,
      "Brian Roberts and Mike Cavanagh (co-CEOs)", "Nasdaq", 34.00, 3.75, 92.0, 124.0,
      [0.0, 0.01, 0.02, 0.02, 0.02], 0.15, 0.18, 0.080, 0.020,
      "Founded in 1963 by Ralph Roberts, whose son Brian Roberts has been CEO since 2002 and has shared the role with co-CEO Mike Cavanagh since January 2026. Comcast is the largest US cable broadband provider and owns NBCUniversal — the broadcast network, Universal film studio, theme parks and the Peacock streaming service. It completed the spin-off of Versant Media Group in January 2026, and the Epic Universe park opened in Orlando in 2025. Its central problem is that broadband, the profit engine, has stopped growing as fixed wireless and fibre competitors take share.",
      [("Residential Connectivity", 44), ("Business Services", 10), ("Media", 20), ("Studios", 9), ("Theme Parks", 8), ("Sky", 9)],
      ["Broadband remains a high-margin, essential service with substantial infrastructure barriers.",
       "Theme parks are irreplaceable assets and Epic Universe is a major new capacity addition.",
       "The content library and studio have real value in a consolidating media landscape."],
      ["Broadband subscriber losses to fixed wireless and fibre have become persistent rather than temporary.",
       "Peacock loses money and lacks the scale of Netflix or Disney+.",
       "Traditional cable television subscriptions continue to decline every quarter."],
      "A value case complicated by broadband competition. Bulls point to the parks and cash flow; bears to subscriber erosion.",
      "Broadband net additions, Peacock subscribers and losses, Epic Universe attendance, capital returns.",
      (3, 1, 3, 4)),

    C("DIS", "The Walt Disney Company", "telecom", "Burbank, California, USA", 1923,
      "Josh D'Amaro", "NYSE", 118.00, 1.81, 38.0, 94.0,
      [0.04, 0.05, 0.05, 0.04, 0.04], 0.11, 0.15, 0.085, 0.025,
      "Founded in 1923 by Walt and Roy Disney. Josh D'Amaro, who previously ran the parks business, succeeded Bob Iger as CEO in March 2026. Disney owns the most valuable collection of intellectual property in entertainment — Disney animation, Pixar, Marvel, Star Wars and National Geographic — and monetises it through films, streaming, television, consumer products and theme parks. The parks and experiences division is by far the largest profit contributor.",
      [("Experiences (Parks & Products)", 38), ("Entertainment", 42), ("Sports (ESPN)", 20)],
      ["An intellectual property portfolio with no real equivalent anywhere in media.",
   "Theme parks are extremely profitable and effectively impossible to replicate.",
   "Streaming is now solidly profitable, with Entertainment SVOD operating income of $712 million in the third quarter of fiscal 2026, up from $329 million a year earlier."],
      ["Linear television networks are in structural decline and still represent meaningful profit.",
   "ESPN's transition to direct-to-consumer risks accelerating cable subscriber losses, and Sports operating income fell 17% in the third quarter of fiscal 2026.",
   "A new chief executive is still reshaping the leadership team, adding a chief technology officer and a new head of direct-to-consumer in September 2026, so execution of his strategy is untested."],
      "Debate centres on whether streaming and parks growth can outrun linear decline under new chief executive Josh D'Amaro. Third-quarter fiscal 2026 adjusted EPS rose 28%, Experiences operating income rose 20% and the buyback target was raised to at least $9 billion, with management guiding to double-digit adjusted EPS growth in fiscal 2027.",
      "Fiscal fourth-quarter results and 2027 outlook, streaming subscriber and margin trends, park attendance and per-capita spending, ESPN direct-to-consumer performance.",
      (5, 3, 3, 5)),
]
