"""Expansion coverage, part three — companies 201 to 234.

All US-listed, so every price and chart comes from the Yahoo pipeline that
now drives the site. Sanofi and GSK are included via their US ADR lines, which
Yahoo covers under their plain tickers.

Still deliberately excluded: REITs. Prologis, American Tower, Equinix and
Welltower are all large enough to belong here, but real estate is valued on
funds from operations rather than free cash flow. Running them through the
standard DCF would produce numbers that look precise and mean nothing. They
need their own treatment.

Prices below are starting values only — the first run overwrites them.
Revenue, share count and net debt are modelling inputs and are refreshed
separately by fetch_fundamentals.py.
"""

from companies.schema import C

EXPANSION3 = [

    # ===================== SEMICONDUCTORS =====================
    C("AMKR", "Amkor Technology, Inc.", "semis", "Tempe, Arizona, USA", 1968,
      "Giel Rutten", "Nasdaq", 32.00, 0.246, 0.2, 6.3,
      [0.08, 0.10, 0.09, 0.08, 0.07], 0.09, 0.13, 0.105, 0.026,
      "Founded in 1968 by James Kim, initially assembling chips in South Korea for US semiconductor companies. Giel Rutten has been CEO since 2020. Amkor packages and tests finished silicon — the step between a wafer leaving the fab and a usable chip. Advanced packaging has become strategically important because stacking chips together is now one of the main ways to improve performance as transistor shrinks slow down.",
      [("Communications", 40), ("Automotive & Industrial", 22), ("Computing", 21), ("Consumer", 17)],
      ["Advanced packaging is a genuine bottleneck in AI hardware production and demand exceeds capacity.",
   "One of only a handful of outsourced assembly and test providers at real scale.",
   "The Arizona campus aligns with US reshoring incentives, and customer commitments led Amkor to add a second phase in September 2026, lifting planned investment to about $12 billion."],
      ["Packaging is far more commoditised than chip design, so margins are structurally thin.",
       "Heavy customer concentration, with Apple historically a very large share of revenue.",
       "Capital intensive: new capacity requires spending well ahead of the revenue it serves."],
      "Regarded as a way to own AI packaging demand at a much lower multiple than the chip designers, with the discount reflecting genuinely weaker economics.",
      "Third-quarter results on 26 October 2026, advanced packaging utilisation, Arizona phase 2 plans, customer concentration, capex guidance.",
      (3, 4, 3, 3)),

    C("ON", "ON Semiconductor Corporation", "semis", "Scottsdale, Arizona, USA", 1999,
      "Hassane El-Khoury", "Nasdaq", 52.00, 0.42, 1.5, 6.6,
      [0.06, 0.10, 0.09, 0.08, 0.07], 0.20, 0.26, 0.105, 0.028,
      "Spun out of Motorola in 1999. Hassane El-Khoury became CEO in 2020 and deliberately exited large volumes of low-margin commodity business to focus on silicon carbide power devices and image sensors. Silicon carbide handles high voltages far more efficiently than conventional silicon, which makes it central to electric vehicle powertrains and industrial power conversion.",
      [("Power Solutions", 50), ("Analog & Mixed Signal", 32), ("Intelligent Sensing", 18)],
      ["Silicon carbide content per electric vehicle is high and ON is one of the few suppliers at scale.",
       "The deliberate exit from commodity business structurally raised gross margin.",
       "Long-term supply agreements with major automakers provide visibility."],
      ["Electric vehicle adoption has slowed relative to the forecasts this strategy was built on.",
       "Chinese silicon carbide suppliers are adding capacity aggressively and pricing hard.",
       "Automotive and industrial inventory corrections have been prolonged."],
      "The silicon carbide thesis is intact but the timeline has stretched. Revenue returned to growth in the second quarter of 2026, up 9% to $1.60 billion, and investors are now also weighing the all-cash Synaptics acquisition, cut to about $5.7 billion in October 2026.",
      "Third-quarter results, Synaptics shareholder and regulatory approvals, silicon carbide revenue growth, automotive design wins, gross margin, inventory levels.",
      (4, 3, 3, 4)),

    C("SWKS", "Skyworks Solutions, Inc.", "semis", "Irvine, California, USA", 1962,
      "Philip Brace", "Nasdaq", 68.00, 0.152, -0.5, 4.1,
      [0.03, 0.05, 0.05, 0.04, 0.04], 0.26, 0.29, 0.100, 0.024,
      "Traces to Alpha Industries, founded 1962, taking its current form in 2002. Philip Brace became CEO in 2025. Skyworks makes radio frequency front-end components — the filters, amplifiers and switches that let a phone connect to cellular networks. In October 2026 it completed a cash-and-stock combination with former direct competitor Qorvo, whose shareholders now own about 37% of the enlarged company. Apple is by far its largest customer, which is both the reason for its scale and its central vulnerability.",
      [("Mobile", 62), ("Broad Markets", 38)],
      ["Radio frequency content per phone rises with each new cellular band and standard.",
       "Deep, long-standing engineering relationships with the largest handset makers.",
       "Strong free cash flow generation and a consistent dividend."],
      ["Apple represents a very large share of revenue and has been developing in-house alternatives.",
   "Smartphone unit volumes are mature and no longer growing.",
   "Integrating Qorvo, completed in October 2026, is a large execution task, and Broadcom still competes directly for the same sockets."],
      "The Apple concentration dominates every conversation. With the Qorvo combination closed on 5 October 2026, attention turns to integration and the first guidance for the enlarged company on 3 November.",
      "Fiscal fourth-quarter results and guidance on 3 November 2026, Qorvo integration, Apple content per device, broad markets growth, smartphone unit forecasts.",
      (3, 2, 4, 3)),

    C("ENTG", "Entegris, Inc.", "semis", "Billerica, Massachusetts, USA", 1966,
      "Bertrand Loy", "Nasdaq", 95.00, 0.152, 3.8, 3.4,
      [0.09, 0.11, 0.10, 0.09, 0.08], 0.16, 0.22, 0.100, 0.028,
      "Formed from a 2005 merger, with roots to 1966. Bertrand Loy has been CEO since 2012. Entegris supplies the materials and contamination-control products used inside semiconductor fabs — specialty chemicals, filters, wafer handling systems. As chip features shrink, tolerance for contamination approaches zero, which makes these unglamorous products increasingly critical and increasingly specified.",
      [("Materials Solutions", 45), ("Microcontamination Control", 35), ("Advanced Materials Handling", 20)],
      ["Consumable products tied to wafer starts, so revenue tracks fab output rather than equipment cycles.",
       "Contamination tolerance falls with every node shrink, which raises content per wafer.",
       "Products are specified into customer processes, making substitution slow and risky."],
      ["Wafer start volumes are cyclical and fell sharply in the memory downturn.",
   "China restrictions limit access to a meaningful part of the market.",
   "Debt from the CMC Materials acquisition remains elevated, although $200 million was repaid in the second quarter of 2026."],
      "Viewed as a quality consumables business leveraged to the semiconductor cycle rather than to any single chipmaker. Second-quarter 2026 revenue rose about 11% to $883 million, and third-quarter guidance of $905–935 million points to a continuing recovery.",
      "Third-quarter results on 29 October 2026, investor day on 9 November 2026, wafer start trends, content per wafer, China policy, debt reduction.",
      (5, 4, 3, 4)),

    C("STX", "Seagate Technology Holdings plc", "semis", "Fremont, California, USA", 1978,
      "Dave Mosley", "Nasdaq", 175.00, 0.212, 4.5, 9.1,
      [0.14, 0.12, 0.09, 0.07, 0.06], 0.18, 0.24, 0.110, 0.022,
      "Founded in 1979 by Al Shugart and Finis Conner. Dave Mosley has been CEO since 2017. Seagate makes hard disk drives, and although solid state storage replaced spinning disks in consumer devices years ago, HDDs remain far cheaper per terabyte at scale — which is why cloud providers still buy them in enormous volumes for bulk storage. AI workloads generate vast quantities of data that has to live somewhere affordable.",
      [("Mass Capacity Storage", 82), ("Legacy & Other", 18)],
      ["Cost per terabyte remains dramatically below flash, which keeps HDDs essential for cloud bulk storage.",
       "Effectively a duopoly with Western Digital, and both have shown pricing discipline.",
       "HAMR technology raises areal density substantially and Seagate is furthest along."],
      ["Structurally declining unit volumes, offset only by rising capacity per drive.",
       "Flash prices falling faster than expected would compress the cost advantage.",
       "Very high customer concentration among a few hyperscalers."],
      "A cyclical recovery story with a structural decline underneath it. HAMR execution is the swing factor.",
      "Exabytes shipped, HAMR qualification progress, cloud order patterns, pricing per terabyte.",
      (3, 3, 3, 3)),

    C("WDC", "Western Digital Corporation", "semis", "San Jose, California, USA", 1970,
      "Irving Tan", "Nasdaq", 118.00, 0.35, 5.5, 9.5,
      [0.13, 0.11, 0.09, 0.07, 0.06], 0.16, 0.22, 0.110, 0.022,
      "Founded in 1970. Irving Tan became CEO in 2025 after Western Digital separated its flash memory business, leaving the company focused on hard disk drives. That separation was the culmination of years of pressure to split two businesses with very different economics and capital requirements.",
      [("Cloud", 72), ("Client", 18), ("Consumer", 10)],
      ["The flash separation leaves a simpler, more focused business easier for investors to value.",
       "Cloud demand for high-capacity drives is growing with AI data generation.",
       "Duopoly pricing dynamics with Seagate."],
      ["Same structural unit decline as the rest of the HDD industry.",
       "Behind Seagate on next-generation areal density technology.",
       "Newly separated company with an unproven standalone track record."],
      "Bracketed with Seagate but generally viewed as the weaker of the two on technology roadmap. Fiscal fourth-quarter 2026 revenue rose 44% to $3.75 billion and first-quarter fiscal 2027 guidance of about $4.1 billion implies 42–49% growth, so near-term cloud demand is not the concern.",
      "Fiscal first-quarter 2027 results, exabytes shipped, cloud demand, gross margin, technology transition progress, capital returns.",
      (3, 3, 3, 3)),

    # ===================== SOFTWARE & INTERNET =====================
    C("NET", "Cloudflare, Inc.", "software", "San Francisco, California, USA", 2009,
      "Matthew Prince", "NYSE", 273.04, 0.35, -1.0, 2.1,
      [0.28, 0.25, 0.21, 0.18, 0.15], 0.10, 0.24, 0.115, 0.032,
      "Founded in 2009 by Matthew Prince, Lee Holloway and Michelle Zatlyn out of a Harvard Business School project. Prince still runs it. Cloudflare operates a global network sitting between websites and their visitors, providing security, performance acceleration and increasingly compute. Its edge network spans hundreds of cities, which lets it run code close to users rather than in distant data centres.",
      [("Application Services", 78), ("Network Services", 15), ("Developer & Other", 7)],
      ["The edge network is genuinely difficult to replicate and gets more valuable as it grows.",
       "Workers gives it a credible position in edge compute, a market the hyperscalers are less suited to.",
       "Large enterprise customer count growing quickly with strong net retention."],
      ["Still lossmaking on a GAAP basis with high stock-based compensation.",
       "Competes against Akamai, Fastly and the security arms of every major cloud provider.",
       "A demanding valuation that assumes many years of high growth."],
      "Widely admired product and network; the argument is almost entirely about the multiple.",
      "Large customer additions, net revenue retention, Workers adoption, path to GAAP profitability.",
      (5, 5, 4, 4)),

    C("TEAM", "Atlassian Corporation", "software", "Sydney, Australia", 2002,
      "Mike Cannon-Brookes", "Nasdaq", 180.00, 0.26, -1.2, 5.2,
      [0.19, 0.17, 0.15, 0.13, 0.11], 0.20, 0.27, 0.105, 0.030,
      "Founded in 2002 in Sydney by Mike Cannon-Brookes and Scott Farquhar, funded initially on credit cards. Cannon-Brookes is now sole CEO. Atlassian makes Jira and Confluence, the issue tracking and documentation tools that a large share of software teams run on. Its unusual history is that it grew for years with essentially no sales force, relying on developers adopting the tools themselves.",
      [("Subscription", 92), ("Maintenance & Other", 8)],
      ["Jira is deeply embedded in engineering workflows and migrating off it is genuinely painful.",
       "Bottom-up adoption keeps customer acquisition costs far below enterprise software norms.",
       "The cloud migration from server licences is largely complete and lifted recurring revenue."],
      ["Growth depends heavily on software engineering headcount, which has been cut across the industry.",
       "Linear, Notion and others compete for the same teams with more modern interfaces.",
       "Free tiers mean a large share of users generate no revenue."],
      "Considered a durable franchise facing a slower hiring environment. Fiscal 2026 ended with fourth-quarter revenue up 28% and cloud up 31%, but guidance for about 13% total revenue growth in fiscal 2027 points to a sharp deceleration, and the CEO's plan to buy up to $250 million of stock is read as a show of confidence.",
      "Fiscal first-quarter 2027 results, cloud revenue growth, AI and agentic product adoption, paid seat expansion, enterprise deal count, engineering hiring trends.",
      (5, 4, 4, 5)),

    C("VEEV", "Veeva Systems Inc.", "software", "Pleasanton, California, USA", 2007,
      "Peter Gassner", "NYSE", 265.00, 0.164, -1.0, 2.9,
      [0.15, 0.14, 0.13, 0.11, 0.10], 0.30, 0.35, 0.095, 0.030,
      "Founded in 2007 by Peter Gassner, previously at Salesforce, who still runs it. Veeva sells cloud software exclusively to life sciences companies — customer relationship management for pharmaceutical sales teams, plus clinical trial and regulatory document management. Building only for one heavily regulated industry means the software handles compliance requirements generic vendors do not attempt.",
      [("Commercial Solutions", 45), ("R&D Solutions", 55)],
      ["Near-total focus on life sciences creates domain depth competitors cannot easily match.",
       "Regulated document workflows have very high switching costs once validated.",
       "Almost every large pharmaceutical company is already a customer, and they expand steadily."],
      ["A relatively finite customer universe — there are only so many large drug companies.",
       "Salesforce, its former platform partner, has become a direct competitor.",
       "Pharmaceutical R&D budget pressure flows through to software spend."],
      "Regarded as a high-quality vertical software business with a naturally bounded market. Fiscal second-quarter revenue rose 18% to $928 million, management raised its full-year outlook, and Vault CRM had what the CEO called its best quarter ever.",
      "Fiscal third-quarter results, Vault CRM wins among top-20 biopharma, R&D solutions adoption, AI product adoption, competitive displacements.",
      (5, 4, 5, 5)),

    C("ADP", "Automatic Data Processing, Inc.", "software", "Roseland, New Jersey, USA", 1949,
      "Maria Black", "Nasdaq", 290.00, 0.405, 1.5, 20.5,
      [0.06, 0.06, 0.06, 0.05, 0.05], 0.22, 0.25, 0.080, 0.026,
      "Founded in 1949 by Henry Taub as a manual payroll processing service. Maria Black has been CEO since 2023. ADP runs payroll for a very large share of American workers, and its monthly employment report is watched as an economic indicator in its own right. Beyond payroll it sells human resources outsourcing, benefits administration and compliance services.",
      [("Employer Services", 68), ("Professional Employer Organisation", 32)],
      ["Payroll is the single stickiest enterprise system there is — switching risks paying people incorrectly.",
       "Earns float income on client funds held between collection and disbursement, which rises with rates.",
       "Scale advantages in navigating tax and compliance rules across every jurisdiction."],
      ["Revenue tracks employment levels, so a recession reduces both clients and employees per client.",
       "Workday and Paycom compete hard at the larger end of the market.",
       "Growth is steady but structurally low single digit."],
      "A classic defensive compounder. Employment trends and interest rates on client float drive most of the variance.",
      "Pays per control, client retention, float income, employment growth data.",
      (5, 3, 5, 5)),

    C("FISV", "Fiserv, Inc.", "software", "Milwaukee, Wisconsin, USA", 1984,
      "Takis Georgakopoulos", "Nasdaq", 50.35, 0.55, 24.0, 20.5,
      [0.07, 0.07, 0.06, 0.06, 0.05], 0.22, 0.26, 0.090, 0.026,
      "Founded in 1984. Takis Georgakopoulos became chief executive in June 2026, promoted from co-president after Mike Lyons left abruptly for Truist eighteen months into the job. The shares fell over 8% on the announcement and are down more than 70% over the year, so this is a turnaround with the credibility of its own targets in question. Fiserv provides the core banking software that thousands of smaller US banks and credit unions run on, plus Clover, a point-of-sale system for small merchants that has become the growth engine. Core banking systems are famously difficult to replace — many run on decades-old architecture precisely because migration risk is so high.",
      [("Merchant Solutions", 43), ("Financial Solutions", 40), ("Corporate & Other", 17)],
      ["Core banking contracts run for many years and switching is a multi-year project banks rarely undertake.",
       "Clover has taken meaningful share in small business point-of-sale against Square.",
       "Payment volumes grow with nominal consumer spending regardless of unit growth."],
      ["Substantial debt taken on through years of acquisitions.",
       "Small business formation and health drive Clover, making it economically sensitive.",
       "Fintech entrants keep attacking the most profitable parts of the payments chain."],
      "Sentiment weakened further after second-quarter 2026 results missed estimates and the full-year organic revenue outlook was cut to between -1% and flat, with adjusted EPS guided to $7.20–$7.40. Management blamed timing rather than lost business, but the credibility of the reset is still debated. Reports of preliminary talks to sell the STAR debit network to large US banks lifted the shares in August 2026, though no deal has been announced and analysts are sceptical one happens.",
      "Third-quarter results on 3 November 2026, Clover revenue growth, organic revenue by segment, debit network sale talks, free cash flow conversion, debt reduction.",
      (4, 3, 3, 4)),

        C("TTD", "The Trade Desk, Inc.", "software", "Ventura, California, USA", 2009,
      "Jeff Green", "Nasdaq", 62.00, 0.49, -1.4, 2.6,
      [0.18, 0.17, 0.15, 0.13, 0.11], 0.28, 0.33, 0.110, 0.030,
      "Founded in 2009 by Jeff Green, who still runs it. The Trade Desk operates a demand-side platform: software that advertising agencies and brands use to buy digital advertising across the open internet — connected television, audio, display — everywhere except the walled gardens of Google, Meta and Amazon. Its independence from any media owner is the core of the pitch.",
      [("Connected TV", 45), ("Display & Mobile", 38), ("Audio & Other", 17)],
      ["Independent positioning means no conflict of interest, unlike platforms that also sell their own inventory.",
       "Connected television advertising is shifting from linear TV budgets and is growing quickly.",
       "UID2 is a credible industry alternative to third-party cookies."],
      ["Amazon has entered demand-side advertising aggressively with enormous scale advantages.",
   "Advertising spend is cyclical and among the first budgets cut.",
   "Revenue is now guided to shrink, with third-quarter 2026 guidance of at least $650 million against $739 million a year earlier, and a fourth chief financial officer in about 14 months has hurt credibility."],
      "Confidence has collapsed further after second-quarter 2026 revenue of $715 million missed consensus by about 5% and third-quarter guidance implied a year-on-year decline of roughly 12%. The shares fell about 24% after hours on the 6 August 2026 report and hit a 52-week low of $11.85 in early October. Bears point to Amazon's growing share of programmatic spend; bulls argue the valuation now prices in a great deal of bad news.",
      "Third-quarter 2026 results, Kokai adoption, connected TV share, customer retention, competitive response to Amazon.",
      (4, 4, 4, 4)),

    C("ROP", "Roper Technologies, Inc.", "software", "Sarasota, Florida, USA", 1981,
      "Neil Hunn", "Nasdaq", 520.00, 0.107, 6.5, 7.5,
      [0.11, 0.10, 0.09, 0.08, 0.08], 0.30, 0.34, 0.085, 0.028,
      "Founded in 1981 as an industrial pump manufacturer. Neil Hunn has been CEO since 2018. Roper has spent two decades transforming into a collection of vertical software businesses — legal case management, freight matching, healthcare compliance, government contracting software. Each serves a niche too small for large vendors to attack but essential to the customers in it.",
      [("Application Software", 45), ("Network Software", 30), ("Technology Enabled Products", 25)],
      ["Niche vertical software has very high retention because no credible alternative exists.",
       "A disciplined acquisition machine with a long record of buying and improving businesses.",
       "Around 75% recurring revenue with strong cash conversion."],
      ["Growth depends on continued acquisitions, which requires reasonable valuations to be available.",
       "The businesses are individually small, so any single one moves the needle little.",
       "Consistently expensive relative to both software and industrial peers."],
      "Regarded as one of the better capital allocators in the market. The debate is deployment opportunity, not execution.",
      "Organic growth by segment, acquisition pipeline, recurring revenue mix, cash conversion.",
      (5, 4, 4, 5)),

        # ===================== HEALTHCARE =====================
    C("SNY", "Sanofi S.A.", "health", "Paris, France", 1973,
      "Olivier Charmeil", "Nasdaq", 47.99, 2.39, 12.0, 48.0,
      [0.05, 0.06, 0.06, 0.05, 0.05], 0.20, 0.24, 0.080, 0.024,
      "Traces to 1973, taking its current form through mergers with Synthélabo and Aventis. Olivier Charmeil took over as chief executive in 2026, succeeding Paul Hudson, who had refocused the company on immunology and vaccines and spun off consumer healthcare. Note that the US listing is an ADS: one ordinary Paris-listed share represents two ADSs, so the share count here is stated in ADSs to match the quoted price. Dupixent, an anti-inflammatory treating eczema, asthma and several other conditions, has become one of the largest-selling drugs in the world and drives most of the growth. US-listed as an ADR.",
      [("Dupixent & Immunology", 42), ("Vaccines", 24), ("General Medicines", 26), ("Consumer & Other", 8)],
      ["Dupixent keeps adding approved indications, each expanding the addressable population.",
       "Vaccines is a structurally defensive business with high barriers to entry.",
       "Trades at a discount to US pharmaceutical peers on comparable pipelines."],
      ["Heavy dependence on a single product — Dupixent is a very large share of growth.",
   "European pharmaceutical companies face persistent pricing pressure at home.",
   "The pipeline behind Dupixent is less proven than the market would like, and the October 2026 Regeneron deal adds $1 billion upfront and up to $7 billion in milestones for mostly early-stage antibodies."],
      "Generally viewed as reasonably valued with real single-product concentration risk. The October 2026 expansion of the Regeneron alliance into long-acting successors to Dupixent is read as an attempt to extend the franchise, while the planned transfer of 20 mature medicines to Cheplapharm continues the narrowing of the portfolio.",
      "Third-quarter results on 30 October 2026, Dupixent indication expansions, progress of long-acting Regeneron antibodies, Cheplapharm transfer from early 2027, vaccine season strength, currency effects.",
      (4, 3, 4, 4)),

    C("GSK", "GSK plc", "health", "London, United Kingdom", 1715,
      "Luke Miels", "NYSE", 44.00, 2.05, 18.0, 42.0,
      [0.04, 0.05, 0.05, 0.04, 0.04], 0.21, 0.24, 0.080, 0.022,
      "Traces to a London apothecary founded in 1715, with the modern company formed by the 2000 GlaxoWellcome and SmithKline Beecham merger. Emma Walmsley, CEO from 2017, separated consumer health as Haleon in 2022; Luke Miels, previously chief commercial officer, succeeded her as chief executive on 1 January 2026. GSK now focuses on vaccines, HIV through its ViiV stake, and specialty medicines. US-listed as an ADR.",
      [("Specialty Medicines", 40), ("Vaccines", 33), ("General Medicines", 27)],
      ["Shingrix is the leading shingles vaccine with a large under-penetrated eligible population.",
       "The HIV franchise generates substantial and durable cash flow.",
       "One of the higher dividend yields in large-cap pharmaceuticals."],
      ["Zantac litigation created years of overhang, and legal risk in pharma rarely fully clears.",
   "The oncology pipeline still lags larger peers, although Jemperli's FDA priority review in rectal cancer and the September 2026 Chimagen myeloma deal show it is being rebuilt.",
   "Vaccine demand proved more cyclical post-pandemic than expected."],
      "A value case in European pharma, now under Luke Miels, who became chief executive on 1 January 2026. Pipeline news flow between August and October 2026 has been positive, including a Phase III start for an mRNA flu vaccine and a CROWN trial win for long-acting HIV therapy Cabenuva. Vaccine growth and pipeline delivery remain the recurring debates.",
      "Third-quarter results, Shingrix uptake, long-acting HIV adoption, Jemperli rectal cancer FDA decision, mRNA flu Phase III start, litigation developments.",
      (4, 2, 3, 4)),

    C("MRNA", "Moderna, Inc.", "health", "Cambridge, Massachusetts, USA", 2010,
      "Stéphane Bancel", "Nasdaq", 26.00, 0.385, -6.0, 3.2,
      [0.08, 0.15, 0.18, 0.16, 0.13], -0.35, 0.08, 0.135, 0.030,
      "Founded in 2010 to develop messenger RNA therapeutics, an approach with no approved products until COVID-19 vaccines validated it at extraordinary speed. Stéphane Bancel has been CEO since 2011. Revenue collapsed from pandemic peaks and Moderna is now spending heavily to prove mRNA works beyond COVID — in RSV, influenza, and most importantly individualised cancer vaccines.",
      [("COVID-19 Vaccines", 62), ("RSV & Flu", 20), ("Other & Collaborations", 18)],
      ["The mRNA platform allows far faster development cycles than conventional biologics.",
   "Individualised neoantigen therapy intismeran, with Merck's Keytruda, met its primary recurrence-free survival endpoint in the Phase 3 INTerpath-001 melanoma trial in August 2026.",
   "Cash plus $2.6 billion of convertible notes raised in August 2026 funds oncology expansion and several more years of development."],
      ["Deeply lossmaking, with revenue far below the cost base built during the pandemic.",
   "COVID vaccine demand continues to decline and is now seasonal at best.",
   "After the August 2026 melanoma readout the valuation assumes regulatory approval and commercial success for cancer vaccines that have not yet been filed."],
      "The August 2026 Phase 3 melanoma success has turned the debate from whether the cancer platform works to how large it can become, and the shares traded around $143 by late August. Moderna joins the Nasdaq-100 on 9 October 2026. Bears still point to a heavily lossmaking respiratory business and the dilution embedded in the new convertible.",
      "Full INTerpath-001 data presentation and regulatory filings, overall survival follow-up, ESMO 2026 data, mFLUSIVA launch, COVID season uptake, cash burn.",
      (3, 5, 3, 2)),

    C("BIIB", "Biogen Inc.", "health", "Cambridge, Massachusetts, USA", 1978,
      "Christopher Viehbacher", "Nasdaq", 145.00, 0.146, 3.0, 9.5,
      [0.01, 0.03, 0.04, 0.04, 0.03], 0.27, 0.30, 0.095, 0.022,
      "Founded in 1978, among the earliest biotechnology companies. Christopher Viehbacher became CEO in 2022. Biogen built its franchise in multiple sclerosis, now facing generic competition, and has staked its future on Alzheimer's disease — Leqembi, developed with Eisai, is one of the first treatments shown to slow cognitive decline, though uptake has been slower than hoped.",
      [("Multiple Sclerosis", 45), ("Alzheimer's & Neurology", 22), ("Biosimilars & Other", 33)],
      ["Leqembi addresses an enormous unmet need with essentially no direct competition yet.",
       "Deep neuroscience expertise built over four decades.",
       "Trades at a low multiple with substantial cash generation from the legacy franchise."],
      ["The multiple sclerosis franchise is in structural decline as generics arrive.",
   "Leqembi still requires diagnostic confirmation and MRI monitoring, which has slowed adoption, although a subcutaneous autoinjector for starting therapy became available in the US in August 2026.",
   "A long record of pipeline disappointments has damaged credibility."],
      "Cheap for identifiable reasons. The argument is whether Alzheimer's treatment scales before the base business erodes.",
      "Leqembi patient starts and Iqlik autoinjector uptake, MS revenue decline rate, litifilimab and immunology pipeline progress, cost reductions.",
      (3, 2, 4, 3)),

    C("IDXX", "IDEXX Laboratories, Inc.", "health", "Westbrook, Maine, USA", 1983,
      "Jonathan Mazelsky", "Nasdaq", 540.00, 0.081, 0.5, 4.0,
      [0.09, 0.09, 0.08, 0.08, 0.07], 0.24, 0.28, 0.085, 0.028,
      "Founded in 1983. IDEXX makes veterinary diagnostic equipment and the test consumables that run on it, plus practice management software for animal clinics. The model mirrors razor-and-blades: place an analyser in a veterinary practice, then sell the proprietary test slides it consumes for years afterwards. It holds a dominant position in companion animal diagnostics.",
      [("Companion Animal Diagnostics", 87), ("Water Testing", 7), ("Livestock & Other", 6)],
      ["Installed analysers lock in years of high-margin consumable revenue.",
       "Pet healthcare spending has proved resilient through economic cycles.",
       "Diagnostic testing rates per veterinary visit continue to rise."],
      ["Veterinary clinic visit volumes have softened as pandemic-era pet adoption normalises.",
       "Persistently expensive relative to almost any comparable business.",
       "Veterinary staffing shortages constrain how many appointments clinics can run."],
      "Regarded as an exceptional business model. The entire discussion is valuation and clinic visit trends. Second-quarter 2026 results, with 9% organic revenue growth and a full-year EPS outlook raised to $14.69–$14.94, kept the operating record intact.",
      "Third-quarter results on 2 November 2026, clinic visit volumes, consumable revenue growth, analyser placements including the new cardiac test, testing per visit.",
      (5, 4, 4, 5)),

    C("A", "Agilent Technologies, Inc.", "health", "Santa Clara, California, USA", 1999,
      "Padraig McDonnell", "NYSE", 125.00, 0.284, 1.5, 6.6,
      [0.05, 0.07, 0.07, 0.06, 0.06], 0.21, 0.25, 0.085, 0.026,
      "Spun out of Hewlett-Packard in 1999. Padraig McDonnell became CEO in 2025. Agilent makes analytical instruments — mass spectrometers, chromatography systems — used in pharmaceutical development, environmental testing and food safety, plus the consumables and services that go with them. Like Thermo Fisher it sells into research activity rather than betting on outcomes.",
      [("Life Sciences & Applied Markets", 40), ("Diagnostics & Genomics", 27), ("CrossLab Services", 33)],
      ["Recurring consumables and service revenue is over half the total and far steadier than instruments.",
       "The installed base of instruments creates a long service annuity.",
       "Pharmaceutical quality control testing is non-discretionary regulated spending."],
      ["Instrument purchases are capital decisions customers defer easily when budgets tighten.",
       "China is a meaningful market and has been persistently weak.",
       "Academic and biotech funding pressure has reduced research spending."],
      "A quality instruments franchise that is now recovering. Fiscal third-quarter 2026 core revenue grew 7.3% and full-year guidance was raised to $7.49–$7.51 billion of revenue and $6.18–$6.21 of non-GAAP EPS, so the debate has moved from recovery timing to how durable the upturn is.",
      "Fiscal fourth-quarter results, instrument order growth, China demand, recurring revenue mix, pharma capital budgets, tariff refunds.",
      (5, 3, 4, 5)),

    C("EW", "Edwards Lifesciences Corporation", "health", "Irvine, California, USA", 1958,
      "Bernard Zovighian", "NYSE", 78.00, 0.59, -1.0, 6.2,
      [0.09, 0.09, 0.08, 0.08, 0.07], 0.24, 0.27, 0.085, 0.028,
      "Traces to Miles Lowell Edwards, who built the first artificial heart valve in 1958, and separated from Baxter in 2000. Bernard Zovighian has been CEO since 2023. Edwards dominates transcatheter aortic valve replacement — replacing a heart valve via catheter rather than open-heart surgery, which makes the procedure available to patients too frail for surgery.",
      [("Transcatheter Aortic Valve", 62), ("Surgical Structural Heart", 17), ("Transcatheter Mitral & Tricuspid", 21)],
      ["Clear leadership in transcatheter aortic valves with strong clinical evidence behind it.",
       "The eligible patient population keeps expanding as trials extend into lower-risk groups.",
       "Mitral and tricuspid programmes open genuinely large new markets."],
      ["Aortic valve growth has decelerated as the initial market matures.",
       "Medtronic and Abbott compete directly and are investing heavily.",
       "Hospital procedure capacity and staffing limit how fast volumes can grow."],
      "The franchise quality is not disputed; the growth rate is. The updated Medicare coverage policy for transcatheter aortic valves issued in September 2026 is seen as widening patient access, though Edwards says adoption will take time. Mitral and tricuspid growth and the 2027 outlook due at the December investor conference are the swing factors.",
      "TCT investor event on 2 November 2026, third-quarter results on 4 November 2026, December investor conference with 2027 guidance, uptake under the new TAVR coverage policy, mitral and tricuspid growth.",
      (5, 3, 5, 5)),

    C("CNC", "Centene Corporation", "health", "St. Louis, Missouri, USA", 1984,
      "Sarah London", "NYSE", 62.00, 0.49, 12.0, 165.0,
      [0.04, 0.05, 0.05, 0.04, 0.04], 0.020, 0.026, 0.095, 0.024,
      "Founded in 1984 by Elizabeth Brinn as a single Wisconsin health plan. Sarah London has been CEO since 2022. Centene is the largest US Medicaid managed care organisation, administering government health programmes for low-income populations across most states, plus a substantial marketplace insurance business. Revenue depends almost entirely on government contracts and reimbursement rates.",
      [("Medicaid", 55), ("Marketplace", 25), ("Medicare", 12), ("Other", 8)],
      ["Scale leader in Medicaid managed care, an area states continue to outsource.",
       "Marketplace enrolment has grown substantially with enhanced subsidies.",
       "Trades at a low multiple relative to the broader managed care group."],
      ["Medicaid redeterminations left a sicker remaining membership, pressuring margins badly.",
       "State reimbursement rates have lagged actual medical cost trends.",
       "Expiry of enhanced marketplace subsidies is a direct and dated risk to enrolment."],
      "One of the most contested managed care names. Rate adequacy versus medical costs drives everything.",
      "Medicaid health benefits ratio, state rate updates, marketplace enrolment, subsidy legislation.",
      (3, 2, 3, 3)),

    C("IQV", "IQVIA Holdings Inc.", "health", "Durham, North Carolina, USA", 1982,
      "Ari Bousbib", "NYSE", 185.00, 0.174, 13.0, 15.5,
      [0.05, 0.07, 0.07, 0.06, 0.06], 0.16, 0.20, 0.090, 0.026,
      "Formed by the 2016 merger of IMS Health and Quintiles. Ari Bousbib has been CEO since. IQVIA runs clinical trials for pharmaceutical companies as a contract research organisation, and separately sells the prescription and healthcare data the industry uses for commercial decisions. Combining trial execution with data ownership is unusual and hard to replicate.",
      [("Research & Development Solutions", 58), ("Technology & Analytics", 37), ("Contract Sales", 5)],
      ["Combining trial execution with proprietary healthcare data is a genuinely differentiated position.",
       "A large committed backlog gives multi-year revenue visibility.",
       "Drug development activity grows structurally regardless of which drugs succeed."],
      ["Biotech funding weakness reduces the volume of trials being started.",
       "Large pharmaceutical clients have been consolidating vendor spend and pushing on price.",
       "Meaningful debt load from the merger and subsequent acquisitions."],
      "Viewed as the leading contract research organisation, with the debate centred on biotech funding recovery.",
      "Third-quarter results on 27 October 2026, backlog and book-to-bill, biotech funding conditions, large pharma awards, data business growth.",
      (4, 3, 3, 4)),

    C("DXCM", "DexCom, Inc.", "health", "San Diego, California, USA", 1999,
      "Jake Leach", "Nasdaq", 72.00, 0.39, 0.5, 4.4,
      [0.13, 0.13, 0.12, 0.10, 0.09], 0.21, 0.26, 0.100, 0.030,
      "Founded in 1999. Jake Leach is president and chief executive. DexCom makes continuous glucose monitors — small sensors worn on the body that track blood sugar in real time and send it to a phone, replacing finger-prick testing. The market is expanding well beyond insulin-dependent diabetics into type 2 patients and general metabolic health monitoring.",
      [("US Sensor & Hardware", 70), ("International", 30)],
      ["Continuous glucose monitoring is still substantially under-penetrated even among insulin users.",
       "Expansion into type 2 diabetes multiplies the addressable population.",
       "The consumables model produces highly recurring revenue per patient."],
      ["Abbott's Libre competes directly and is priced more aggressively.",
       "Reimbursement decisions by insurers determine how fast the market can expand.",
       "A US sales force reorganisation caused a growth stumble that damaged credibility."],
      "The category growth is not in doubt; DexCom's share of it against Abbott is.",
      "Third-quarter results on 29 October 2026, new patient starts, international growth, type 2 reimbursement decisions, competitive pricing.",
      (4, 4, 4, 4)),

    C("HUM", "Humana Inc.", "health", "Louisville, Kentucky, USA", 1961,
      "Jim Rechtin", "NYSE", 255.00, 0.121, 8.0, 122.0,
      [0.05, 0.05, 0.05, 0.04, 0.04], 0.022, 0.030, 0.095, 0.024,
      "Founded in 1961 as a nursing home operator, later a hospital company, and health insurance only from the 1980s. Jim Rechtin became CEO in 2024. Humana is the second largest Medicare Advantage insurer, covering older Americans through privately administered Medicare, and operates primary care clinics through CenterWell.",
      [("Medicare Advantage", 78), ("Group & Specialty", 12), ("CenterWell Services", 10)],
      ["Medicare Advantage enrolment grows structurally with an ageing population.",
       "CenterWell clinics give it control over care delivery costs, not just insurance risk.",
       "Deep experience in Medicare specifically, rather than as one line among many."],
      ["Medical cost utilisation ran far above pricing assumptions, causing severe margin damage.",
       "Star ratings declines directly reduce bonus payments, and one downgrade costs hundreds of millions.",
       "Almost entirely dependent on a single government programme and its reimbursement decisions."],
      "Sentiment has turned more constructive: Barclays upgraded the shares to Overweight on 25 September 2026 with a $515 target, and the stock was up about 60% this year. The debate now centres on whether 2027 star ratings recover after only about 20% of members sat in four-star-plus plans for 2026, with draft cutpoints for 2027 tougher on about half of measures.",
      "Final 2027 star ratings (October 2026), third-quarter results, 2027 membership after exiting plans covering about 600,000 members, medical loss ratio, CenterWell expansion.",
      (3, 3, 3, 3)),

    # ===================== FINANCIALS =====================
    C("AON", "Aon plc", "financials", "Dublin, Ireland", 1982,
      "Greg Case", "NYSE", 350.00, 0.216, 16.0, 16.0,
      [0.07, 0.07, 0.06, 0.06, 0.05], 0.21, 0.24, 0.080, 0.027,
      "Formed in 1982 through the combination of Ryan Insurance and Combined International. Greg Case has been CEO since 2005. Aon is the second largest insurance broker globally, placing commercial risk and advising on reinsurance, plus a substantial human capital consulting business. Like Marsh McLennan it earns commission on premium without underwriting any risk itself. In August 2026 it agreed to buy USI, a US middle-market broker with about $3 billion of annual revenue, for $17.0 billion in cash, with completion expected in the fourth quarter of 2026.",
      [("Commercial Risk", 45), ("Reinsurance", 20), ("Health Solutions", 22), ("Wealth Solutions", 13)],
      ["Broking captures the upside of rising insurance prices without bearing any claims.",
   "Reinsurance broking is a concentrated market with very few credible participants.",
   "USI adds a large US middle-market platform, with about $395 million of targeted annual run-rate synergies on top of highly recurring renewal revenue."],
      ["After NFP, the debt-funded $17 billion USI purchase takes leverage to about 4.8 times at closing, against a 2.8–3.0 times target Aon aims to regain within about 24 months.",
   "Commission revenue falls when insurance pricing softens.",
   "Consulting revenue is discretionary and cyclical, and buybacks are paused while debt is repaid."],
      "Still bracketed with Marsh McLennan as a high-quality broker, but the USI deal, priced at about 14.5 times synergised EBITDA and roughly 22 times before synergies, has made leverage and integration the central debate. The interim CFO arrangement after Edmund Reese's August 2026 departure adds to execution questions during a large integration.",
      "USI closing (expected Q4 2026), de-leveraging pace, permanent CFO appointment, NFP and USI integration, organic revenue growth, insurance pricing cycle.",
      (5, 3, 3, 5)),

    C("USB", "U.S. Bancorp", "financials", "Minneapolis, Minnesota, USA", 1863,
      "Gunjan Kedia", "NYSE", 52.00, 1.56, 0.0, 28.0,
      [0.04, 0.05, 0.05, 0.04, 0.04], 0.26, 0.30, 0.100, 0.025,
      "Traces to the First National Bank of Cincinnati, chartered 1863. Gunjan Kedia became CEO in 2025. U.S. Bancorp is the largest US regional bank, with a branch network across the Midwest and West plus a payments processing business unusual for a bank of its size, providing fee income uncorrelated with lending.",
      [("Consumer & Business Banking", 40), ("Payment Services", 25), ("Wealth & Corporate", 35)],
      ["The payments business gives fee revenue most regional banks lack entirely.",
       "Historically among the best returns on equity in US regional banking.",
       "Diversified deposit base with a strong regional franchise."],
      ["Regional banks face structural deposit cost pressure from money market alternatives.",
       "Commercial real estate exposure is a persistent concern across the sector.",
       "The Union Bank integration consumed management attention and capital."],
      "Regarded as the highest-quality large regional bank. Deposit costs and credit quality drive the debate.",
      "Net interest margin, deposit costs, payments revenue growth, credit provisions.",
      (4, 3, 3, 4)),

    C("PNC", "The PNC Financial Services Group, Inc.", "financials", "Pittsburgh, Pennsylvania, USA", 1852,
      "William Demchak", "NYSE", 205.00, 0.396, 0.0, 22.0,
      [0.04, 0.05, 0.05, 0.04, 0.04], 0.27, 0.31, 0.100, 0.025,
      "Traces to the Pittsburgh Trust and Savings Company, founded 1852. William Demchak has been CEO since 2013. PNC is one of the largest US regional banks, with a national expansion strategy pursued through both acquisition and organic branch building, plus a substantial corporate and institutional banking arm.",
      [("Retail Banking", 42), ("Corporate & Institutional", 45), ("Asset Management", 13)],
      ["A national expansion strategy that has genuinely added markets rather than just assets.",
       "Corporate banking provides diversification away from pure consumer lending.",
       "Consistently conservative credit underwriting through cycles."],
      ["The same deposit cost pressure affecting all regional banks.",
       "Commercial real estate exposure, particularly office, remains an overhang.",
       "Regional bank consolidation may force expensive defensive acquisitions."],
      "Well regarded on management quality. Sector-wide questions on deposits and credit apply equally here.",
      "Net interest income guidance, deposit betas, credit quality, expansion market progress.",
      (4, 3, 3, 4)),

    C("TFC", "Truist Financial Corporation", "financials", "Charlotte, North Carolina, USA", 1872,
      "Michael Lyons", "NYSE", 48.00, 1.32, 0.0, 23.0,
      [0.03, 0.05, 0.05, 0.04, 0.04], 0.24, 0.29, 0.105, 0.025,
      "Formed in 2019 by the merger of BB&T and SunTrust, with roots to 1872. Michael Lyons became chief executive on 1 September 2026, succeeding Bill Rogers, who moved to executive chair. Truist is a large southeastern US regional bank. It sold its insurance brokerage in 2024 to strengthen capital, a decision that raised questions about what remains to differentiate it.",
      [("Consumer & Small Business", 45), ("Wholesale Banking", 47), ("Other", 8)],
      ["Strong deposit franchise across fast-growing southeastern markets.",
       "The insurance sale materially improved capital ratios.",
       "Trades at a discount to regional bank peers on tangible book."],
      ["The merger integration was difficult and took far longer than guided.",
       "Selling insurance removed the main source of fee income diversification.",
       "Commercial real estate concentration is above the regional average."],
      "Generally seen as cheap with reason. The question is what the franchise looks like without insurance.",
      "Net interest margin, expense reduction, credit provisions, capital returns.",
      (3, 2, 3, 3)),

    C("AIG", "American International Group, Inc.", "financials", "New York, New York, USA", 1919,
      "Eric Andersen", "NYSE", 88.00, 0.58, 8.0, 27.0,
      [0.03, 0.04, 0.04, 0.04, 0.03], 0.13, 0.17, 0.095, 0.024,
      "Founded in Shanghai in 1919 by Cornelius Vander Starr. Peter Zaffino, CEO from 2021, spent his tenure simplifying a company that required a government rescue in 2008, divesting life and retirement (the last Corebridge shares were sold in May 2026) and refocusing on general insurance. Eric Andersen succeeded him as CEO in 2026, and Zaffino left the board in September 2026. AIG now writes commercial property and casualty and specialty lines globally.",
      [("North America Commercial", 42), ("International Commercial", 38), ("Global Personal", 20)],
      ["Underwriting discipline has improved substantially and consistently under Zaffino.",
       "The simplification into a pure general insurer makes the business far easier to value.",
       "A large buyback programme funded by divestiture proceeds."],
      ["The 2008 legacy still colours how the market perceives risk management here.",
       "Catastrophe exposure is inherent to commercial property insurance.",
       "Commercial pricing has passed its cyclical peak in several lines."],
      "A turnaround the market has largely credited, now passing to new leadership: Eric Andersen is CEO, Zaffino left the board in September 2026 and the head of General Insurance retires at the end of 2026. Second-quarter 2026 results were solid, with adjusted EPS up 10% and a combined ratio of 89.0%; the question remains normalised underwriting margin from here.",
      "Third-quarter results (3 November 2026), combined ratio, commercial rate change, catastrophe losses, buyback pace, leadership transition under Andersen.",
      (4, 2, 4, 3)),

    C("MET", "MetLife, Inc.", "financials", "New York, New York, USA", 1868,
      "Michel Khalaf", "NYSE", 92.00, 0.68, 15.0, 72.0,
      [0.03, 0.04, 0.04, 0.04, 0.03], 0.075, 0.09, 0.095, 0.024,
      "Founded in 1868. Michel Khalaf has been CEO since 2019. MetLife is one of the largest US life insurers, selling group benefits through employers — life, dental, disability — plus retirement solutions and international operations concentrated in Asia and Latin America. Group benefits is genuinely attractive: employers renew annually and switching disrupts every employee.",
      [("Group Benefits", 35), ("Retirement & Income", 27), ("Asia", 20), ("Latin America & Other", 18)],
      ["Group benefits has high retention and low capital intensity relative to individual life.",
       "Higher interest rates improve investment income on a very large asset base.",
       "Asian operations provide growth that US-only insurers lack."],
      ["Life insurance liabilities extend for decades, making the balance sheet hard to assess externally.",
       "Sensitive to credit losses in a large corporate bond portfolio.",
       "Long-term care and legacy blocks carry reserve risk."],
      "A stable, capital-return-focused holding. Second-quarter 2026 adjusted EPS rose 20% to $2.43 with adjusted ROE of 17.0%, and a new $3 billion buyback authorisation in August 2026 reinforced the capital-return case. Interest rates and credit quality still drive most of the variance.",
      "Third-quarter results, group benefits ratio, spread income, Asian growth, pace of the $3 billion buyback.",
      (4, 2, 3, 4)),

    C("APO", "Apollo Global Management, Inc.", "financials", "New York, New York, USA", 1990,
      "Marc Rowan", "NYSE", 135.00, 0.57, 0.0, 26.0,
      [0.10, 0.10, 0.09, 0.08, 0.07], 0.25, 0.30, 0.105, 0.028,
      "Founded in 1990 by Leon Black, Josh Harris and Marc Rowan. Rowan has been CEO since 2021. Apollo is known for credit investing rather than traditional private equity, and its 2022 merger with Athene, an annuities provider, gave it a very large permanent capital base — insurance premiums it can invest without ever needing to raise a fund.",
      [("Asset Management", 32), ("Retirement Services (Athene)", 60), ("Principal Investing", 8)],
      ["Athene provides permanent capital that never needs re-raising, unlike traditional fund structures.",
       "Private credit is taking share from bank lending, and Apollo is the largest player.",
       "Origination capability is a genuine differentiator over managers who only allocate."],
      ["Insurance liabilities introduce balance sheet risk that pure fee managers avoid entirely.",
       "Private credit has attracted enormous capital and spreads have compressed.",
       "A credit cycle would test both the investment portfolio and the annuity book at once."],
      "The most credit-focused of the large alternative managers, and views on it are largely views on private credit. Second-quarter 2026 showed record fee-related earnings, up 25% to $785 million, with assets above $1 trillion, and the October 2026 move to daily pricing of all credit assets addresses the transparency debate around the asset class.",
      "Third-quarter results (3 November 2026), fee-related earnings, Athene spread income, origination volumes, credit performance, daily credit pricing rollout.",
      (5, 4, 3, 4)),

    C("AJG", "Arthur J. Gallagher & Co.", "financials", "Rolling Meadows, Illinois, USA", 1927,
      "J. Patrick Gallagher Jr.", "NYSE", 310.00, 0.256, 6.0, 11.5,
      [0.11, 0.10, 0.09, 0.08, 0.07], 0.21, 0.24, 0.080, 0.028,
      "Founded in 1927 by Arthur J. Gallagher; his grandson has run it since 1995. Gallagher is the third largest insurance broker globally, built through an unusually consistent programme of acquiring small regional brokerages — dozens a year — and folding them into a common platform. It focuses on middle-market clients rather than the largest multinationals.",
      [("Brokerage", 85), ("Risk Management", 15)],
      ["A repeatable acquisition model in a fragmented market with hundreds of remaining targets.",
       "Middle-market focus faces less competition than the largest accounts.",
       "Broking economics: commission on premium with no underwriting risk."],
      ["Growth depends on continued acquisitions at sensible prices.",
       "Integration risk compounds when acquiring dozens of businesses annually.",
       "Commission revenue falls if insurance pricing softens."],
      "Consistently well regarded for execution. The debate is how long the acquisition runway lasts.",
      "Organic growth, acquisition count and pricing, insurance rate environment, margin expansion.",
      (5, 4, 4, 5)),
]
