"""Expansion coverage, part two — companies 151 to 200.

All US-listed, so every price updates automatically from the free Finnhub tier.

Deliberately excluded: REITs. Prologis, American Tower and Equinix are all large
enough to belong here, but real estate is valued on funds from operations rather
than free cash flow, and running them through the standard DCF would produce
numbers that look precise and mean nothing. They need their own treatment, which
is a separate piece of work.

As with part one, prices below are only starting values — the first scheduled run
overwrites them. Revenue, share count and net debt are modelling inputs and do
not auto-update.
"""

from companies.schema import C

EXPANSION2 = [

    # ===================== SEMICONDUCTORS =====================
    C("MCHP", "Microchip Technology Incorporated", "semis", "Chandler, Arizona, USA", 1987,
      "Steve Sanghi", "Nasdaq", 62.00, 0.54, 5.5, 4.9,
      [0.12, 0.14, 0.11, 0.09, 0.08], 0.22, 0.30, 0.100, 0.028,
      "Founded in 1987 when General Instrument spun out its microelectronics division. Steve Sanghi, who ran the company from 1991 to 2021, returned as CEO in November 2024 after his successor departed amid a severe downturn. Microchip makes microcontrollers — the small, cheap processors embedded in industrial equipment, cars and appliances — alongside analog and connectivity parts. Its parts sell for a few dollars and stay designed into products for a decade or more.",
      [("Microcontrollers", 52), ("Analog", 26), ("FPGA & Other", 22)],
      ["Extremely long product lifecycles: designs stay in production for a decade or more, making revenue durable once won.",
       "Tens of thousands of customers with no meaningful concentration risk.",
       "Sanghi's return brought back the operator who built the company's original discipline."],
      ["Went through one of the deepest inventory corrections in the industry, with revenue nearly halving from peak.",
   "Carries meaningful debt from the Microsemi acquisition into a downturn.",
   "Management has said the 66-67% gross margin guided for the September 2026 quarter includes one-off benefits such as lumpy licensing revenue and should not be modelled higher."],
      "The recovery is now visible in reported numbers: June 2026 quarter net sales rose 38% year on year to $1.485 billion, ahead of the top of guidance, with a further 7-9% sequential rise guided. The debate has moved from whether the cycle has turned to how much of the margin rebound is sustainable, with management directing excess cash to debt reduction rather than buybacks.",
      "September 2026 quarter results, book-to-bill ratio, inventory days, gross margin sustainability, debt reduction, Hailo edge AI integration.",
      (4, 3, 2, 4)),

    C("MPWR", "Monolithic Power Systems, Inc.", "semis", "Kirkland, Washington, USA", 1997,
      "Michael Hsing", "Nasdaq", 720.00, 0.048, -1.0, 2.3,
      [0.22, 0.19, 0.16, 0.13, 0.11], 0.28, 0.32, 0.100, 0.030,
      "Founded in 1997 by Michael Hsing, who still runs it. Monolithic Power makes power management integrated circuits — the parts that convert and regulate voltage inside electronic systems. Its differentiation is proprietary process technology that lets it integrate more function into a smaller package than competitors. It has become a significant supplier of power delivery for AI accelerators, where the sheer power draw of modern GPUs has made this an unexpectedly critical component.",
      [("Enterprise Data", 38), ("Storage & Computing", 20), ("Automotive", 17), ("Industrial & Consumer", 25)],
      ["AI accelerators draw enormous power, and delivering it efficiently at the board level is a genuine engineering constraint.",
       "Proprietary process technology gives a real integration advantage over competitors buying standard processes.",
       "Founder-led with an unusually consistent long-term execution record."],
      ["Very high customer concentration in the data centre business.",
       "Trades at one of the highest multiples in semiconductors, leaving no room for disappointment.",
       "Competitors including Infineon and Renesas are targeting the same AI power delivery sockets."],
      "Regarded as a high-quality operator with a valuation that assumes continued AI power content gains. In September 2026 it signed a long-term agreement to run its proprietary process at GlobalFoundries' Singapore fab, adding manufacturing capacity from early 2027.",
      "Data centre revenue growth, design win announcements, content per accelerator, gross margin, GlobalFoundries Singapore capacity coming online in early 2027.",
      (5, 5, 5, 4)),

    C("TER", "Teradyne, Inc.", "semis", "North Reading, Massachusetts, USA", 1960,
      "Greg Smith", "Nasdaq", 135.00, 0.16, -0.5, 2.9,
      [0.16, 0.15, 0.12, 0.10, 0.09], 0.22, 0.27, 0.100, 0.028,
      "Founded in 1960 by two MIT graduates, Alex d'Arbeloff and Nick DeWolf. Greg Smith has been CEO since 2020. Teradyne makes automated test equipment — the systems that verify a chip works correctly before it ships. Every semiconductor is tested, so Teradyne sells into the entire industry regardless of who wins. It also owns Universal Robots and Mobile Industrial Robots, a collaborative robotics business that has grown more slowly than hoped.",
      [("Semiconductor Test", 76), ("Robotics", 10), ("System Test & Wireless", 14)],
      ["Test intensity rises with chip complexity, so AI and advanced packaging structurally increase test time per device.",
       "A duopoly with Advantest in the highest-end test systems.",
       "Net cash balance sheet and consistent buybacks."],
      ["Highly cyclical, following semiconductor capital spending closely.",
       "Customer concentration is significant among the largest chipmakers.",
       "The robotics business has consistently disappointed against its original acquisition thesis."],
      "Viewed as a reasonable way to own rising chip complexity. The robotics segment is the main source of scepticism.",
      "Semiconductor test bookings, AI test intensity commentary, robotics revenue, customer capex plans.",
      (4, 4, 4, 4)),

    C("GFS", "GlobalFoundries Inc.", "semis", "Malta, New York, USA", 2009,
      "Tim Breen", "Nasdaq", 42.00, 0.55, 1.0, 6.8,
      [0.05, 0.08, 0.08, 0.07, 0.06], 0.14, 0.19, 0.105, 0.026,
      "Created in 2009 when AMD spun out its manufacturing operations, with Abu Dhabi's Mubadala as majority owner. Tim Breen became CEO in 2025. GlobalFoundries abandoned the race for leading-edge nodes in 2018 and instead specialises in mature and specialty processes — the chips that go into cars, phones' radio front ends, and industrial equipment, where reliability matters more than transistor density. Its US and European fabs give customers geographic diversification away from Taiwan.",
      [("Smart Mobile Devices", 44), ("Automotive", 20), ("IoT", 16), ("Communications & Other", 20)],
      ["Geographic diversification is genuinely valuable to customers worried about Taiwan concentration.",
   "Specialty processes have longer product lifecycles and less pricing pressure than leading edge.",
   "Substantial government support, including a $375 million Commerce Department quantum R&D award finalised in September 2026 and an expected $300 million award for silicon photonics."],
      ["Deliberately exited leading-edge manufacturing, so its AI exposure comes through adjacent areas such as optical networking, silicon photonics and packaging rather than the accelerators themselves.",
   "Far smaller scale than TSMC, with correspondingly weaker margins.",
   "Automotive and smartphone end markets have both been soft."],
      "Seen as a strategically useful but structurally lower-margin foundry, though AI-related optical networking demand is starting to change the growth story. June 2026 quarter revenue rose 6% year on year to $1.786 billion, above the top of guidance, and the October 2026 agreement to make silicon interposers for TSMC's CoWoS packaging in Malta, New York gives it a direct role in the US AI packaging supply chain.",
      "Third quarter 2026 results, utilisation rates, optical networking and silicon photonics demand, TSMC interposer capacity build in Malta (volume ramp from first half 2028), government funding milestones.",
      (3, 3, 3, 3)),

    # ===================== SOFTWARE & INTERNET =====================
    C("SNOW", "Snowflake Inc.", "software", "Bozeman, Montana, USA", 2012,
      "Sridhar Ramaswamy", "NYSE", 282.9, 0.33, -4.0, 4.0,
      [0.26, 0.23, 0.19, 0.16, 0.13], 0.12, 0.24, 0.110, 0.032,
      "Founded in 2012 by two former Oracle engineers, Benoit Dageville and Thierry Cruanes. Sridhar Ramaswamy, previously head of Google's advertising business, became CEO in 2024. Snowflake sells a cloud data platform that separates storage from compute, letting customers scale each independently and pay only for what they use. That consumption model means revenue tracks customer usage directly rather than seats, which cuts both ways.",
      [("Product Revenue", 95), ("Professional Services", 5)],
      ["Consumption pricing means revenue grows automatically as customers analyse more data.",
       "Data gravity creates real lock-in — once a company's data warehouse is in Snowflake, moving is a major project.",
       "AI workloads require organised, accessible data, which is precisely what Snowflake provides."],
      ["Databricks competes directly and aggressively, and the hyperscalers all offer competing warehouses.",
       "Consumption pricing cuts both ways — customers optimising their spend directly reduces revenue.",
       "Still lossmaking on a GAAP basis with substantial stock-based compensation."],
      "Consumption growth has reaccelerated: product revenue rose 37% year on year to $1.49 billion in the July 2026 quarter, the third straight quarter of acceleration, and full-year guidance was raised to $6.07 billion. The shares rose more than 20% in extended trading on the results, so the valuation now assumes the AI-driven reacceleration holds.",
      "Fiscal third-quarter product revenue against the $1.588-1.593 billion guide, net revenue retention, remaining performance obligations, AI product adoption.",
      (4, 4, 4, 3)),

    C("DDOG", "Datadog, Inc.", "software", "New York, New York, USA", 2010,
      "Olivier Pomel", "Nasdaq", 145.00, 0.35, -3.0, 3.1,
      [0.24, 0.21, 0.18, 0.15, 0.13], 0.19, 0.27, 0.105, 0.032,
      "Founded in 2010 by Olivier Pomel and Alexis Lê-Quôc, who had worked together at Wireless Generation and were frustrated by the gap between developers and operations teams. Pomel still runs it. Datadog monitors cloud infrastructure and applications, showing engineers what is happening across their systems in real time. It has expanded methodically from infrastructure monitoring into logs, security and application performance, and customers typically adopt more products over time.",
      [("Infrastructure Monitoring", 35), ("APM & Logs", 40), ("Security & Other", 25)],
      ["Land-and-expand works unusually well here — most customers add products every year.",
       "Cloud migration and application complexity both structurally increase what needs monitoring.",
       "Genuinely strong product engineering reputation among developers, who are the buyers."],
      ["Usage-based pricing means revenue falls when customers optimise cloud spending.",
       "Competes with Dynatrace, New Relic, Splunk and Grafana, plus native cloud provider tools.",
       "A persistently high multiple that leaves the stock exposed to any growth deceleration."],
      "Well regarded operationally, and growth has reaccelerated: second-quarter 2026 revenue rose 36% year on year to $1.12 billion and full-year guidance was raised to $4.45-4.47 billion. The shares still fell about 21% before the open on 6 August 2026, with some analysts noting the guidance implied no further acceleration in the second half.",
      "Third-quarter 2026 results, second-half revenue growth trajectory, customers with multiple products, net revenue retention, AI-native customer cohort.",
      (5, 4, 4, 4)),

    C("WDAY", "Workday, Inc.", "software", "Pleasanton, California, USA", 2005,
      "Aneel Bhusri", "Nasdaq", 250.00, 0.27, -1.0, 8.8,
      [0.14, 0.13, 0.12, 0.11, 0.10], 0.24, 0.29, 0.095, 0.030,
      "Founded in 2005 by Dave Duffield and Aneel Bhusri after Oracle's hostile takeover of their previous company, PeopleSoft. Bhusri returned as CEO in February 2026, replacing Carl Eschenbach, who had led the company since 2023. Workday sells cloud human resources and financial management software to large enterprises. Replacing an HR system of record is one of the most disruptive projects a company can undertake, which makes both winning and losing customers a slow process — and revenue extremely sticky once won.",
      [("Subscription Services", 89), ("Professional Services", 11)],
      ["Systems of record for HR and finance have exceptionally high switching costs.",
       "Gross retention above 95% reflects how rarely customers leave.",
       "Large enterprise customer base with long contract durations and high visibility."],
      ["Headcount-based pricing means slower corporate hiring directly slows revenue growth.",
       "SAP and Oracle compete hard, particularly in finance where Workday is less established.",
       "Growth has decelerated from the rates that originally justified the multiple."],
      "Considered a durable franchise growing more slowly than it once did, with the shares down more than 40% from their 2024 peak by August 2026. Reuters reported that month that Silver Lake was in talks to take Workday private, and the stock rose further after fiscal second-quarter earnings beat estimates and the board added a $4.0 billion buyback.",
      "Silver Lake take-private talks, subscription revenue growth, 12-month subscription backlog, AI share of new contract value, execution of the $4.0 billion buyback.",
      (5, 3, 4, 5)),

    C("ABNB", "Airbnb, Inc.", "software", "San Francisco, California, USA", 2008,
      "Brian Chesky", "Nasdaq", 135.00, 0.63, -6.0, 11.6,
      [0.10, 0.10, 0.09, 0.08, 0.07], 0.32, 0.35, 0.095, 0.028,
      "Founded in 2008 by Brian Chesky, Joe Gebbia and Nathan Blecharczyk, who started by renting air mattresses in their San Francisco apartment during a design conference. Chesky still runs it. Airbnb connects travellers with hosts offering short-term accommodation and takes a commission from both sides. The marketplace is asset-light — it owns no property — and generates exceptional free cash flow relative to revenue.",
      [("North America", 45), ("EMEA", 34), ("Latin America", 8), ("Asia Pacific", 13)],
      ["Two-sided network effects with over seven million listings that no competitor can replicate quickly.",
       "Asset-light model produces free cash flow margins above 35%.",
       "Brand has become a generic verb, which is rare and valuable in consumer marketplaces."],
      ["Regulatory restrictions on short-term rentals keep tightening in major cities.",
   "Booking.com and Vrbo compete directly, and hotels have improved their direct offerings.",
   "Travel demand is cyclical, and management has warned of tougher comparisons in the second half of 2026 after revenue growth reaccelerated to 17% in the second quarter."],
      "Consensus admires the business model, and the growth debate has eased after second-quarter 2026 revenue rose 17% to $3.6 billion and nights and seats booked accelerated to 10% growth. Management raised its full-year outlook to at least mid-teens revenue growth, and the shares rose about 11% after hours on the results; regulation remains the recurring bear argument.",
      "Nights and seats booked, average daily rate, experiences and services uptake, hotel inventory expansion, regulatory developments in key cities, third-quarter 2026 results.",
      (5, 3, 5, 5)),

    C("SPOT", "Spotify Technology S.A.", "software", "Stockholm, Sweden", 2006,
      "Gustav Söderström & Alex Norström", "NYSE", 680.00, 0.20, -6.0, 18.5,
      [0.15, 0.14, 0.12, 0.11, 0.10], 0.13, 0.20, 0.100, 0.030,
      "Founded in 2006 by Daniel Ek and Martin Lorentzon in Stockholm, as a legal alternative to the piracy then devastating the music industry. Ek moved to executive chairman in January 2026, with Gustav Söderström and Alex Norström becoming co-CEOs. Spotify is the largest music streaming service in the world by subscribers. Its structural challenge is that the labels own the music and take roughly two thirds of every euro of revenue, which caps gross margin.",
      [("Premium Subscriptions", 88), ("Ad-Supported", 12)],
      ["Largest music streaming subscriber base globally, with scale advantages in licensing negotiations.",
       "Price increases have been absorbed with minimal churn, demonstrating real pricing power.",
       "Podcasts and audiobooks carry better economics than music because the content costs are lower."],
      ["The three major labels control the catalogue and take the majority of revenue — a permanent structural constraint.",
       "Apple and Amazon can subsidise competing services as features of larger ecosystems.",
       "Years of heavy podcast investment produced disappointing returns and required painful write-downs."],
      "The margin story has continued: gross margin reached a record 33.4% in the second quarter of 2026 and operating income rose 61% to EUR 655 million as Premium subscribers passed 300 million. The shares still fell about 6% on the results because third-quarter profit and user guidance came in below expectations, and the label economics remain the ceiling.",
      "Monthly active user growth, premium subscriber additions, gross margin, price increase absorption, third-quarter 2026 results against 305 million subscriber and EUR 670 million operating income guidance.",
      (4, 4, 4, 3)),

    C("APP", "AppLovin Corporation", "software", "Palo Alto, California, USA", 2012,
      "Adam Foroughi", "Nasdaq", 470.00, 0.34, 3.0, 5.2,
      [0.24, 0.20, 0.17, 0.14, 0.12], 0.40, 0.45, 0.115, 0.030,
      "Founded in 2012 by Adam Foroughi, who still runs it. AppLovin began by helping mobile game developers acquire users, then built Axon, a machine learning advertising engine that predicts which users will spend money in an app. Axon proved good enough that the company has been divesting its own games studios to focus purely on the advertising platform, and is extending it to e-commerce advertisers outside gaming.",
      [("Advertising", 78), ("Apps", 22)],
      ["Axon has demonstrably outperformed competing mobile ad engines on return on ad spend.",
       "Extending beyond gaming into e-commerce advertising multiplies the addressable market.",
       "Exceptional free cash flow margins for an advertising technology business."],
      ["Heavily dependent on mobile gaming advertising budgets, which are discretionary.",
       "Short-seller reports have questioned attribution methodology and data practices.",
       "The stock has re-rated enormously, so expectations embedded in the price are demanding."],
      "One of the most polarising names in software. Second-quarter 2026 revenue rose 53% to $1.92 billion at an 84% adjusted EBITDA margin, but it fell slightly short of estimates and third-quarter guidance trailed projections, sending the shares down as much as 21%.",
      "Advertising revenue growth, e-commerce advertiser adoption, third-quarter 2026 results against the $2.055-2.085 billion revenue guide, response to short-seller claims.",
      (4, 5, 4, 3)),

    C("FTNT", "Fortinet, Inc.", "software", "Sunnyvale, California, USA", 2000,
      "Ken Xie", "Nasdaq", 98.00, 0.77, -3.0, 6.3,
      [0.13, 0.12, 0.11, 0.10, 0.09], 0.33, 0.36, 0.095, 0.028,
      "Founded in 2000 by Ken Xie, who had previously founded NetScreen, and his brother Michael Xie. Ken Xie still runs it. Fortinet sells network security, and its differentiator is hardware: it designs its own security processors, which let its firewalls handle inspection workloads far more efficiently than competitors running on general-purpose chips. That translates into better price-performance, particularly for mid-sized customers and distributed branch networks.",
      [("Unified SASE", 24), ("Secure Networking", 62), ("Security Operations", 14)],
      ["Custom silicon gives a genuine cost and performance advantage that software-only competitors cannot match.",
       "Very strong operating margins, among the best in cybersecurity.",
       "Large installed base of firewall appliances creates a natural refresh cycle."],
      ["The post-pandemic firewall refresh cycle pulled demand forward, creating a difficult comparison period.",
       "More hardware-dependent than competitors, which the market rewards with a lower multiple.",
       "Palo Alto, Zscaler and Microsoft all compete for the same security budgets."],
      "Viewed as a high-margin operator working through a digestion period after the refresh pull-forward.",
      "Billings growth, product revenue recovery, SASE adoption, operating margin.",
      (4, 3, 5, 4)),

    C("ADSK", "Autodesk, Inc.", "software", "San Francisco, California, USA", 1982,
      "Andrew Anagnost", "Nasdaq", 315.00, 0.215, 1.0, 6.4,
      [0.11, 0.11, 0.10, 0.09, 0.08], 0.30, 0.34, 0.090, 0.028,
      "Founded in 1982 by John Walker and twelve co-authors, and defined by AutoCAD, which became the standard for computer-aided design. Andrew Anagnost has been CEO since 2017 and led the shift from perpetual licences to subscriptions. Autodesk's software is used to design buildings, infrastructure, manufactured products and visual effects, and its file formats are so entrenched in architecture and construction that they function as an industry standard. In August 2026 it closed the $3.6 billion cash acquisition of MaintainX, whose software manages maintenance and work orders, extending it from design into the operation of physical assets.",
      [("Architecture, Engineering & Construction", 48), ("Manufacturing", 21), ("Media & Entertainment", 8), ("Other", 23)],
      ["AutoCAD and Revit are industry standards taught in universities, creating generational lock-in.",
       "Construction digitisation is a genuine multi-decade tailwind and Autodesk is positioned at its centre.",
       "Subscription transition is complete, so revenue is now recurring and predictable."],
      ["Construction and manufacturing end markets are cyclical and sensitive to interest rates.",
   "The transition to direct customer billing has created near-term disruption with channel partners.",
   "The $3.6 billion MaintainX acquisition was not profitable when bought and dilutes operating margin in fiscal 2027, raising questions about capital allocation."],
      "Seen as a quality franchise in cyclical end markets, with construction growing above 20%. Fiscal second-quarter revenue rose 16% to $2.05 billion and beat estimates, and full-year revenue and billings guidance was raised, but the shares slipped about 5% after hours as investors weighed the margin drag from MaintainX.",
      "Billings growth, construction segment performance, MaintainX integration and margin dilution, operating margin targets, fiscal third-quarter results.",
      (5, 3, 4, 5)),

    # ===================== HEALTHCARE =====================
    C("SYK", "Stryker Corporation", "health", "Kalamazoo, Michigan, USA", 1941,
      "Kevin Lobo", "NYSE", 400.00, 0.383, 12.0, 23.0,
      [0.09, 0.09, 0.08, 0.08, 0.07], 0.17, 0.21, 0.080, 0.027,
      "Founded in 1941 by orthopaedic surgeon Homer Stryker, who invented better hospital beds and surgical tools because the existing ones frustrated him. Kevin Lobo has been CEO since 2012. Stryker makes orthopaedic implants, surgical equipment and neurotechnology products, and its Mako robotic surgery platform has become the leading system for joint replacement. Once a hospital installs a Mako, it buys Stryker implants — an unusually effective razor-and-blade structure.",
      [("MedSurg & Neurotechnology", 57), ("Orthopaedics", 33), ("Spine & Other", 10)],
      ["Mako robotic platform drives implant pull-through and locks in hospital accounts.",
       "Ageing demographics guarantee rising joint replacement procedure volumes for decades.",
       "One of the most consistent organic growth records in medical devices."],
      ["Hospital capital equipment budgets tighten when health systems come under financial pressure.",
       "Implant pricing faces steady downward pressure from hospital purchasing groups.",
       "Consistently expensive relative to medical device peers."],
      "Regarded as the best growth compounder in medical devices. The pushback is valuation rather than execution.",
      "Organic revenue growth, Mako installations, procedure volumes, capital equipment orders.",
      (5, 4, 4, 5)),

    C("BSX", "Boston Scientific Corporation", "health", "Marlborough, Massachusetts, USA", 1979,
      "Michael Mahoney", "NYSE", 110.00, 1.48, 9.0, 17.5,
      [0.12, 0.11, 0.10, 0.09, 0.08], 0.18, 0.22, 0.080, 0.027,
      "Founded in 1979 by John Abele and Peter Nicholas to commercialise less-invasive medical devices. Michael Mahoney has been CEO since 2012 and has overseen one of the strongest turnarounds in the sector. Boston Scientific makes cardiovascular devices, endoscopy equipment and urology products. Its Farapulse pulsed field ablation system, used to treat atrial fibrillation, has been the fastest device launch in the company's history.",
      [("Cardiovascular", 63), ("MedSurg", 37)],
      ["Farapulse remains a leading pulsed field ablation system, and international electrophysiology sales grew 23% in the second quarter of 2026.",
   "A restructuring programme targeting roughly $500 million of run-rate savings gives management a lever on margins while growth slows.",
   "Well-executed acquisition strategy that has repeatedly bought growth at reasonable prices."],
      ["Medtronic, Johnson & Johnson and Abbott are taking US pulsed field ablation share, and US electrophysiology sales grew only 3% in the second quarter of 2026.",
   "Watchman demand has slowed sharply, with US stand-alone procedures down in the low teens in the second quarter of 2026 after new stroke-risk evidence reduced referrals.",
   "An August 2026 cyberattack disrupted manufacturing and order shipments, and the company has said it will no longer meet its third-quarter and full-year 2026 guidance."],
      "Sentiment has reversed sharply: the shares lost more than half their value between late December 2025 and September 2026 as US electrophysiology share losses and a Watchman slowdown forced repeated guidance cuts. The August 2026 cyberattack added a further setback, although Barclays upgraded the stock to hold in October and the chief executive bought about $9 million of shares.",
      "Third-quarter results on 28 October 2026 and quantified cyberattack impact, US electrophysiology share trends, Watchman procedure recovery, restructuring savings.",
      (5, 5, 4, 5)),

    C("CI", "The Cigna Group", "health", "Bloomfield, Connecticut, USA", 1982,
      "Brian Evanko", "NYSE", 310.00, 0.27, 30.0, 250.0,
      [0.06, 0.06, 0.05, 0.05, 0.05], 0.022, 0.027, 0.085, 0.026,
      "Formed in 1982 by the merger of Connecticut General and INA, with roots back to 1792. Brian Evanko succeeded David Cordani, chief executive since 2009, as CEO in July 2026, with Cordani becoming executive chair. The Cigna Group has two very different businesses: Evernorth, which contains Express Scripts, one of the three pharmacy benefit managers that negotiate drug prices for most Americans, and Cigna Healthcare, a commercial health insurer. Evernorth generates most of the profit and is where the political risk sits.",
      [("Evernorth Health Services", 78), ("Cigna Healthcare", 22)],
      ["Express Scripts is one of three pharmacy benefit managers controlling the vast majority of US prescription volume.",
       "Exited Medicare Advantage, avoiding the utilisation problems that have hurt peers.",
       "Specialty pharmacy is a large and structurally growing profit pool."],
      ["Pharmacy benefit managers face intense bipartisan political scrutiny over drug pricing and rebate practices.",
   "PBM reform passed in February 2026 delinks PBM pay from drug prices in Medicare Part D and requires full rebate pass-through for commercial plans, mostly from 2028 or 2029.",
   "Commercial insurance is exposed to employment levels and medical cost trends."],
      "Cheap relative to peers, with the discount reflecting political risk to the PBM model rather than operational problems. At its September 2026 investor day the new management team reaffirmed 2026 adjusted EPS of at least $30.45 and set a 10-14% annual EPS growth target through 2030, but the shares fell about 3% because the outlook was not raised.",
      "Implementation of PBM delinking and rebate pass-through rules, medical care ratio, Evernorth earnings growth, specialty pharmacy trends, $3 billion productivity programme.",
      (4, 3, 3, 3)),

    C("CVS", "CVS Health Corporation", "health", "Woonsocket, Rhode Island, USA", 1963,
      "David Joyner", "NYSE", 78.00, 1.26, 58.0, 380.0,
      [0.04, 0.04, 0.04, 0.03, 0.03], 0.018, 0.024, 0.090, 0.024,
      "Founded in 1963 as Consumer Value Stores. David Joyner became CEO in October 2024 after a period of severe underperformance. CVS is unusually vertically integrated: it owns retail pharmacies, Caremark (a large pharmacy benefit manager), and Aetna (a major health insurer). The theory is that owning the whole chain lowers costs; the practice has been that problems in any one part drag down the whole.",
      [("Health Services (Caremark)", 47), ("Health Care Benefits (Aetna)", 33), ("Pharmacy & Consumer Wellness", 20)],
      ["Vertical integration across pharmacy, benefits management and insurance is genuinely difficult to replicate.",
       "Around 9,000 retail locations put a pharmacy within reach of most of the US population.",
       "Valuation is depressed enough that modest operational improvement could re-rate the shares."],
      ["Medicare Advantage utilisation ran far above expectations, causing repeated guidance cuts, and management still describes cost trends as elevated.",
   "Retail pharmacy faces structural pressure from mail order and Amazon.",
   "Very heavy debt load following the Aetna acquisition constrains flexibility."],
      "A turnaround that is now showing results: in August 2026 CVS raised full-year adjusted EPS guidance to $7.90-$8.10, crediting the Aetna margin recovery plan. Management kept a cautious stance for the rest of the year because of elevated cost trends, so the durability of the Medicare Advantage margin recovery remains the key variable.",
      "Third-quarter results, Medicare Advantage medical loss ratio, 2027 star ratings, Caremark client retention, debt reduction.",
      (3, 2, 2, 3)),

    C("MCK", "McKesson Corporation", "health", "Irving, Texas, USA", 1833,
      "Brian Tyler", "NYSE", 730.00, 0.125, 5.0, 330.0,
      [0.08, 0.07, 0.07, 0.06, 0.06], 0.011, 0.014, 0.085, 0.026,
      "Founded in 1833 in New York as a wholesale drug importer, making it one of the oldest companies in American healthcare. Brian Tyler has been CEO since 2019. McKesson distributes pharmaceuticals to pharmacies, hospitals and physician practices, moving an enormous volume of product on very thin margins. Its oncology business, which supports community cancer practices, is the higher-margin growth engine.",
      [("US Pharmaceutical", 89), ("Prescription Technology", 5), ("Medical-Surgical & International", 6)],
      ["Distribution is an oligopoly of three, with scale barriers that make new entry impractical.",
       "Oncology and specialty distribution carry better margins than commodity drug distribution.",
       "GLP-1 drug volumes have driven substantial revenue growth through the distribution network."],
      ["Operating margins are around 1%, so small disruptions have outsized effects.",
       "Opioid litigation settlements represent a multi-billion dollar obligation over many years.",
       "Revenue growth is driven by drug prices and volumes it does not control."],
      "Viewed as a steady, defensive compounder. In August 2026 McKesson raised fiscal 2027 adjusted EPS guidance to $44.20-$45.00 after a 20% rise in first-quarter adjusted EPS, with Oncology & Multispecialty revenue up 33%. The planned separation of Medical-Surgical, now named Wellverse, would leave a more focused distribution and specialty business.",
      "Wellverse (Medical-Surgical) separation, oncology platform expansion, pharmaceutical revenue growth, opioid settlement payments, GLP-1 volumes.",
      (4, 3, 4, 4)),

    C("HCA", "HCA Healthcare, Inc.", "health", "Nashville, Tennessee, USA", 1968,
      "Sam Hazen", "NYSE", 420.00, 0.25, 40.0, 72.0,
      [0.06, 0.06, 0.06, 0.05, 0.05], 0.075, 0.09, 0.090, 0.026,
      "Founded in 1968 in Nashville by Thomas Frist Sr., his son and Jack Massey, creating one of the first hospital chains. Sam Hazen has been CEO since 2019. HCA operates around 190 hospitals and 2,400 care sites, concentrated in fast-growing Sun Belt markets including Texas and Florida. Hospital economics depend heavily on payer mix — how many patients are commercially insured versus on Medicare, Medicaid, or uninsured.",
      [("Inpatient Services", 45), ("Outpatient Services", 40), ("Other Revenue", 15)],
      ["Scale gives real negotiating leverage with commercial insurers and suppliers.",
       "Concentrated in Sun Belt markets with above-average population growth.",
       "Aggressive share repurchase programme has substantially reduced the share count."],
      ["Payer mix can deteriorate quickly if unemployment rises or subsidies lapse.",
       "Labour costs, particularly nursing, have risen structurally since the pandemic.",
       "Very high leverage, which magnifies both good and bad operating outcomes."],
      "Regarded as the best-run hospital operator. Payer mix and policy changes to insurance subsidies drive the debate.",
      "Same-facility admissions, payer mix, labour cost per adjusted admission, ACA subsidy legislation.",
      (4, 3, 2, 4)),

    C("ZTS", "Zoetis Inc.", "health", "Parsippany, New Jersey, USA", 1952,
      "Kristin Peck", "NYSE", 160.00, 0.45, 5.0, 9.4,
      [0.08, 0.08, 0.07, 0.07, 0.06], 0.26, 0.30, 0.080, 0.028,
      "Spun out of Pfizer in 2013, with roots in Pfizer's animal health division dating to 1952. Kristin Peck has been CEO since 2020. Zoetis is the largest animal health company in the world, making vaccines, parasiticides and medicines for both pets and livestock. The companion animal business is the attractive part: pet owners increasingly treat animals as family members and spend accordingly, and veterinary medicines face no insurance reimbursement pressure.",
      [("Companion Animal", 65), ("Livestock", 34), ("Other", 1)],
      ["Pet humanisation is a durable spending trend largely insulated from economic cycles.",
       "No payer or reimbursement pressure, unlike human pharmaceuticals — owners pay directly.",
       "Librela and Solensia, monoclonal antibodies for osteoarthritis pain, opened a genuinely new category."],
      ["US companion animal sales fell 11% in the second quarter of 2026 on softer demand, price sensitivity, competition and generic pressure on Cerenia and Convenia, prompting a second guidance cut in August 2026.",
   "Livestock demand is tied to protein prices and farm economics.",
   "Lower US Librela sales, following reports of adverse events, show prescriber caution is now affecting revenue."],
      "Once considered a high-quality, defensive compounder, Zoetis is now viewed as a business facing a more pressured US companion animal market. In August 2026 it cut 2026 guidance to revenue of $9.12-$9.32bn and adjusted EPS of $6.15-$6.25, from $9.68-$9.96bn and $6.85-$7.00, and the debate is whether the US slowdown is cyclical or competitive.",
      "Third-quarter results, US companion animal trends, Librela prescription trends, Lenivia and Portela launches, livestock demand.",
      (5, 4, 4, 5)),

    # ===================== FINANCIALS =====================
    C("MMC", "Marsh & McLennan Companies, Inc.", "financials", "New York, New York, USA", 1871,
      "John Doyle", "NYSE", 220.00, 0.49, 18.0, 25.5,
      [0.07, 0.07, 0.06, 0.06, 0.05], 0.21, 0.24, 0.080, 0.027,
      "Founded in 1871 in Chicago. John Doyle has been CEO since 2023. Marsh McLennan is the largest insurance broker in the world, placing risk between companies and insurers and collecting commissions, plus Mercer in employee benefits consulting and Oliver Wyman in management consulting. Broking is an unusually good business: it takes a share of premium without underwriting any risk, so it profits from rising insurance prices without bearing the losses.",
      [("Risk & Insurance Services", 63), ("Consulting", 37)],
      ["Earns commission on premium without taking underwriting risk — all the upside of hard markets, none of the losses.",
       "Highly recurring revenue as insurance programmes renew annually.",
       "Genuine expertise barriers in complex commercial and specialty risk placement."],
      ["Commission revenue falls when insurance pricing softens.",
       "Consulting revenue is discretionary and cyclical.",
       "Regulatory scrutiny of broker compensation and contingent commissions recurs periodically."],
      "Regarded as one of the highest-quality business models in financials, and priced accordingly.",
      "Third-quarter results on 15 October 2026, organic revenue growth, insurance pricing cycle, consulting demand, acquisition activity.",
      (5, 3, 4, 5)),

    C("ICE", "Intercontinental Exchange, Inc.", "financials", "Atlanta, Georgia, USA", 2000,
      "Jeffrey Sprecher", "NYSE", 175.00, 0.575, 20.0, 9.8,
      [0.06, 0.06, 0.06, 0.05, 0.05], 0.32, 0.36, 0.080, 0.027,
      "Founded in 2000 by Jeffrey Sprecher, who bought a small Atlanta power exchange for one dollar and built it into a group that owns the New York Stock Exchange. Sprecher still runs it. ICE operates exchanges and clearing houses for energy, commodities and equities, sells fixed income data and analytics, and owns a large mortgage technology business built through the Ellie Mae and Black Knight acquisitions. In July 2026 it agreed to buy MarketAxess for about $5.7bn in cash, with closing expected in the first half of 2027.",
      [("Exchanges", 57), ("Fixed Income & Data Services", 24), ("Mortgage Technology", 19)],
      ["Exchanges and clearing houses are natural monopolies with regulatory moats.",
       "Trading volumes rise with volatility, making the business partly counter-cyclical.",
       "Recurring data and analytics subscription revenue smooths transaction volatility."],
      ["Mortgage technology revenue is tied to origination volumes, which collapse when rates rise.",
   "Heavy debt from the Black Knight acquisition, with further debt to be issued to fund the roughly $5.7bn MarketAxess purchase.",
   "Regulatory scrutiny of exchange market data pricing is persistent, and the MarketAxess deal is under US antitrust review."],
      "The exchange business is universally admired, and trading volumes were strong through the third quarter of 2026. The mortgage technology business remains the contested part, and the debt-funded MarketAxess acquisition adds an integration and regulatory question.",
      "Third-quarter results, MarketAxess antitrust review and shareholder vote on 29 October 2026, mortgage origination volumes, recurring revenue growth, debt reduction.",
      (5, 3, 3, 5)),

    C("CME", "CME Group Inc.", "financials", "Chicago, Illinois, USA", 1898,
      "Terrence Duffy", "Nasdaq", 285.00, 0.36, -2.0, 6.3,
      [0.06, 0.05, 0.05, 0.05, 0.04], 0.42, 0.45, 0.075, 0.026,
      "Traces to the Chicago Butter and Egg Board founded in 1898. Terrence Duffy has been CEO since 2016, and President and CFO Lynne Fitzpatrick is due to succeed him in March 2027. CME operates the largest derivatives exchange in the world, where interest rate futures, equity index futures, energy and agricultural contracts trade. Its interest rate complex is effectively the venue where the world hedges rate risk, and open interest in those contracts is very difficult for a competitor to displace.",
      [("Interest Rates", 33), ("Equity Indexes", 20), ("Energy", 17), ("Agricultural & FX", 18), ("Market Data", 12)],
      ["Liquidity concentration is self-reinforcing — traders go where the open interest is, which keeps it there.",
       "Operating margins above 60%, among the highest of any large listed company.",
       "Volatility drives volume, so the business performs well precisely when markets are stressed."],
      ["Volumes fall in calm, low-volatility markets.",
       "A prolonged period of stable interest rates reduces hedging demand.",
       "Competitors periodically attempt to launch rival contracts, though rarely with success."],
      "Viewed as a near-monopoly with exceptional margins. Record average daily volume of 29.4 million contracts in the third quarter of 2026, up 16%, supports the volume picture, and the debate remains about volume cyclicality rather than competitive position.",
      "Third-quarter results, average daily volume, rate volatility, CME Securities Clearing launch in December 2026, CEO transition in March 2027.",
      (5, 3, 5, 5)),

    C("COF", "Capital One Financial Corporation", "financials", "McLean, Virginia, USA", 1994,
      "Richard Fairbank", "NYSE", 215.00, 0.64, 0.0, 45.0,
      [0.09, 0.07, 0.06, 0.05, 0.05], 0.19, 0.24, 0.105, 0.026,
      "Founded in 1994 by Richard Fairbank and Nigel Morris, who pioneered using data analysis to price credit card risk at a time when the industry offered one rate to everyone. Fairbank still runs it. Capital One is a major US credit card issuer and bank, and its 2025 acquisition of Discover added a payments network — making it the only large US issuer that also owns the rails its cards run on.",
      [("Credit Card", 65), ("Consumer Banking", 22), ("Commercial Banking", 13)],
      ["Owning the Discover network means capturing interchange economics rather than paying them to Visa or Mastercard.",
       "Decades of proprietary credit data give a genuine underwriting edge.",
       "The Discover deal created meaningful scale in a consolidating card market."],
      ["Credit card losses rise sharply in a recession, and subprime exposure amplifies that.",
       "Integrating Discover is a large and complex undertaking.",
       "Consumer credit quality has been deteriorating from unusually strong post-pandemic levels."],
      "The Discover acquisition is the whole story — network economics against integration and credit risk.",
      "Net charge-off rate, Discover integration milestones, card loan growth, network volume.",
      (4, 4, 3, 4)),

    C("BX", "Blackstone Inc.", "financials", "New York, New York, USA", 1985,
      "Stephen Schwarzman", "NYSE", 160.00, 1.22, 0.0, 11.5,
      [0.11, 0.10, 0.09, 0.08, 0.07], 0.33, 0.37, 0.100, 0.028,
      "Founded in 1985 by Stephen Schwarzman and Peter Peterson with $400,000. Schwarzman still runs it. Blackstone is the largest alternative asset manager in the world, investing in private equity, real estate, credit and infrastructure on behalf of pension funds, sovereign wealth funds and, increasingly, individual investors. It earns management fees on committed capital plus performance fees on gains, and its real estate business is the largest of any private owner.",
      [("Real Estate", 30), ("Private Equity", 28), ("Credit & Insurance", 30), ("Hedge Fund Solutions", 12)],
      ["Management fees on long-locked capital produce highly predictable base revenue.",
       "The private wealth channel is a genuinely large new source of capital that has barely been tapped.",
       "Scale allows participation in transactions no competitor can finance alone."],
      ["Performance fees are volatile and depend on realising investments at good prices.",
       "Commercial real estate, historically its strongest area, has faced severe valuation pressure.",
       "Higher interest rates raise financing costs across every leveraged strategy."],
      "Seen as the highest-quality alternative manager. Real estate marks and realisation activity drive most of the debate.",
      "Fee-related earnings, fundraising, realisation activity, real estate portfolio marks.",
      (5, 4, 3, 5)),

    C("MCO", "Moody's Corporation", "financials", "New York, New York, USA", 1909,
      "Robert Fauber", "NYSE", 510.00, 0.18, 5.0, 7.4,
      [0.08, 0.08, 0.07, 0.07, 0.06], 0.32, 0.36, 0.080, 0.028,
      "Founded in 1909 when John Moody published the first bond ratings manual. Robert Fauber has been CEO since 2021. Moody's is one of the two dominant credit rating agencies, and separately runs Moody's Analytics, which sells risk data, models and software. Regulatory frameworks worldwide reference credit ratings directly, which means issuers cannot practically avoid obtaining one.",
      [("Moody's Investors Service", 53), ("Moody's Analytics", 47)],
      ["A regulated duopoly with S&P, protected by regulatory reliance on ratings.",
       "Moody's Analytics provides recurring subscription revenue that offsets ratings cyclicality.",
       "Debt issuance grows structurally over time as global credit markets expand."],
      ["Ratings revenue swings with debt issuance volumes, which are highly rate-sensitive.",
       "Periodic regulatory pressure on the issuer-pays model that funds the agencies.",
       "The valuation consistently reflects a high-quality premium."],
      "Universally regarded as an exceptional business model. Issuance volumes drive the near-term earnings debate.",
      "Debt issuance volumes, Analytics recurring revenue growth, transactional versus recurring mix, regulatory developments.",
      (5, 4, 4, 5)),

    C("KKR", "KKR & Co. Inc.", "financials", "New York, New York, USA", 1976,
      "Joseph Bae & Scott Nuttall", "NYSE", 140.00, 0.89, 0.0, 14.0,
      [0.12, 0.11, 0.10, 0.09, 0.08], 0.30, 0.35, 0.105, 0.028,
      "Founded in 1976 by Jerome Kohlberg and cousins Henry Kravis and George Roberts, and made famous by the 1988 leveraged buyout of RJR Nabisco. Joseph Bae and Scott Nuttall became co-CEOs in 2021. KKR invests in private equity, infrastructure, real estate and credit, and has increasingly used its own balance sheet to invest alongside clients — plus Global Atlantic, an insurance business that provides permanent capital.",
      [("Asset Management", 55), ("Insurance (Global Atlantic)", 33), ("Strategic Holdings", 12)],
      ["Balance sheet investing means KKR captures investment returns directly, not just fees.",
       "Global Atlantic provides permanent capital that does not need to be raised repeatedly.",
       "Infrastructure and Asia strategies are among the fastest-growing areas in private markets."],
      ["Performance fee income is inherently volatile and depends on exit markets.",
       "Balance sheet investments introduce mark-to-market earnings volatility that pure fee managers avoid.",
       "Leveraged buyouts are directly harmed by higher financing costs."],
      "Viewed as the most balance-sheet-heavy of the large alternative managers, with higher potential return and more earnings volatility. The $17bn sale of USI Insurance Services to Aon, agreed in August 2026, is expected to bring KKR about $3.3bn of after-tax proceeds and more than $2.00 per share of adjusted net income if it closes, a clear example of the realisation upside.",
      "Third-quarter results, closing of the USI sale to Aon, fee-related earnings, capital deployment, realisation activity, Global Atlantic spread income.",
      (5, 4, 3, 5)),

    # ===================== CONSUMER, RETAIL & LUXURY =====================
    C("CL", "Colgate-Palmolive Company", "consumer", "New York, New York, USA", 1806,
      "Noel Wallace", "NYSE", 90.00, 0.81, 7.0, 20.1,
      [0.03, 0.04, 0.04, 0.04, 0.03], 0.17, 0.20, 0.075, 0.024,
      "Founded in 1806 by William Colgate as a soap and candle business in New York. Noel Wallace has been CEO since 2019. Colgate sells toothpaste, toothbrushes, soap and home care products, and owns Hill's Pet Nutrition, a premium veterinary-recommended pet food business that has become the growth engine. Colgate toothpaste holds roughly 40% global market share, an extraordinary position for a consumer category.",
      [("Oral Care", 40), ("Personal Care", 18), ("Home Care", 19), ("Hill's Pet Nutrition", 23)],
      ["Around 40% global toothpaste share, with particular strength in emerging markets.",
       "Hill's Pet Nutrition benefits from the same pet humanisation trend as Zoetis, with better growth than the core business.",
       "Oral care is a daily habit purchase, about as recession-resistant as consumer spending gets."],
      ["Heavy emerging market exposure creates significant currency translation risk.",
       "Private label competition in developed markets pressures volumes.",
       "Growth has come more from price than volume, which is not indefinitely sustainable."],
      "A defensive staple where the debate is whether Hill's growth can offset a slow-growing core.",
      "Organic sales growth, volume versus price mix, Hill's growth rate, currency impact.",
      (5, 2, 4, 5)),

    C("CMG", "Chipotle Mexican Grill, Inc.", "consumer", "Newport Beach, California, USA", 1993,
      "Scott Boatwright", "NYSE", 46.00, 1.36, -2.0, 11.8,
      [0.11, 0.11, 0.10, 0.09, 0.08], 0.16, 0.19, 0.090, 0.028,
      "Founded in 1993 by Steve Ells, a classically trained chef, with a loan from his father. Scott Boatwright became CEO in 2024 after Brian Niccol left for Starbucks. Chipotle operates around 3,700 restaurants and owns nearly all of them rather than franchising, which means it captures full restaurant economics but funds all growth itself. Its digital ordering and second make-line build-out substantially raised throughput per restaurant.",
      [("Food & Beverage Revenue", 98), ("Delivery Service & Other", 2)],
      ["Company-owned model captures full restaurant-level margins rather than a franchise royalty.",
       "Substantial unit growth runway — management targets roughly 7,000 North American restaurants.",
       "Digital ordering is a large share of sales and carries better throughput economics."],
      ["Very high multiple that assumes many years of continued unit growth and comparable sales.",
       "Food and labour cost inflation compresses restaurant margins directly.",
       "Portion size controversies demonstrated how sensitive the brand is to value perception."],
      "A growth story where nobody disputes the concept and everybody debates the price.",
      "Comparable restaurant sales, transaction growth, new unit openings, restaurant-level margin.",
      (5, 4, 5, 4)),

    C("MAR", "Marriott International, Inc.", "consumer", "Bethesda, Maryland, USA", 1927,
      "Anthony Capuano", "Nasdaq", 295.00, 0.27, 13.0, 25.5,
      [0.07, 0.07, 0.06, 0.06, 0.05], 0.12, 0.15, 0.085, 0.026,
      "Founded in 1927 by J. Willard and Alice Marriott as a root beer stand in Washington DC. Anthony Capuano has been CEO since 2021. Marriott is the largest hotel company in the world by rooms, but owns almost none of them — it franchises and manages properties owned by others, collecting fees based on revenue. That asset-light structure means very high returns on capital and much lower downside in a travel downturn than an owner would face.",
      [("Franchise Fees", 55), ("Management Fees", 15), ("Owned & Leased", 8), ("Cost Reimbursements Net", 22)],
      ["Asset-light franchising produces high returns on capital and low capital intensity.",
       "Bonvoy loyalty programme has well over 200 million members and drives direct bookings.",
       "Pipeline of committed new rooms provides visible multi-year unit growth."],
      ["Travel demand is cyclical, and fee revenue falls with hotel revenue per available room.",
       "Hotel owners, who fund the capital, can push back on fee structures.",
       "Alternative accommodation from Airbnb competes for leisure travellers."],
      "Regarded as a high-quality asset-light compounder. Second-quarter 2026 results in August beat on earnings, with worldwide RevPAR up 3.4% and full-year RevPAR guidance raised to 3.0-3.5%, but international RevPAR fell 0.5% on Middle East conflict headwinds. The debate is still where normalised travel demand settles.",
      "Revenue per available room, international demand and Middle East exposure, net rooms growth, pipeline conversions, capital returns.",
      (5, 3, 4, 5)),

    C("ORLY", "O'Reilly Automotive, Inc.", "consumer", "Springfield, Missouri, USA", 1957,
      "Brad Beckham", "Nasdaq", 100.00, 0.81, 6.0, 17.0,
      [0.06, 0.06, 0.06, 0.05, 0.05], 0.14, 0.16, 0.080, 0.026,
      "Founded in 1957 by the O'Reilly family in Springfield, Missouri. Brad Beckham became CEO in 2024. O'Reilly sells automotive parts through around 6,300 stores to both professional mechanics and consumers doing their own repairs. The dual-market model is the key: professional customers need parts delivered within minutes, which requires a dense store and distribution network that online retailers cannot economically replicate.",
      [("Do-It-Yourself", 55), ("Professional Installer", 45)],
      ["Same-day parts delivery to professional mechanics is a genuine barrier to e-commerce competition.",
       "An ageing US vehicle fleet, with average age above twelve years, structurally increases repair demand.",
       "One of the most aggressive and consistent share repurchase programmes in US retail."],
      ["Electric vehicles need fewer replacement parts, a slow but real long-term headwind.",
       "Amazon and online parts retailers keep improving in the do-it-yourself segment.",
       "The valuation has expanded considerably for a business growing at mid-single digits."],
      "Widely respected as an exceptionally well-run retailer. EV adoption is the long-term structural question.",
      "Comparable store sales, professional versus DIY mix, average vehicle age data, buyback pace.",
      (5, 3, 4, 5)),

    C("KR", "The Kroger Co.", "consumer", "Cincinnati, Ohio, USA", 1883,
      "Greg Foran", "NYSE", 72.00, 0.66, 18.0, 150.0,
      [0.02, 0.03, 0.03, 0.03, 0.02], 0.023, 0.028, 0.080, 0.022,
      "Founded in 1883 by Barney Kroger, who invested his life savings of $372 in a Cincinnati grocery store. Greg Foran, a former Walmart executive and Air New Zealand chief executive, became CEO in February 2026, with Ronald Sargent remaining chairman. Kroger is one of the largest US grocers, operating around 2,700 stores under Kroger, Ralphs, Fred Meyer and other regional banners. Its proposed merger with Albertsons was blocked by courts in 2024, forcing a return to organic strategy.",
      [("Non-Perishable", 47), ("Fresh", 25), ("Pharmacy & Fuel", 22), ("Other", 6)],
      ["Grocery is genuinely recession-resistant — people eat regardless of the economy.",
       "Own-brand products carry higher margins and have gained share as consumers seek value.",
       "Retail media, selling advertising to suppliers, is a small but very high-margin growth area."],
      ["Grocery operates on razor-thin margins, around 2%, leaving little room for error.",
       "Walmart, Costco and Aldi all compete aggressively on price.",
       "The blocked Albertsons merger removed the scale strategy management had been pursuing."],
      "A defensive holding in a structurally low-margin industry, now under a new chief executive. The September 2026 cut to full-year identical sales guidance, to 0.2%-0.8%, prompted target cuts from Citi and Deutsche Bank even though earnings guidance held. Retail media, where profit rose 24% in the second quarter, remains the main margin improvement hope.",
      "Investor update meeting on 20 October 2026, identical sales excluding fuel, completion of the $2 billion buyback, retail media growth, gross margin.",
      (3, 2, 3, 3)),

    C("MNST", "Monster Beverage Corporation", "consumer", "Corona, California, USA", 1935,
      "Hilton Schlosberg", "Nasdaq", 31.0, 1.94, -1.5, 7.6,
      [0.08, 0.08, 0.07, 0.07, 0.06], 0.24, 0.27, 0.085, 0.028,
      "Traces to Hansen's, a 1935 juice company, transformed after Rodney Sacks and Hilton Schlosberg acquired it in 1992 and launched Monster Energy in 2002. Schlosberg is now CEO. Monster is the second largest energy drink brand globally behind Red Bull, and its distribution agreement with Coca-Cola gives it access to a global network it could never have built alone. Energy drinks remain one of the fastest-growing beverage categories.",
      [("Monster Energy Drinks", 91), ("Strategic Brands", 6), ("Alcohol Brands & Other", 3)],
      ["The Coca-Cola distribution partnership provides global reach with no capital investment.",
       "Energy drinks continue to take share from carbonated soft drinks, particularly among younger consumers.",
       "Very high margins and a net cash balance sheet."],
      ["Celsius and other entrants have taken meaningful share in the US.",
   "Aluminium can costs are expected to keep rising through 2026, and the company is relying on selective US price increases in the fourth quarter to protect gross margin.",
   "Regulatory attention to caffeine content in drinks marketed to young people is a recurring risk."],
      "Second-quarter 2026 results reassured on growth, with net sales up 20.2% and international sales now about 46% of the total, though higher marketing and freight costs weighed on operating margin. International expansion and pricing against aluminium inflation are the main debates.",
      "US scanner data share trends, international growth, Q4 2026 US price increases, aluminium costs, gross margin.",
      (5, 4, 5, 4)),

    C("YUM", "Yum! Brands, Inc.", "consumer", "Louisville, Kentucky, USA", 1997,
      "Chris Turner", "NYSE", 150.00, 0.28, 11.0, 7.6,
      [0.06, 0.06, 0.06, 0.05, 0.05], 0.25, 0.28, 0.085, 0.026,
      "Spun out of PepsiCo in 1997 as Tricon Global, renamed Yum! Brands in 2002. Chris Turner became CEO in October 2025. Yum owns KFC, Taco Bell and Habit Burger, operating more than 44,000 restaurants in 151 countries and territories, after selling Pizza Hut in 2026 to LongRange Capital and, for mainland China, to Yum China for a combined $2.7 billion. Almost all restaurants are franchised, meaning Yum collects royalties on system sales without funding the restaurants — a very high-margin, low-capital model.",
      [("KFC", 60), ("Taco Bell", 38), ("Habit Burger", 2)],
      ["Almost entirely franchised, producing high margins and minimal capital requirements.",
       "Taco Bell has been one of the strongest performers in US quick service for several years.",
       "KFC has enormous international scale, particularly in China through its licensee."],
      ["A cyclospora outbreak linked to Taco Bell in July 2026 has drawn significant attention; food safety incidents can damage a quick-service brand for far longer than the outbreak itself lasts.",
   "With Pizza Hut sold, earnings are more concentrated in KFC and Taco Bell, so weakness at either brand now carries more weight.",
   "International exposure brings currency and geopolitical risk, including boycott impacts in some markets."],
      "With Pizza Hut sold for a combined $2.7 billion, Yum is now essentially a KFC and Taco Bell story. The near-term question is how quickly Taco Bell recovers from the July 2026 cyclospora outbreak; unit growth remains the long-term driver.",
      "Q3 2026 results, Taco Bell same-store sales recovery, use of Pizza Hut sale proceeds, KFC net new unit openings, franchisee health.",
      (4, 3, 3, 5)),

    # ===================== ENERGY & MATERIALS =====================
    C("MPC", "Marathon Petroleum Corporation", "energy", "Findlay, Ohio, USA", 2011,
      "Maryann Mannen", "NYSE", 185.00, 0.31, 25.0, 140.0,
      [0.01, 0.02, 0.02, 0.02, 0.02], 0.035, 0.045, 0.095, 0.020,
      "Spun out of Marathon Oil in 2011, with refining roots dating to 1887. Maryann Mannen became CEO in 2024. Marathon Petroleum is the largest US refiner by capacity, running thirteen refineries, and holds a controlling stake in MPLX, a midstream partnership that provides steadier fee-based cash flow. It also operates the Speedway-branded fuel supply relationship following that chain's sale.",
      [("Refining & Marketing", 85), ("Midstream (MPLX)", 15)],
      ["Largest US refining capacity, with scale advantages in crude sourcing and product distribution.",
       "MPLX distributions provide predictable cash flow largely independent of refining margins.",
       "Among the most aggressive capital return programmes in the sector."],
      ["Refining margins are extremely volatile and outside management control; the G7 emergency release of oil and diesel stocks agreed in October 2026 is explicitly aimed at narrowing today's unusually wide product spreads.",
   "Long-term fuel demand faces pressure from vehicle electrification.",
   "Policy intervention is a live risk: a temporary US diesel-export restriction was floated by lawmakers in September 2026 and weighed on refining shares while it was discussed."],
      "Held mainly for capital returns, which exceeded $2.8 billion in the second quarter of 2026, with $6.1 billion of buyback authorisation remaining at the end of June. Second-quarter EPS of $17.73 on an R&M margin of $36.33 per barrel shows how tight fuel markets have become; the debate has moved from where mid-cycle margins settle to how long the current spike lasts.",
      "Q3 2026 results on 3 November 2026, crack spreads and diesel prices, G7 emergency stock release, any US fuel-export restrictions, buyback pace, MPLX distributions.",
      (3, 2, 3, 3)),

    C("WMB", "The Williams Companies, Inc.", "energy", "Tulsa, Oklahoma, USA", 1908,
      "Chad Zamarin", "NYSE", 60.00, 1.22, 26.0, 10.8,
      [0.06, 0.06, 0.05, 0.05, 0.04], 0.28, 0.31, 0.075, 0.024,
      "Founded in 1908 by brothers Miller and David Williams as a pipeline construction business. Chad Zamarin is CEO, succeeding Alan Armstrong, who had led the company since 2011. Williams owns and operates natural gas infrastructure, most importantly Transco — the largest natural gas pipeline system in the United States, running from the Gulf Coast to New York. In September 2026 it completed the roughly $5.5 billion acquisition of Momentum Midstream, expanding its Haynesville gathering and pipeline footprint. Revenue is largely fee-based on contracted capacity rather than commodity prices, which makes cash flow far steadier than a producer's.",
      [("Transmission & Gulf of Mexico", 42), ("West", 22), ("Northeast G&P", 27), ("Gas & NGL Marketing", 9)],
      ["Transco is an irreplaceable asset — permitting a competing interstate pipeline is effectively impossible today.",
       "Fee-based contracted revenue means limited direct commodity price exposure.",
       "Data centre and LNG export demand are both driving structural natural gas growth."],
      ["High leverage, characteristic of midstream but a real constraint on flexibility; including Momentum, the company guides to leverage of about 3.75 times EBITDA for 2026.",
   "Pipeline permitting and environmental opposition can delay or block expansion projects.",
   "Long-term energy transition risk to natural gas demand."],
      "Viewed as a high-quality natural gas infrastructure holding with an attractive yield. Data centre power demand remains the main bull argument, and the Momentum acquisition, which lifted the 2026 adjusted EBITDA guidance midpoint to $8.4 billion, adds Haynesville gathering and pipeline capacity.",
      "Momentum Midstream integration, Delta Access and Shelby Trough Connector projects, Transco expansion projects, power innovation projects, LNG feedgas volumes, distributable cash flow.",
      (4, 3, 2, 5)),

    C("FCX", "Freeport-McMoRan Inc.", "energy", "Phoenix, Arizona, USA", 1912,
      "Kathleen Quirk", "NYSE", 48.00, 1.44, 4.0, 26.0,
      [0.05, 0.06, 0.05, 0.05, 0.04], 0.14, 0.18, 0.100, 0.024,
      "Traces to 1912 as Freeport Sulphur. Kathleen Quirk became CEO in 2024. Freeport is one of the largest publicly traded copper producers in the world, with major operations in Indonesia at the Grasberg mine — one of the largest copper and gold deposits ever found — plus assets in Arizona and South America. Copper is the metal most directly leveraged to electrification: grids, electric vehicles and data centres all require enormous quantities.",
      [("Copper", 74), ("Gold", 17), ("Molybdenum & Other", 9)],
      ["Copper demand is structurally supported by electrification, grid investment and data centre construction.",
       "New copper supply is scarce — permitting and building a mine takes well over a decade.",
       "Grasberg is a genuinely world-class, low-cost orebody."],
      ["Earnings are driven by the copper price, which is cyclical and outside management control.",
   "Substantial Indonesian operations carry political, permitting and resource nationalism risk, and Grasberg is still recovering from the September 2025 mud rush, with mill throughput at about 67% of pre-incident rates in the third quarter of 2026.",
   "Mining is capital-intensive with significant environmental and closure liabilities."],
      "The structural copper deficit argument is widely accepted, and realised copper prices above $6.50 per pound in the third quarter of 2026 are supporting earnings. The debate is now the pace of the Grasberg recovery, which management still expects to reach 80% of capacity by mid-2027, alongside Indonesian political risk.",
      "Q3 2026 results on 27 October 2026, Grasberg Block Cave ramp-up and Production Block 1S restart in mid-2027, Bagdad expansion investment decision by end-2026, copper price, unit cash costs.",
      (4, 3, 3, 4)),

    C("APD", "Air Products and Chemicals, Inc.", "energy", "Allentown, Pennsylvania, USA", 1940,
      "Eduardo Menezes", "NYSE", 300.00, 0.223, 12.0, 12.1,
      [0.05, 0.06, 0.06, 0.05, 0.05], 0.22, 0.26, 0.080, 0.026,
      "Founded in 1940 by Leonard Pool, who pioneered building air separation plants on customers' sites rather than shipping gas to them. Eduardo Menezes became CEO in 2025 after activist pressure led to leadership change. Air Products supplies industrial gases — oxygen, nitrogen, hydrogen — under long-term take-or-pay contracts, typically fifteen to twenty years, with plants built next to the customer. It is the direct US competitor to Air Liquide and Linde.",
      [("Americas", 40), ("Asia", 27), ("Europe", 24), ("Middle East & Other", 9)],
      ["On-site contracts run fifteen to twenty years with take-or-pay terms, producing exceptionally predictable cash flow.",
       "Once a plant is built next to a customer's facility, switching supplier is effectively impossible.",
       "Industrial gases is a global oligopoly of three, with rational pricing behaviour."],
      ["Very large hydrogen project commitments, including NEOM, have uncertain returns and heavy capital requirements.",
       "The previous management's capital allocation drew sustained activist criticism.",
       "Higher interest rates raise the cost of the debt funding these long-dated projects."],
      "The activist-driven leadership change is the central story — whether project discipline improves returns on capital.",
      "Capital project reviews, hydrogen project decisions, on-site contract signings, return on capital trends.",
      (5, 3, 3, 5)),

    C("SHW", "The Sherwin-Williams Company", "energy", "Cleveland, Ohio, USA", 1866,
      "Heidi Petz", "NYSE", 365.00, 0.25, 10.0, 23.0,
      [0.04, 0.05, 0.05, 0.05, 0.04], 0.13, 0.16, 0.080, 0.026,
      "Founded in 1866 by Henry Sherwin and Edward Williams in Cleveland. Heidi Petz became CEO in 2024. Sherwin-Williams makes and sells paint and coatings, and its structural advantage is distribution: it operates around 5,000 company-owned stores serving professional painters, who value availability and colour consistency far more than price. That direct relationship with contractors is something competitors selling through hardware retailers cannot replicate.",
      [("Paint Stores Group", 57), ("Consumer Brands Group", 17), ("Performance Coatings", 26)],
      ["Company-owned store network creates a direct, sticky relationship with professional painters.",
       "Paint is a small share of a repainting job's total cost, so contractors are relatively price-insensitive.",
       "Repaint demand is more stable than new construction, since surfaces need recoating regardless."],
      ["New residential construction and housing turnover both drive demand and are rate-sensitive.",
       "Raw material costs, particularly petrochemical-derived inputs, are volatile.",
       "Consumer DIY paint demand normalised sharply after the pandemic surge."],
      "Regarded as a quality compounder held back by housing. The professional store network is the durable advantage.",
      "Same-store sales in paint stores, raw material costs, housing turnover, pro versus DIY mix.",
      (5, 3, 3, 5)),

    # ===================== INDUSTRIALS & DEFENCE =====================
    C("MMM", "3M Company", "industrials", "St. Paul, Minnesota, USA", 1902,
      "William Brown", "NYSE", 155.00, 0.54, 12.0, 24.6,
      [0.02, 0.03, 0.03, 0.03, 0.03], 0.15, 0.19, 0.085, 0.024,
      "Founded in 1902 as Minnesota Mining and Manufacturing, originally to mine corundum — a venture that failed, forcing a pivot to sandpaper. William Brown became CEO in 2024. 3M makes tens of thousands of products across industrial adhesives, safety equipment, electronics materials and consumer brands including Post-it and Scotch. Its research culture produced decades of genuine innovation, but recent years have been dominated by litigation.",
      [("Safety & Industrial", 44), ("Transportation & Electronics", 33), ("Consumer", 23)],
      ["Enormous product diversification across thousands of end markets and customers.",
       "Genuine materials science expertise that is difficult to replicate.",
       "New leadership from outside brought a clearer focus on operational discipline."],
      ["Multi-billion dollar settlements over combat earplugs and PFAS chemicals, with liabilities extending for years.",
       "Organic growth has been persistently weak for a decade.",
       "The Solventum healthcare spin-off removed a higher-growth segment from the portfolio."],
      "A restructuring story where litigation overhang and slow growth are set against a low valuation and new management.",
      "Organic growth by segment, litigation payment schedule, margin improvement, capital allocation.",
      (3, 2, 3, 4)),

    C("ITW", "Illinois Tool Works Inc.", "industrials", "Glenview, Illinois, USA", 1912,
      "Christopher O'Herlihy", "NYSE", 270.00, 0.29, 8.0, 15.9,
      [0.03, 0.04, 0.04, 0.04, 0.03], 0.22, 0.25, 0.080, 0.025,
      "Founded in 1912 in Chicago. Christopher O'Herlihy has been CEO since 2023. Illinois Tool Works operates around eighty decentralised business units making engineered fasteners, welding equipment, food equipment, automotive components and testing instruments. Its 80/20 management principle — concentrating effort on the 20% of products and customers generating 80% of profit — has produced consistently high margins across a very diverse portfolio.",
      [("Automotive OEM", 17), ("Food Equipment", 15), ("Test & Measurement", 14), ("Welding", 12), ("Polymers & Fluids", 12), ("Construction & Specialty", 30)],
      ["The 80/20 principle has delivered operating margins above 25%, exceptional for diversified industrials.",
   "Decentralised structure keeps business units close to their customers.",
   "Dividend increases now span 63 consecutive years, extended in August 2026 with a 7% rise, and a new $6 billion buyback authorisation underlines strong cash generation."],
      ["Exposed to industrial production and automotive build rates, both cyclical.",
       "Organic growth has been consistently low single digit.",
       "Automotive OEM exposure carries EV transition risk."],
      "Admired for margin discipline, questioned on growth. Generally treated as a quality industrial to own through cycles, with the $6 billion buyback authorised in August 2026 reinforcing its capital return profile.",
      "Organic revenue growth, operating margin, automotive build rates, food equipment demand.",
      (5, 2, 4, 5)),

    C("CSX", "CSX Corporation", "industrials", "Jacksonville, Florida, USA", 1980,
      "Steve Angel", "Nasdaq", 37.00, 1.87, 17.0, 14.5,
      [0.03, 0.05, 0.05, 0.04, 0.04], 0.24, 0.28, 0.080, 0.025,
      "Formed in 1980 from the merger of Chessie System and Seaboard Coast Line, with predecessor railroads dating to the 1820s. Steve Angel, previously CEO of Linde, took over in 2025 after board dissatisfaction with operating performance. CSX operates around 20,000 route miles across the eastern United States, hauling intermodal containers, chemicals, agricultural products and coal between Atlantic ports and inland markets.",
      [("Merchandise", 62), ("Intermodal", 18), ("Coal", 15), ("Other", 5)],
      ["Rail networks are irreplaceable infrastructure with essentially no prospect of new entrants.",
       "Eastern network serves dense population centres and major Atlantic ports.",
       "New leadership with a strong operational record brought in specifically to improve service metrics."],
      ["Service and operating performance have lagged western peers, which prompted the leadership change.",
       "Coal remains a meaningful revenue source and is in structural decline.",
       "Industrial volumes are cyclical and have been soft."],
      "A turnaround premised on operational improvement under new management. Service metrics are the thing to watch.",
      "Operating ratio, velocity and dwell metrics, intermodal volumes, pricing versus inflation.",
      (4, 3, 3, 5)),

    C("WM", "Waste Management, Inc.", "industrials", "Houston, Texas, USA", 1968,
      "James Fish", "NYSE", 230.00, 0.40, 23.0, 22.5,
      [0.06, 0.06, 0.05, 0.05, 0.05], 0.17, 0.20, 0.070, 0.025,
      "Founded in 1968 by Dean Buntrock and Wayne Huizenga, who consolidated hundreds of small local haulers. James Fish has been CEO since 2016 and will retire in January 2027, when President John Morris, a former chief operating officer with more than three decades in the industry, takes over. Waste Management is the largest waste collection and disposal company in North America, and its most valuable assets are landfills — permitting a new one is close to impossible in most jurisdictions, which makes existing capacity extraordinarily durable.",
      [("Collection", 63), ("Landfill", 19), ("Transfer & Recycling", 13), ("Other", 5)],
      ["Landfill permits are effectively irreplaceable — this is one of the strongest asset moats in industrials.",
       "Waste volumes are stable and largely recession-resistant.",
       "Renewable natural gas from landfill methane is a growing high-margin revenue stream."],
      ["Recycling commodity prices are volatile and can swing segment profitability.",
       "Fuel and labour costs are significant and inflation-sensitive.",
       "The Stericycle acquisition added medical waste, a new business with integration risk."],
      "Considered one of the most defensive quality compounders in the market, and priced as such. The August 2026 announcement that long-serving President John Morris will succeed Jim Fish in January 2027 points to continuity rather than a change of strategy.",
      "Q3 2026 results on 27 October 2026, CEO transition to John Morris on 4 January 2027, core price growth, volume trends, recycling commodity prices, renewable energy project returns.",
      (5, 3, 3, 5)),

    C("TDG", "TransDigm Group Incorporated", "industrials", "Cleveland, Ohio, USA", 1993,
      "Michael Lisman", "NYSE", 1350.00, 0.056, 22.0, 8.6,
      [0.10, 0.09, 0.08, 0.07, 0.07], 0.28, 0.31, 0.095, 0.026,
      "Founded in 1993 by Nick Howley and Doug Peacock. Michael Lisman became CEO in 2025. TransDigm makes highly engineered aircraft components — pumps, valves, actuators, ignition systems — where it is often the sole approved supplier for a given part. Because aircraft parts require regulatory certification, and TransDigm owns the certification, it has extraordinary pricing power in the aftermarket, which is where most of its profit comes from.",
      [("Power & Control", 50), ("Airframe", 46), ("Non-aviation", 4)],
      ["Roughly 75% of revenue comes from proprietary products where TransDigm is the sole source.",
       "Aftermarket parts carry very high margins and recur throughout an aircraft's decades-long life.",
       "One of the best long-term shareholder return records of any US industrial."],
      ["Very high leverage by design, which the company uses deliberately but which magnifies downside.",
       "Aftermarket pricing practices have drawn Department of Defense inspector general scrutiny.",
       "Air travel demand is cyclical and the business is concentrated in aviation."],
      "The business model is widely admired and the leverage widely debated. Fiscal third-quarter 2026 sales grew 23%, 13% organically, and full-year guidance was raised, though the EBITDA margin slipped to 52.8% from 54.4%. Regulatory attention to pricing is the tail risk.",
      "Fiscal Q4 2026 results and fiscal 2027 guidance, Prince & Izant integration, aftermarket revenue growth, aircraft utilisation rates, further acquisition activity, leverage ratio.",
      (5, 4, 2, 5)),

    C("FDX", "FedEx Corporation", "industrials", "Memphis, Tennessee, USA", 1971,
      "Rajesh Subramaniam", "NYSE", 255.00, 0.24, 20.0, 88.0,
      [0.02, 0.03, 0.04, 0.04, 0.03], 0.07, 0.10, 0.085, 0.024,
      "Founded in 1971 by Fred Smith, who described the hub-and-spoke overnight delivery concept in a Yale term paper. Rajesh Subramaniam became CEO in 2022. FedEx operates express air freight and ground delivery networks worldwide. Its DRIVE programme is a large cost reduction effort, and in June 2026 it completed the spin-off of its less-than-truckload business, FedEx Freight, as a separate company, keeping a stake of up to 19.9% that it must generally dispose of within 24 months.",
      [("FedEx Express", 51), ("FedEx Ground", 43), ("Services & Other", 6)],
      ["Global express air network is enormously expensive to replicate and few competitors have one.",
   "The DRIVE cost programme has delivered real structural savings.",
   "The FedEx Freight spin-off funded a $4.1 billion dividend to FedEx, which, with cash on hand, retired about $4.9 billion of debt in July 2026."],
      ["Express air freight has high fixed costs, so volume declines hurt disproportionately.",
       "Amazon's logistics network has removed a large customer and become a competitor.",
       "Business-to-business volumes are tied to industrial activity, which has been weak."],
      "A self-help story: cost reduction against structurally challenged express volumes, with the freight separation now completed. The question is how the leaner parcel business performs on its own.",
      "DRIVE savings realisation, Express segment margin, disposal of the retained FedEx Freight stake, B2B volume trends.",
      (3, 2, 3, 4)),

    C("LHX", "L3Harris Technologies, Inc.", "industrials", "Melbourne, Florida, USA", 2019,
      "Sam Mehta", "NYSE", 275.00, 0.19, 11.0, 21.5,
      [0.05, 0.05, 0.05, 0.04, 0.04], 0.10, 0.13, 0.080, 0.024,
      "Formed in 2019 by the merger of L3 Technologies and Harris Corporation, whose roots go back to 1895. Sam Mehta, who joined in 2023 and previously ran its space and communications businesses, became CEO in August 2026 after Christopher Kubasik stepped down following a board investigation into his conduct. L3Harris makes tactical radios, electronic warfare systems, night vision equipment and space sensors, and acquired Aerojet Rocketdyne in 2023, adding solid rocket motors — a capability with only two suppliers in the United States and one that missile production depends on entirely.",
      [("Space & Airborne Systems", 32), ("Integrated Mission Systems", 30), ("Communication Systems", 25), ("Aerojet Rocketdyne", 13)],
      ["Aerojet Rocketdyne is one of only two US solid rocket motor suppliers, and in September 2026 Lockheed Martin awarded seven-year propulsion contracts worth $4.7 billion for PAC-3 MSE and more than $6 billion for THAAD.",
   "Tactical communications demand has risen sharply with global rearmament.",
   "Positioned as a lower-cost, faster alternative to the traditional primes."],
      ["Almost entirely dependent on US and allied defence budgets.",
   "Expanding constrained solid rocket motor capacity requires heavy investment, including a $3 billion build-out and new plants in Arkansas, and the large PAC-3 and THAAD propulsion contracts are still undefinitized.",
   "Fixed-price development contracts carry cost overrun risk."],
      "Seen as well positioned for munitions and communications demand, a view reinforced by more than $10 billion of PAC-3 and THAAD propulsion awards in September 2026. The abrupt departure of Christopher Kubasik in August 2026 raised governance questions, though the successor is an internal appointment and 2026 guidance was reaffirmed.",
      "Q3 2026 results on 29 October 2026, leadership transition under Sam Mehta, solid rocket motor capacity build-out, definitisation of PAC-3 and THAAD propulsion contracts, defence budget appropriations.",
      (4, 3, 3, 4)),

    # ===================== AUTOS & MOBILITY =====================
    C("F", "Ford Motor Company", "autos", "Dearborn, Michigan, USA", 1903,
      "James Farley", "NYSE", 13.00, 3.95, 20.0, 185.0,
      [0.01, 0.02, 0.03, 0.03, 0.02], 0.030, 0.042, 0.100, 0.020,
      "Founded in 1903 by Henry Ford, who introduced the moving assembly line and changed manufacturing permanently. James Farley has been CEO since 2020 and reorganised the company into three units: Ford Blue for combustion vehicles, Model e for electric, and Ford Pro for commercial customers. Ford Pro is the standout — commercial fleet customers buy trucks, then buy service, parts and software subscriptions for years afterwards.",
      [("Ford Blue (ICE)", 51), ("Ford Pro (Commercial)", 34), ("Ford Model e (EV)", 6), ("Ford Credit", 9)],
      ["Ford Pro generates high-margin recurring service and software revenue from commercial fleets.",
       "The F-Series has been the best-selling US vehicle line for more than four decades.",
       "Net debt figures look alarming but largely reflect Ford Credit's lending book, not industrial leverage."],
      ["The electric vehicle division has been losing billions annually with no near-term path to profitability.",
   "Warranty and recall costs have been persistently higher than peers.",
   "Supply chain fragility is hurting the most profitable product: a months-long aluminium shortage was followed by a supplier issue that halted F-150 output at Dearborn and Kansas City in late September 2026."],
      "The market largely values Ford Pro and discounts Model e heavily. EV loss reduction is the main swing factor, but near-term attention has shifted to F-150 supply after management said the late-September stoppage will dent third-quarter sales.",
      "Third-quarter results, F-150 production recovery, Ford Pro margins, Model e losses, warranty and recall costs, US truck demand and pricing.",
      (3, 2, 2, 3)),

    C("RIVN", "Rivian Automotive, Inc.", "autos", "Irvine, California, USA", 2009,
      "RJ Scaringe", "Nasdaq", 15.00, 1.15, -5.0, 5.2,
      [0.28, 0.35, 0.30, 0.24, 0.19], -0.30, 0.05, 0.135, 0.032,
      "Founded in 2009 by RJ Scaringe, who still runs it. Rivian makes electric pickup trucks and SUVs, plus delivery vans for Amazon, which is also a major shareholder. Its R2 platform, a smaller and substantially cheaper vehicle, is the company's attempt to reach a mainstream market — the current R1 vehicles are premium-priced and volumes are far too low to cover fixed costs. Volkswagen has invested in a joint venture for Rivian's software and electrical architecture.",
      [("Vehicle Sales", 88), ("Software & Services", 12)],
      ["Genuinely well-regarded products with strong owner satisfaction scores.",
       "The Volkswagen joint venture validates Rivian's software architecture and provides substantial funding.",
       "R2 targets a much larger addressable market at a far lower price point."],
      ["Still loses money on every vehicle at current volumes, and the cash burn is substantial.",
   "R2 execution is existential: deliveries began in June 2026, but only the higher-priced Performance version is on sale through 2026 and the ramp has to lift volumes quickly.",
   "Competing against Tesla, legacy manufacturers and Chinese entrants simultaneously."],
      "A binary story. Bulls back the product, the VW partnership and an R2 ramp that helped third-quarter deliveries beat expectations; bears point to cash burn and the difficulty of scaling automotive manufacturing.",
      "Third-quarter results on 29 October 2026, R2 production ramp, fourth-quarter deliveries against the 65,000–70,000 outlook, gross profit per vehicle, cash burn rate, CFO succession, Volkswagen joint venture milestones.",
      (3, 5, 3, 2)),

    # ===================== TELECOM & MEDIA =====================
    C("CHTR", "Charter Communications, Inc.", "telecom", "Stamford, Connecticut, USA", 1993,
      "Christopher Winfrey", "Nasdaq", 265.00, 0.14, 94.0, 55.0,
      [0.0, 0.01, 0.01, 0.01, 0.01], 0.14, 0.17, 0.085, 0.018,
      "Founded in 1993 and rebuilt after bankruptcy under John Malone's influence, acquiring Time Warner Cable in 2016. Christopher Winfrey has been CEO since 2022. Charter sells broadband, video and mobile service under the Spectrum brand, and after completing its combination with Cox Communications in August 2026 it serves more than 70 million homes and businesses across 45 states. Cox Enterprises now owns about 26% of the company, which is to be renamed Cox Communications within a year while keeping the Spectrum brand. Its mobile business resells Verizon's network, which has grown quickly by bundling with broadband at aggressive prices.",
      [("Internet", 51), ("Video", 25), ("Mobile", 12), ("Voice & Commercial", 12)],
      ["Broadband infrastructure has high replacement cost and serves as an essential service.",
       "Mobile bundling has been genuinely effective at reducing broadband churn.",
       "Extremely aggressive share repurchases have reduced the share count dramatically."],
      ["Broadband subscriber losses to fixed wireless and fibre overbuilders have been persistent.",
   "Very high leverage — among the most indebted large US companies relative to earnings, with about $12 billion of Cox debt added at closing.",
   "Integrating Cox under an interim CFO from 15 October 2026 adds execution risk while video subscribers keep declining."],
      "A leveraged equity story. Small changes in broadband subscriber trends have outsized effects on the equity value, and investors now want evidence that the Cox combination delivers its promised savings.",
      "First results including Cox, Cox integration and synergies, broadband net additions, mobile line growth, permanent CFO appointment, leverage ratio, renaming to Cox Communications.",
      (3, 1, 1, 4)),

        # ===================== FRONTIER =====================
    C("HOOD", "Robinhood Markets, Inc.", "frontier", "Menlo Park, California, USA", 2013,
      "Vladimir Tenev", "Nasdaq", 105.00, 0.88, -5.0, 3.3,
      [0.26, 0.22, 0.18, 0.15, 0.12], 0.30, 0.36, 0.115, 0.030,
      "Founded in 2013 by Vladimir Tenev and Baiju Bhatt, who introduced commission-free stock trading and forced the entire brokerage industry to follow. Tenev still runs it. Robinhood earns revenue from payment for order flow, net interest on customer cash and margin lending, crypto trading, and a subscription product called Gold. Its customer base skews young, which is strategically valuable as those customers accumulate assets over time.",
      [("Transaction Revenue", 52), ("Net Interest Revenue", 38), ("Other & Subscriptions", 10)],
      ["Dominant brand among younger investors, a demographic traditional brokers have struggled to reach.",
       "Diversifying into retirement accounts, credit cards and wealth management deepens the relationship.",
       "Crypto trading provides revenue that traditional brokerages largely cannot access."],
      ["Revenue is highly sensitive to retail trading activity, which collapses in bear markets.",
       "Payment for order flow remains a target for regulatory prohibition, particularly in Europe.",
       "Crypto revenue is volatile and dependent on speculative cycles."],
      "A high-beta play on retail investor engagement. Product expansion beyond trading is the main bull argument.",
      "Third-quarter results on 27 October 2026, funded customers and platform assets, prediction market volumes, crypto trading volumes, regulatory developments on order flow.",
      (3, 5, 4, 3)),
]
