from .schema import C

# Note for banks and insurers: a classic free-cash-flow DCF does not work, because
# debt is raw material rather than financing. Here "revenue" is total net revenue
# (net interest income plus fees) and the margin line is distributable net income
# as a share of that revenue. Net debt is set to zero. This is a simplification and
# is flagged on the sector page.

FINANCIALS = [
C("BRK.B", "Berkshire Hathaway Inc.", "financials", "Omaha, Nebraska, USA", 1839,
  "Greg Abel", "NYSE", 507.78, 2.15, -140.0, 375.0,
  [0.06, 0.06, 0.05, 0.05, 0.05], 0.13, 0.14, 0.078, 0.024,
  "Originally a New England textile mill dating to 1839; Warren Buffett took control in 1965 and converted it into a holding company. Greg Abel formally succeeded Buffett as CEO on 1 January 2026, the first planned leadership change in Berkshire's history, with Buffett staying on as chairman. Berkshire owns operating businesses outright — GEICO insurance, BNSF Railway, Berkshire Hathaway Energy, Precision Castparts, See's Candies, Dairy Queen and dozens more — and holds a large listed equity portfolio, historically concentrated in Apple, American Express, Coca-Cola and Bank of America. The insurance float, premiums collected before claims are paid, provides low-cost capital that funds acquisitions. Its cash pile reached a record of roughly $397B by the end of the first quarter of 2026.",
  [("Insurance (GEICO, reinsurance)", 30), ("BNSF Railway", 18), ("Berkshire Hathaway Energy", 16), ("Manufacturing, Service & Retail", 36)],
  ["An enormous cash position is a genuine asset in a market where credit is tightening — it buys optionality nobody else has.",
   "Insurance float functions as permanent, low-cost leverage, which is structurally advantaged financing.",
   "Extreme diversification across the real economy makes earnings unusually resilient."],
  ["The succession from Buffett to Abel is the largest untested variable in the company's history.",
   "Size is now the enemy of returns — moving the needle requires acquisitions few targets can absorb.",
   "A large listed equity portfolio means reported earnings swing violently with mark-to-market rules."],
  "Held as a defensive core position and a proxy for US economic breadth. The debate is about capital deployment under new leadership and whether the size problem caps future returns.",
  "Cash deployment decisions, insurance underwriting results, buyback pace, BNSF volumes.",
  (5, 2, 5, 5)),

C("JPM", "JPMorgan Chase & Co.", "financials", "New York, New York, USA", 1799,
  "Jamie Dimon", "NYSE", 334.47, 2.51, 0.0, 180.0,
  [0.05, 0.05, 0.04, 0.04, 0.04], 0.32, 0.33, 0.095, 0.025,
  "Traces its roots to the Bank of the Manhattan Company, chartered in 1799, and consolidates JP Morgan, Chase Manhattan, Bank One and Bear Stearns. Jamie Dimon has been CEO since 2005, one of the longest tenures in global banking. It is the largest US bank, with roughly $4.8T in assets under management at the end of 2025. Four segments: Consumer and Community Banking, Corporate and Investment Bank (trading, advisory, underwriting), Commercial Banking, and Asset and Wealth Management. It partnered with Coinbase in July 2026 to expand into digital assets.",
  [("Consumer & Community Banking", 43), ("Corporate & Investment Bank", 36), ("Asset & Wealth Management", 12), ("Commercial Banking", 9)],
  ["A fortress balance sheet that lets it gain share in every crisis — it acquired distressed banks in 2008 and again in 2023.",
   "Scale advantage in technology spending is enormous; it can outspend every regional bank combined.",
   "Diversified revenue means trading strength offsets lending weakness and vice versa."],
  ["Credit costs rise if the 2026 oil shock and higher rates push the consumer into stress.",
   "Net interest income benefits fade if the Fed cuts, and the market is currently pricing hikes instead.",
   "Dimon's eventual succession is a genuine, if long-signalled, risk."],
  "Consistently the preferred large-cap US bank. The debate is cyclical, not structural: how much credit normalisation is coming and whether the premium valuation to peers is justified.",
  "Net interest income guidance, credit provisions, investment banking fee pool, capital return approvals.",
  (5, 2, 5, 4)),

C("V", "Visa Inc.", "financials", "San Francisco, California, USA", 1958,
  "Ryan McInerney", "NYSE", 362.13, 1.90, 5.0, 41.0,
  [0.10, 0.09, 0.09, 0.08, 0.07], 0.52, 0.54, 0.082, 0.028,
  "Began in 1958 as the BankAmericard programme, became an independent association in 1970 and listed in 2008 in what was then the largest US IPO. Ryan McInerney is CEO. Visa does not lend or issue cards — it operates VisaNet, the network that authorises, clears and settles transactions between banks and merchants, taking a small fee on each. Roughly 4.5 billion cards run on it across more than 200 countries. Growth areas include Visa Direct for real-time payouts, tokenised credentials, and value-added services in fraud and data analytics.",
  [("Service revenues", 34), ("Data processing", 34), ("International transactions", 23), ("Other", 9)],
  ["Operating margins above 50% — this is one of the most profitable business models in existence.",
   "A genuine two-sided network: merchants must accept Visa because consumers hold it, and vice versa.",
   "It takes no credit risk, so a recession hits volumes but not the balance sheet."],
  ["Interchange fee regulation is a live threat in the US, EU and several emerging markets.",
   "Account-to-account payment rails, including instant bank transfer schemes, bypass the card network entirely.",
   "Cross-border travel volumes are the highest-margin revenue and the most exposed to geopolitical disruption."],
  "A long-standing consensus quality holding. The bear case is regulatory and technological disintermediation over a long horizon rather than anything near-term.",
  "Payment volume growth, cross-border volume, interchange regulation, Visa Direct adoption.",
  (5, 3, 5, 5)),

C("MA", "Mastercard Incorporated", "financials", "Purchase, New York, USA", 1966,
  "Michael Miebach", "NYSE", 539.39, 0.91, 9.0, 32.0,
  [0.11, 0.10, 0.09, 0.08, 0.08], 0.48, 0.51, 0.084, 0.028,
  "Founded in 1966 as Interbank, a cooperative of banks formed to compete with BankAmericard, and listed in 2006. Michael Miebach is CEO, headquartered in Purchase, New York. Like Visa, Mastercard runs a payment network rather than issuing credit. It has pushed harder into value-added services — cyber security, identity verification, consulting and data analytics now represent a substantial and faster-growing share of revenue than at Visa, which changes the mix of the business meaningfully.",
  [("Payment network", 63), ("Value-added services & solutions", 37)],
  ["Value-added services grow faster than the core network and diversify revenue away from pure transaction fees.",
   "Same network economics as Visa with a slightly higher growth rate off a smaller base.",
   "Strong position in cross-border and in emerging markets where card penetration is still low."],
  ["Identical regulatory exposure to Visa on interchange.",
   "Real-time bank payment schemes such as UPI in India and Pix in Brazil are displacing cards in large markets.",
   "The valuation embeds continued double-digit volume growth."],
  "Treated as the higher-growth of the two networks. The disagreement is mostly about relative valuation between Mastercard and Visa rather than the business model.",
  "Cross-border volume growth, value-added services revenue, regulatory rulings, emerging market schemes.",
  (5, 4, 5, 5)),

C("BAC", "Bank of America Corporation", "financials", "Charlotte, North Carolina, USA", 1904,
  "Brian Moynihan", "NYSE", 58.73, 7.45, 0.0, 105.0,
  [0.05, 0.05, 0.04, 0.04, 0.04], 0.27, 0.29, 0.098, 0.024,
  "Traces to the Bank of Italy, founded in San Francisco in 1904 by Amadeo Giannini to lend to immigrants other banks ignored. Now headquartered in Charlotte, North Carolina, with Brian Moynihan as CEO since 2010. It is the second-largest US bank by assets, with the largest retail deposit base in the country. Segments: Consumer Banking, Global Wealth and Investment Management (which includes Merrill), Global Banking, and Global Markets. Its deposit franchise is unusually low-cost, which makes it highly sensitive to the level of interest rates.",
  [("Consumer Banking", 38), ("Global Markets", 24), ("Global Wealth & Investment Mgmt", 21), ("Global Banking", 17)],
  ["The cheapest large deposit base in US banking, which is the single most valuable asset a bank can own.",
   "Merrill and the private bank generate stable fee revenue that is not rate-dependent.",
   "Higher-for-longer rates, now the base case after the Fed's 2026 shift, are directly accretive to net interest income."],
  ["A large held-to-maturity securities portfolio carries substantial unrealised losses that only unwind with time.",
   "Consumer credit deteriorates quickly if unemployment rises, and the 2026 oil shock pressures household budgets.",
   "Less diversified than JPMorgan in trading and investment banking."],
  "Generally viewed as the most rate-sensitive way to own a US money-centre bank. Bulls like the deposit franchise; bears point at the securities book.",
  "Net interest income trajectory, deposit costs, consumer charge-off rates, capital return.",
  (4, 2, 4, 4)),

C("GS", "The Goldman Sachs Group", "financials", "New York, New York, USA", 1869,
  "David Solomon", "NYSE", 1021.00, 0.30, 0.0, 58.0,
  [0.07, 0.06, 0.05, 0.05, 0.04], 0.26, 0.28, 0.105, 0.024,
  "Founded in 1869 by Marcus Goldman, a German immigrant trading commercial paper in New York. David Solomon has been CEO since 2018. Goldman is the pre-eminent investment bank: mergers and acquisitions advisory, equity and debt underwriting, and one of the largest trading operations in the world. It also runs Asset and Wealth Management, which is the strategic priority because fee revenue is more stable than trading revenue. Goldman was lead-left bookrunner on the SpaceX IPO in June 2026, the largest offering in history.",
  [("Global Banking & Markets", 66), ("Asset & Wealth Management", 30), ("Platform Solutions", 4)],
  ["Dominant market share in advisory means Goldman captures a disproportionate share of any capital markets recovery.",
   "The SpaceX IPO mandate demonstrates its position at the top of the league tables, and a wave of large listings is expected to follow.",
   "Asset management fee growth reduces earnings volatility over time."],
  ["Earnings are inherently cyclical and depend on deal activity that can stop abruptly.",
   "Higher rates and geopolitical stress can freeze the IPO and M&A pipeline the bull case depends on.",
   "The consumer banking strategy was an expensive failure and management credibility took damage from it."],
  "Viewed as the highest-beta way to own a capital markets recovery. Bulls point to the IPO pipeline; bears note how quickly that pipeline closes in a risk-off environment.",
  "Investment banking backlog, IPO pipeline conversion, trading revenue, asset management inflows.",
  (4, 3, 4, 4)),

C("MS", "Morgan Stanley", "financials", "New York, New York, USA", 1935,
  "Ted Pick", "NYSE", 213.93, 1.60, 0.0, 66.0,
  [0.07, 0.06, 0.06, 0.05, 0.05], 0.24, 0.27, 0.098, 0.024,
  "Founded in 1935 by Henry Morgan and Harold Stanley after the Glass-Steagall Act forced JP Morgan to separate its investment banking arm. Ted Pick became CEO in 2024. Morgan Stanley deliberately rebuilt around wealth management, acquiring E*TRADE and Eaton Vance, so that stable fee income from client assets now outweighs volatile trading revenue. It manages several trillion dollars in client assets. Institutional Securities still runs a large equities trading franchise, historically the strongest on Wall Street.",
  [("Wealth Management", 48), ("Institutional Securities", 42), ("Investment Management", 10)],
  ["Wealth management fees are recurring and grow with markets, giving far better earnings quality than pure investment banking.",
   "Client asset growth compounds — every dollar retained generates fees indefinitely.",
   "The equities trading franchise is consistently top-ranked and benefits from volatility."],
  ["Wealth management fee rates face persistent competitive pressure from low-cost platforms.",
   "Net new asset growth slows when markets fall, exactly when the stock is already under pressure.",
   "Investment banking exposure still makes results cyclical."],
  "Regarded as the higher-quality earnings profile among the large investment banks because of the wealth management mix.",
  "Net new assets, wealth management pre-tax margin, trading revenue, investment banking pipeline.",
  (4, 3, 4, 4)),

C("AXP", "American Express Company", "financials", "New York, New York, USA", 1850,
  "Stephen Squeri", "NYSE", 351.96, 0.69, 0.0, 74.0,
  [0.09, 0.08, 0.08, 0.07, 0.07], 0.16, 0.17, 0.090, 0.026,
  "Founded in 1850 as a freight express business in Buffalo, New York, later moving into money orders and travellers cheques. Stephen Squeri is CEO. Amex is unusual because it is both the network and the lender — a closed-loop model that gives it direct data on cardholder spending. Revenue comes from merchant discount fees, annual card fees on premium products such as Platinum and Gold, and net interest on lending. Its customer base skews affluent, and the premium fee model has proven strikingly successful with younger high-earning consumers.",
  [("Discount revenue", 62), ("Net card fees", 17), ("Net interest income", 17), ("Other", 4)],
  ["Annual card fee revenue is recurring, growing and remarkably resilient — customers renew even in downturns.",
   "The affluent customer base has better credit performance than the industry through every cycle.",
   "The closed loop gives Amex spending data that open networks simply do not have."],
  ["Merchant acceptance is still narrower than Visa and Mastercard, particularly outside the US.",
   "Amex takes credit risk directly, unlike the networks, so a recession hits both volumes and provisions.",
   "Travel and entertainment spending, its highest-margin category, is sensitive to geopolitical disruption."],
  "Well regarded for the premium fee model and credit quality. The bear case is that it is a lender wearing a network's valuation multiple.",
  "Billed business growth, net card fee revenue, provision for credit losses, premium card refresh cycle.",
  (4, 3, 4, 4)),

C("BLK", "BlackRock, Inc.", "financials", "New York, New York, USA", 1988,
  "Laurence Fink", "NYSE", 1150.00, 0.155, 6.0, 22.0,
  [0.10, 0.09, 0.08, 0.08, 0.07], 0.32, 0.34, 0.088, 0.026,
  "Founded in 1988 by Larry Fink and seven partners inside Blackstone, spun out in 1994. Fink is still CEO. BlackRock is the world's largest asset manager with roughly $12T under management, built on the iShares exchange-traded fund platform acquired from Barclays in 2009. It also licenses Aladdin, the risk management and portfolio system used by a large share of the institutional investment industry, and has expanded aggressively into private markets through the acquisitions of GIP in infrastructure and HPS in private credit.",
  [("iShares ETFs", 40), ("Institutional active & index", 30), ("Technology (Aladdin) & Private Markets", 30)],
  ["Fee revenue scales with assets under management, and index assets grow with markets without requiring new sales effort.",
   "Aladdin is embedded software revenue inside an asset manager — it is sticky and carries software-like margins.",
   "Private markets and infrastructure carry far higher fee rates than index products."],
  ["Fee compression in index products is relentless and structural.",
   "Assets under management fall with markets, so revenue is directly correlated to equity levels.",
   "Political scrutiny over the concentration of corporate voting power is a persistent reputational issue."],
  "Seen as the highest-quality asset manager and the main beneficiary of private markets convergence. The concern is fee compression in the core index business.",
  "Net inflows by asset class, effective fee rate, private markets fundraising, Aladdin renewals.",
  (5, 3, 5, 5)),

C("HSBC", "HSBC Holdings plc", "financials", "London, United Kingdom", 1865,
  "Georges Elhedery", "NYSE (ADR) / LSE", 78.00, 3.42, 0.0, 68.0,
  [0.04, 0.04, 0.04, 0.03, 0.03], 0.28, 0.29, 0.100, 0.022,
  "Founded in 1865 in Hong Kong as the Hongkong and Shanghai Banking Corporation to finance trade between Europe and Asia. Headquartered in London since 1993, with Georges Elhedery as CEO since 2024. HSBC is the largest bank in Europe by assets and the dominant international bank in Hong Kong. It has been restructuring aggressively — exiting retail banking in the US, France and Canada — to concentrate on Asian wealth management and global transaction banking, where it moves a very large share of world trade payments.",
  [("Hong Kong & Asia", 48), ("UK & Europe", 33), ("Global Banking & Markets", 19)],
  ["Unmatched trade finance and transaction banking network connecting Asian manufacturing to Western demand.",
   "Asian wealth management is a structural growth market and HSBC has the incumbent relationships.",
   "Large buyback programmes have meaningfully reduced the share count."],
  ["Caught between US and Chinese regulatory expectations, and both governments have leverage over it.",
   "Hong Kong commercial property exposure has been a source of credit losses.",
   "Rate cuts in Asia and the UK compress the net interest margin that drives most of the profit."],
  "Held mostly for capital return and Asian exposure. The overhang is geopolitical positioning between the US and China.",
  "Net interest margin, Hong Kong credit quality, buyback announcements, Asian wealth net new money.",
  (4, 2, 3, 4)),

C("RY", "Royal Bank of Canada", "financials", "Toronto, Canada", 1864,
  "Dave McKay", "NYSE / TSX", 212.00, 1.39, 0.0, 46.0,
  [0.06, 0.05, 0.05, 0.04, 0.04], 0.30, 0.31, 0.088, 0.024,
  "Founded in 1864 in Halifax, Nova Scotia, as the Merchants Bank of Halifax. Dave McKay has been CEO since 2014, headquartered in Toronto. RBC is Canada's largest bank and one of the most profitable in the world, operating in an oligopoly where five banks hold the overwhelming majority of domestic deposits. Segments span Personal Banking, Commercial Banking, Wealth Management including City National in the US, Capital Markets and Insurance. Its 2024 acquisition of HSBC Canada consolidated the domestic market further.",
  [("Personal & Commercial Banking", 42), ("Wealth Management", 28), ("Capital Markets", 22), ("Insurance & Other", 8)],
  ["Canadian banking is a protected oligopoly with structurally higher returns on equity than US retail banking.",
   "The HSBC Canada acquisition removed a competitor and added deposits at attractive terms.",
   "Long unbroken dividend record supported by conservative underwriting."],
  ["Canadian household debt relative to income is among the highest in the developed world.",
   "Housing market exposure is concentrated and mortgage renewals at higher rates pressure borrowers.",
   "Growth is limited by the size of the domestic market."],
  "Regarded as a conservatively run, high-return bank. The recurring worry is Canadian consumer leverage and housing.",
  "Mortgage renewal performance, provisions for credit losses, wealth management flows, capital ratios.",
  (5, 2, 5, 5)),
]
