from .schema import C

SEMIS = [
C("NVDA", "NVIDIA Corporation", "semis", "Santa Clara, California, USA", 1993,
  "Jensen Huang", "Nasdaq", 194.83, 24.4, -50.0, 213.0,
  [0.38, 0.26, 0.18, 0.13, 0.10], 0.45, 0.42, 0.095, 0.030,
  "Founded in 1993 by Jensen Huang, Chris Malachowsky and Curtis Priem to build 3D graphics chips for PC gaming. Huang still runs it from Santa Clara. NVIDIA designs GPUs — it does not own fabs, TSMC manufactures for it. Its Blackwell and Rubin data-centre accelerators, NVLink interconnect, Spectrum-X and InfiniBand networking, DGX systems and the CUDA software stack together form the default platform for training and running large AI models. Legacy lines include GeForce gaming cards, RTX professional visualisation and DRIVE automotive computers.",
  [("Data Center", 89), ("Gaming", 7), ("Pro Visualization, Auto & OEM", 4)],
  ["CUDA is a fifteen-year software moat — the switching cost is rewriting your entire model training stack, not swapping a chip.",
   "Roughly 75% gross margins on data-centre silicon, which is extraordinary for hardware and shows real pricing power.",
   "Annual product cadence (Hopper to Blackwell to Rubin) keeps competitors chasing a moving target."],
  ["Customer concentration is extreme — a handful of hyperscalers drive most of the revenue, and they are all designing their own chips.",
   "AI-lab decisions now move the stock as well as demand: shares fell about 3% on 14 September 2026 after Anthropic's chief executive called for pacing frontier development, and OpenAI paused work on its most capable models in late September 2026.",
   "The whole thesis assumes AI capex keeps compounding; if enterprises fail to earn a return on it, orders can stop very suddenly."],
  "Q2 FY27, reported on 26 August 2026, beat comfortably: revenue of $96.2bn, up 106%, against roughly $92bn expected, with Q3 guided to $108bn versus about $105bn consensus, and the shares rose almost 5% after hours. The debate has shifted from demand to margins and durability, with gross margin expected to drift from 75% toward the low 70s by early 2027 as memory costs rise. September's AI 'pacing' debate showed how sensitive the stock remains to sentiment at the frontier labs.",
  "Q3 FY27 results against $108bn guidance, Vera Rubin volume ramp, gross margin trajectory toward the low 70s, China export licences, hyperscaler capex guidance.",
  (5, 5, 5, 5)),

C("TSM", "Taiwan Semiconductor Manufacturing", "semis", "Hsinchu, Taiwan", 1987,
  "C.C. Wei", "NYSE (ADR) / TWSE", 388.00, 5.19, -55.0, 145.0,
  [0.28, 0.20, 0.15, 0.12, 0.10], 0.30, 0.32, 0.098, 0.028,
  "Founded in 1987 by Morris Chang, TSMC invented the pure-play foundry model: it manufactures chips designed by other companies and competes with none of them. Run by C.C. Wei from Hsinchu Science Park, it produces essentially every leading-edge chip in the world — Apple's A- and M-series, NVIDIA's Blackwell and Rubin, AMD's Instinct and EPYC, Qualcomm and Broadcom silicon. Its 3nm and 2nm nodes plus CoWoS advanced packaging are the physical bottleneck of the AI build-out. New fabs in Arizona, Japan and Germany are diversifying geography.",
  [("High Performance Computing", 60), ("Smartphone", 25), ("IoT, Automotive & Other", 15)],
  ["Effectively a monopoly at the leading edge — Samsung and Intel Foundry have not matched its yields at 3nm or below.",
   "CoWoS packaging capacity is the gating factor for every AI accelerator shipped, giving TSMC pricing leverage over its own customers.",
   "Charges a premium for leading-edge wafers and still fills every slot, which is the clearest evidence of scarcity value."],
  ["Taiwan concentration risk is the single largest geopolitical exposure in global equities.",
   "Capital intensity is brutal — capex guidance was raised again at the Q2 2026 print and the stock fell 3% on it.",
   "Foundry is cyclical; a pause in AI orders hits a business with enormous fixed costs and no ability to flex them down quickly."],
  "Widely held as the highest-quality way to own the AI cycle without single-customer risk, and the shares hit a record on 4 October 2026 on reports that customers lifted 2nm orders and that 2nm capacity could reach around 120,000 wafers a month by end-2026. August revenue rose 53.3% year on year, and in early October 2026 Elon Musk said TSMC is in early discussions to join his Terafab venture in Texas. The longer-running debate is whether Taiwan risk deserves the persistent valuation discount the market applies to it.",
  "Q3 2026 results on 15 October 2026, September monthly revenue, 2nm ramp and yields, 2027 wafer pricing, Terafab discussions, Arizona fab utilisation, capex guidance.",
  (5, 4, 5, 5)),

C("AVGO", "Broadcom Inc.", "semis", "Palo Alto, California, USA", 1961,
  "Hock Tan", "Nasdaq", 360.45, 4.75, 55.0, 82.0,
  [0.24, 0.19, 0.15, 0.12, 0.10], 0.44, 0.46, 0.093, 0.030,
  "Traces back to a 1961 HP division; the modern company was assembled by Hock Tan through serial acquisition (LSI, Brocade, CA, Symantec, VMware). Headquartered in Palo Alto. Two very different halves: semiconductors — custom AI accelerators (XPUs) designed with Google, Meta and OpenAI, Tomahawk and Jericho Ethernet switching silicon, wireless chips for the iPhone — and infrastructure software, dominated by VMware Cloud Foundation, which Tan repriced onto subscription contracts after the 2023 takeover.",
  [("AI Semiconductors", 38), ("Non-AI Semiconductors", 27), ("Infrastructure Software", 35)],
  ["The custom-ASIC business is the credible second source to NVIDIA — hyperscalers actively want it to exist.",
   "VMware turned a licence business into recurring subscription revenue with software-like margins near 70%.",
   "Hock Tan's capital allocation record is one of the best in large-cap technology over the past decade."],
  ["Guidance remains a market-moving event: in September 2026 a fourth-quarter revenue guide of $34.8bn, about $200m below consensus, sent the shares down 3-6% after hours despite a beat on every headline line.",
   "Customer concentration in custom silicon is severe; losing one hyperscaler design win is a multi-billion-dollar revenue hole.",
   "Around $55B of net debt from the VMware deal is manageable but limits flexibility if rates rise further."],
  "Fiscal Q3 2026 revenue rose 86% to $29.6bn, with AI semiconductor revenue up 221% to $16.7bn, and management lifted its fiscal 2027 AI revenue target to around $115bn, saying supply rather than demand is now the limit. The shares still fell on a marginally light Q4 guide, so the open question is how much of the custom-ASIC ramp is already discounted.",
  "Q4 FY26 results against $34.8bn revenue and $21.7bn AI guidance, progress toward ~$115bn of fiscal 2027 AI revenue, new XPU ramps (Meta MTIA, OpenAI), VMware renewal pricing.",
  (5, 4, 5, 3)),

C("AMD", "Advanced Micro Devices", "semis", "Santa Clara, California, USA", 1969,
  "Lisa Su", "Nasdaq", 517.82, 1.62, -3.0, 47.0,
  [0.35, 0.27, 0.20, 0.15, 0.11], 0.20, 0.28, 0.105, 0.030,
  "Founded in 1969 by Jerry Sanders and seven colleagues from Fairchild Semiconductor. Lisa Su took over in 2014 with the stock near $3 and rebuilt it around TSMC manufacturing and a chiplet architecture. Products: EPYC server CPUs, Instinct MI-series AI accelerators, Ryzen desktop and laptop processors, Radeon graphics, Xilinx FPGAs and the semi-custom chips inside PlayStation and Xbox. In Q1 2026 AMD's data-centre revenue overtook Intel's for the first time.",
  [("Data Center", 55), ("Client", 25), ("Gaming", 10), ("Embedded", 10)],
  ["Passing Intel in data-centre revenue in Q1 2026 was a genuine structural milestone, not a quarterly blip.",
   "Instinct MI-series gives hyperscalers a real second source, and they are willing to pay to avoid single-vendor dependence.",
   "Server CPU share gains compound — once a datacentre validates EPYC, refresh cycles favour the incumbent."],
  ["ROCm software remains far behind CUDA, and that gap is the whole reason NVIDIA keeps its pricing.",
   "The stock rose 30% in September 2026 alone on AI-agent CPU demand and the World Labs deal; at these levels execution has to be close to flawless, and a cautious guide, as on 4 August 2026, still triggers double-digit drops.",
   "AMD is fabless and competes for the same TSMC leading-edge capacity as NVIDIA and Apple."],
  "Q2 2026 revenue rose 50% to $11.5bn with data-centre revenue up 107% to $6.7bn, but a Q3 guide of about $13bn sat below some estimates and the shares fell more than 10% after hours. Sentiment then swung sharply, with the stock up 30% in September 2026 on expectations that AI agents such as Meta's Muse will lift server CPU demand, alongside the $8.2bn all-stock purchase of World Labs. Views remain split between those treating AMD as the clear number-two AI accelerator franchise and those arguing the valuation already prices in share gains that have not yet shown up in the numbers.",
  "Q3 2026 results against ~$13bn guidance, MI450 and Helios deployments (OpenAI, Anthropic, Meta), World Labs closing, server share data, ROCm developer adoption.",
  (4, 5, 4, 4)),

C("MU", "Micron Technology", "semis", "Boise, Idaho, USA", 1978,
  "Sanjay Mehrotra", "Nasdaq", 975.56, 1.12, 5.0, 166.0,
  [0.22, 0.05, -0.08, 0.06, 0.08], 0.34, 0.24, 0.115, 0.025,
  "Founded in 1978 in the basement of a Boise dental office by Ward Parkinson and three partners. Sanjay Mehrotra has run it since 2017. Micron makes memory: DRAM, NAND flash, and critically HBM (high-bandwidth memory), the stacked DRAM that sits beside every AI accelerator. It is one of only three companies in the world that can make leading-edge DRAM at scale, alongside Samsung and SK Hynix. Quarterly revenue reached $41.5B in 2026 and the market cap crossed $1T in May 2026.",
  [("DRAM (incl. HBM)", 76), ("NAND", 22), ("Other", 2)],
  ["HBM is sold out on multi-year contracts, which converts a historically brutal spot-priced commodity into something closer to a contracted business.",
   "Only three credible suppliers worldwide, and adding DRAM capacity takes years and tens of billions of dollars.",
   "US-based manufacturing makes Micron the structural winner from Western supply-chain policy."],
  ["Memory is the most cyclical business in semiconductors. Every previous supercycle has ended in a savage price collapse.",
   "Record profits alongside record multiple expansion is exactly what past cycle tops looked like, and the shares rose only about 1% after hours on a clear beat-and-raise on 30 September 2026.",
   "Our model deliberately builds in a down year in FY3 because assuming a straight line here would not be credible."],
  "Still polarised, but the numbers keep moving the bulls' way: fiscal Q4 2026 revenue of $54.23bn beat consensus of $51.5bn, and Q1 FY27 guidance of $61.5bn, with non-GAAP gross margin near 86%, was well ahead of the $57.9bn expected. The muted share reaction shows the argument is now about duration rather than demand. Bulls say HBM contracting and strategic customer agreements have changed the cycle; bears point out that every memory cycle in history has been called structurally different at the top.",
  "Q1 FY27 results against $61.5bn guidance, HBM4 qualification and ramp, DRAM contract pricing, capex discipline from SK Hynix and Samsung, inventory data.",
  (3, 4, 3, 4)),

C("INTC", "Intel Corporation", "semis", "Santa Clara, California, USA", 1968,
  "Lip-Bu Tan", "Nasdaq", 120.35, 4.70, 42.0, 58.0,
  [0.12, 0.14, 0.13, 0.11, 0.09], 0.02, 0.16, 0.115, 0.028,
  "Founded in 1968 by Robert Noyce and Gordon Moore, the company that made the microprocessor a commodity and then lost the leading edge to TSMC. Lip-Bu Tan became CEO in March 2025 and is running a turnaround with US government and strategic investor backing. Products: Core and Xeon processors, Gaudi AI accelerators, Altera FPGAs, and Intel Foundry, which is trying to sell manufacturing capacity to external customers on the 18A and 14A nodes. Up roughly 278% in the first half of 2026, then down 21% in seven trading days in July.",
  [("Client Computing", 48), ("Data Center & AI", 30), ("Foundry (external)", 12), ("Other", 10)],
  ["Optionality is enormous — if 18A yields hold, Intel becomes the only leading-edge foundry outside Taiwan, and that is a strategic asset governments will pay for.",
   "Government and strategic investment, plus a roughly $23bn share sale at $95 in August 2026, materially de-risked a balance sheet that looked genuinely stressed in 2024.",
   "Even modest recovery in margins produces very large earnings swings from today's depressed base."],
  ["Foundry is the whole bull case and it is still lossmaking at the operating line; leading-edge yields have to hold at volume before the economics work, and that is not yet proven.",
   "Server CPU share fell from 72.8% to 66.8% year-over-year and AMD has now passed Intel in data-centre revenue.",
   "There is still no announced external 14A volume customer; management says engagement has risen sharply, but TSMC's October 2026 talks to join Musk's Terafab, where Intel was the first chipmaker backer, show anchor customers can go elsewhere."],
  "Still the most contested large-cap semiconductor name. The stock fell 7% on 14 September 2026 in the AI 'pacing' selloff and slipped again in early October on reports that TSMC may join Musk's Terafab, while the August equity raise priced at $95 traded below its offer price within days. Bulls own it as a policy-backed option on Western manufacturing; bears note that the stock still prices in an execution record Intel has not delivered in a decade.",
  "Q3 2026 results, first named external 14A customer, 18A yield disclosures, Terafab participation, quarterly foundry operating losses, Panther Lake ramp.",
  (2, 3, 2, 3)),

C("ASML", "ASML Holding N.V.", "semis", "Veldhoven, Netherlands", 1984,
  "Christophe Fouquet", "Nasdaq (ADR) / Euronext", 1417.80, 0.39, -8.0, 46.0,
  [0.20, 0.17, 0.14, 0.11, 0.09], 0.30, 0.33, 0.090, 0.028,
  "Spun out of Philips and ASM International in 1984 in Veldhoven, Netherlands, and led by Christophe Fouquet since 2024. ASML is the sole supplier of extreme ultraviolet (EUV) lithography machines — the roughly $200M systems required to print transistors below 7nm. Every advanced chip on earth is made on ASML equipment. Its newer High-NA EUV systems cost around $380M each. It also sells older DUV lithography, metrology and inspection tools, and earns a large recurring service revenue stream on an installed base that lasts decades.",
  [("EUV Systems", 45), ("DUV Systems", 30), ("Installed Base Management", 25)],
  ["A genuine monopoly. There is no second supplier of EUV, and building one would take a decade and tens of billions.",
   "Roughly a quarter of revenue is service and upgrades on installed machines — recurring, high margin and insensitive to the order cycle.",
   "Every capex increase from TSMC, Samsung, Intel or Micron eventually lands as an ASML order."],
  ["Order intake is lumpy to an extreme degree; a single quarter can miss badly on timing and say nothing about the trend.",
   "Dutch and US export controls have closed most of the China market for advanced tools, and China was a large share of DUV sales.",
   "Customer concentration is total — four companies effectively decide ASML's revenue."],
  "Broadly viewed as the highest-quality asset in the semiconductor supply chain, and High-NA is moving from pilot tool to production roadmap, with TSMC planning to introduce it into high-volume manufacturing from 2030. The shares fell 5% on 14 September 2026 in the AI 'pacing' selloff but have since recovered, with buybacks continuing (€442.5m in the week to 2 October 2026). Debate still focuses on order timing and how much China revenue is permanently gone versus deferred.",
  "Q3 2026 results on 14 October 2026, quarterly net bookings, High-NA customer adoption, customer capex announcements, export control changes.",
  (5, 4, 5, 5)),

C("AMAT", "Applied Materials", "semis", "Santa Clara, California, USA", 1967,
  "Gary Dickerson", "Nasdaq", 603.04, 0.78, -2.0, 38.0,
  [0.18, 0.15, 0.12, 0.10, 0.08], 0.27, 0.29, 0.098, 0.028,
  "Founded in 1967, the largest semiconductor equipment company by revenue. Gary Dickerson has led it since 2013. Applied sells the deposition, etch, chemical mechanical planarization and ion implantation tools that build transistor structures layer by layer, plus inspection systems and display equipment. Its Applied Global Services arm provides parts, upgrades and maintenance across the installed base. Gate-all-around transistors and advanced packaging both increase the number of process steps per wafer, which mechanically increases Applied's content.",
  [("Semiconductor Systems", 70), ("Applied Global Services", 25), ("Display & Other", 5)],
  ["Broadest tool portfolio in the industry — customers can source most of a fab line from one vendor.",
   "Gate-all-around and backside power delivery raise the number of process steps, increasing Applied's dollar content per wafer.",
   "Services revenue on a large installed base cushions the downside in a capex trough."],
  ["China was historically a very large revenue share and export controls have structurally reduced it.",
   "The stock fell 7.35% in a single session during the July 2026 selloff — this is a high-beta way to own the capex cycle.",
   "Equipment orders lead revenue by several quarters, so the reported numbers look best right as the cycle turns."],
  "Fiscal Q3 2026 revenue of $9.12bn, up 25%, beat consensus, and the Q4 guide of $10.25bn at the midpoint was well above the $9.62bn expected, with DRAM and advanced packaging driving growth. The stock nonetheless de-rated, falling about 22% in the month to mid-September and another 6% on 14 September 2026, and Morgan Stanley cut its target while raising 2027 estimates. The debate is now how long the AI-led equipment upcycle lasts, alongside how much of the China revenue loss is permanent.",
  "Q4 FY26 results against $10.25bn guidance, 2027 WFE forecasts, DRAM and advanced packaging orders, China revenue mix, gate-all-around tool wins.",
  (4, 4, 4, 5)),

C("LRCX", "Lam Research", "semis", "Fremont, California, USA", 1980,
  "Timothy Archer", "Nasdaq", 351.41, 1.25, 1.0, 32.0,
  [0.26, 0.18, 0.10, 0.08, 0.07], 0.28, 0.30, 0.105, 0.028,
  "Founded in 1980 by David Lam in Fremont, California. Timothy Archer has been CEO since 2018. Lam specialises in etch and deposition — the tools that carve and build the vertical structures inside chips. It is disproportionately exposed to memory, because 3D NAND stacking and DRAM capacitor formation are etch-intensive processes. That made Lam one of the biggest beneficiaries of the 2025-26 memory supercycle, with the stock running from under $95 to $433 before falling 10% in a single session in July 2026.",
  [("Etch & Deposition Systems", 76), ("Customer Support & Services", 24)],
  ["Highest memory exposure among large equipment makers, and memory capex is running at record levels.",
   "Every additional layer in a 3D NAND stack requires more etch steps, so technology roadmaps mechanically raise Lam's content.",
   "Installed base service revenue is large and recurring."],
  ["The same memory leverage that drove the run works in reverse — this is the most cyclical name in equipment.",
   "A 10.19% single-session drop in July 2026 shows how quickly positioning unwinds here.",
   "Memory capex decisions are made by three customers, and they have historically cut together."],
  "Treated as a high-beta memory capex proxy. Bulls point to HBM-driven structural demand; bears note the stock is priced off peak-cycle earnings.",
  "Memory capex announcements from Samsung, SK Hynix and Micron; NAND layer-count roadmaps.",
  (4, 4, 4, 4)),

C("ARM", "Arm Holdings plc", "semis", "Cambridge, United Kingdom", 1990,
  "Rene Haas", "Nasdaq (ADR)", 315.28, 1.06, -3.0, 5.4,
  [0.28, 0.24, 0.20, 0.16, 0.13], 0.30, 0.40, 0.105, 0.032,
  "Founded in Cambridge in 1990 as a joint venture between Acorn Computers, Apple and VLSI Technology. SoftBank bought it in 2016 and relisted it on Nasdaq in 2023; it remains majority SoftBank-owned. Rene Haas is CEO. Arm does not make chips — it licenses instruction set architectures and processor designs, then collects a royalty on every chip shipped using them. Roughly 99% of smartphones use Arm cores, and Arm-based server CPUs (AWS Graviton, NVIDIA Grace, Microsoft Cobalt) are taking real data-centre share.",
  [("Royalty", 60), ("Licensing", 40)],
  ["A royalty model with almost no cost of goods — incremental revenue drops through at extraordinary margins.",
   "Arm v9 carries roughly double the royalty rate of v8, so the mix shift raises revenue without a single extra chip shipping.",
   "Data-centre Arm adoption is the genuine new growth vector; every hyperscaler now ships an Arm server CPU."],
  ["The valuation is extreme on any conventional measure, even after falling 12% in the week to 21 July 2026.",
   "SoftBank's majority stake creates a persistent overhang and limits free float; in September 2026 it raised its Arm-backed margin loan to $25bn, so a falling share price also shrinks the collateral behind its borrowing.",
   "RISC-V is a free, open alternative and is gaining traction in embedded markets where royalty rates matter most."],
  "One of the most expensive large-cap semiconductor names on earnings. Bulls underwrite the royalty rate expansion story; bears simply cannot make the multiple work on any near-term number. The shares fell 9% on 28 September 2026, roughly twice as much as peers, as investors focused on the link between Arm's price and SoftBank's enlarged margin loan.",
  "v9 royalty mix, data-centre design wins, Arm's own chiplet strategy, SoftBank stake actions and margin-loan collateral.",
  (5, 5, 4, 5)),

C("TXN", "Texas Instruments", "semis", "Dallas, Texas, USA", 1930,
  "Haviv Ilan", "Nasdaq", 293.08, 0.90, 8.0, 18.5,
  [0.14, 0.12, 0.09, 0.07, 0.06], 0.24, 0.32, 0.088, 0.028,
  "Founded in 1930 as Geophysical Service Inc., an oil exploration company, before becoming a semiconductor pioneer — Jack Kilby built the first integrated circuit here in 1958. Haviv Ilan has been CEO since 2023, based in Dallas. TI makes analog and embedded processing chips: power management, signal chain, and microcontrollers. These are cheap, unglamorous parts that go into cars, factory equipment and appliances, sold across roughly 100,000 customers. TI owns its own 300mm fabs, which is unusual and gives it a structural cost advantage.",
  [("Analog", 75), ("Embedded Processing", 20), ("Other", 5)],
  ["Owning 300mm analog capacity gives a durable cost-per-chip advantage no fabless competitor can copy.",
   "Extremely diversified customer base — no single design win matters much, which makes revenue unusually predictable.",
   "Long-running record of returning nearly all free cash flow through dividends and buybacks."],
  ["Industrial and automotive end markets have been in a prolonged inventory correction and the recovery keeps slipping.",
   "Heavy capex on new fabs has depressed free cash flow for several years running.",
   "Chinese analog competitors are pricing aggressively in exactly the commodity end of TI's range."],
  "Viewed as a quality compounder going through a capex-heavy trough. The disagreement is over how much of the recent free cash flow weakness is structural versus a temporary investment phase.",
  "Automotive and industrial order recovery, capex step-down, free cash flow per share inflection.",
  (4, 2, 5, 4)),

C("QCOM", "Qualcomm Incorporated", "semis", "San Diego, California, USA", 1985,
  "Cristiano Amon", "Nasdaq", 178.00, 1.08, -6.0, 44.0,
  [0.09, 0.08, 0.07, 0.06, 0.05], 0.29, 0.30, 0.095, 0.025,
  "Founded in 1985 by Irwin Jacobs and six colleagues in San Diego. Cristiano Amon is CEO. Two businesses: QCT, which sells Snapdragon system-on-chip processors and modems for Android phones, cars and PCs; and QTL, which licenses Qualcomm's foundational CDMA and 5G patents and collects a royalty on essentially every 3G/4G/5G handset sold worldwide, regardless of whose chip is inside. The licensing business is small in revenue but enormous in profit. Qualcomm is diversifying into automotive cockpit and ADAS chips and Snapdragon X PC processors.",
  [("Handsets", 62), ("Automotive", 12), ("IoT", 14), ("Licensing (QTL)", 12)],
  ["QTL licensing is close to pure profit and is contractually tied to global handset volumes rather than Qualcomm's own share.",
   "Automotive design-win pipeline is large and books years of revenue in advance.",
   "Trades at a persistent discount to the semiconductor group despite comparable returns on capital."],
  ["Apple has been shipping its own modems and will eventually remove a large chunk of QCT revenue.",
   "Handset volumes are mature; a projected collapse in global smartphone demand was one of the June 2026 selloff triggers.",
   "Licensing depends on periodic renewals with large OEMs; an Apple extension from April 2027 and a multi-year Huawei cross-licence in October 2026 helped, but the Apple term was not disclosed and Chinese renewals remain a recurring negotiation."],
  "Consensus still sees the valuation as largely discounting Apple's modem departure, and two September 2026 deals eased the overhang: a multi-generational custom-silicon and connectivity collaboration with AWS for AI data centres (8 September) and an extension of the Apple patent licence (24 September). The debate is whether data-centre, automotive and PC diversification can replace lost handset content in time; the shares gave back 6% on 28 September 2026 in a broader chip selloff.",
  "Apple modem transition pace, first AWS custom-silicon shipments, automotive design-win conversion, Chinese OEM licence renewals, fiscal Q4 results.",
  (3, 2, 4, 5)),

C("KLAC", "KLA Corporation", "semis", "Milpitas, California, USA", 1975,
  "Richard Wallace", "Nasdaq", 183.50, 1.30, 2.0, 16.0,
  [0.19, 0.15, 0.12, 0.09, 0.08], 0.32, 0.34, 0.095, 0.028,
  "Formed by the 1997 merger of KLA Instruments (1975) and Tencor. Richard Wallace has been CEO since 2006. KLA dominates process control — the inspection and metrology tools that find defects on wafers during manufacturing. It holds well over half the market. As transistor structures get smaller and more three-dimensional, yield becomes the hardest problem in chipmaking, and every extra process step needs another inspection point. That makes KLA's content per wafer rise with complexity, and its gross margins are the highest in equipment at around 60%.",
  [("Semiconductor Process Control", 86), ("Specialty Semiconductor & PCB", 14)],
  ["Over 50% share of process control with no serious challenger, and the highest gross margins in semiconductor equipment.",
   "Yield matters more as nodes shrink, so KLA's revenue per wafer rises structurally with each generation.",
   "Service revenue grows with the installed base and is essentially non-cyclical."],
  ["Same cyclical exposure as the rest of wafer fab equipment, with a higher multiple to lose.",
   "China export restrictions removed a meaningful revenue stream.",
   "Trades at a premium multiple that leaves little room for a demand disappointment."],
  "Regarded as the quality compounder of the equipment group. The valuation rarely gets cheap, which is itself the main pushback.",
  "WFE forecasts, advanced packaging inspection demand, quarterly gross margin.",
  (5, 4, 5, 5)),
]
