from .schema import C

SOFTWARE = [
C("MSFT", "Microsoft Corporation", "software", "Redmond, Washington, USA", 1975,
  "Satya Nadella", "Nasdaq", 390.49, 7.35, 40.0, 325.0,
  [0.14, 0.13, 0.12, 0.11, 0.10], 0.26, 0.30, 0.085, 0.030,
  "Founded in 1975 by Bill Gates and Paul Allen in Albuquerque, now headquartered in Redmond, Washington. Satya Nadella has been CEO since 2014 and rebuilt the company around cloud. Three segments: Intelligent Cloud (Azure, the number-two public cloud, plus SQL Server and GitHub), Productivity and Business Processes (Microsoft 365, Teams, Dynamics, LinkedIn) and More Personal Computing (Windows, Xbox, Surface, Bing). Its partnership with OpenAI put Copilot into Office, Windows and GitHub, and Azure is the primary cloud for a large share of commercial AI workloads.",
  [("Intelligent Cloud", 43), ("Productivity & Business Processes", 33), ("More Personal Computing", 24)],
  ["Microsoft 365 sits inside essentially every large enterprise, which makes it the lowest-friction distribution channel for AI features on earth.",
   "Azure is compounding in the high teens off an enormous base while gross margins keep improving.",
   "Genuinely diversified — no single product failure breaks the story, which is rare at this market cap."],
  ["Capex has exploded to fund AI data centres, and the return on that spend is still unproven.",
   "Copilot seat adoption has been slower to convert into revenue than the initial enthusiasm implied.",
   "The OpenAI relationship has become more complex and less exclusive as OpenAI diversifies its compute suppliers."],
  "The most widely held mega-cap and generally the consensus 'safe' AI exposure. Through the July 2026 capex scare it was treated as the least exposed of the hyperscalers, with management noting that GPU contracts for its largest customers run the full useful life of the hardware. The live debate remains whether AI capex is building a durable moat or simply compressing free cash flow.",
  "Azure growth rate, Copilot seat disclosures, capex guidance, commercial bookings.",
  (5, 4, 5, 5)),

C("GOOGL", "Alphabet Inc.", "software", "Mountain View, California, USA", 1998,
  "Sundar Pichai", "Nasdaq", 359.91, 11.90, -70.0, 400.0,
  [0.15, 0.13, 0.12, 0.10, 0.09], 0.24, 0.28, 0.088, 0.030,
  "Google was founded in 1998 by Larry Page and Sergey Brin at Stanford; Alphabet was created as the holding company in 2015. Sundar Pichai runs it from Mountain View. Revenue is dominated by advertising — Search, YouTube and the ad network — with Google Cloud as the fast-growing second pillar and a portfolio of Other Bets including Waymo autonomous vehicles and Verily. Alphabet designs its own TPU AI accelerators, runs the Gemini model family, and owns Android and Chrome, which together control how most of the world reaches the internet.",
  [("Google Search & Other", 56), ("YouTube Ads", 11), ("Google Cloud", 15), ("Subscriptions, Platforms & Devices", 15), ("Other Bets", 3)],
  ["Search remains one of the best businesses ever built — high margin, recurring, and still growing at a double-digit rate.",
   "Alphabet owns the full AI stack: TPUs, data centres, models and distribution. No one else has all four.",
   "Waymo is a genuinely valuable option that carries almost no weight in the reported numbers."],
  ["AI chat interfaces are the first credible threat to the search query in twenty years, and the monetisation per query is lower.",
   "Ongoing antitrust remedies in the US and EU could force changes to default search placement deals.",
   "Cloud is a strong third place behind AWS and Azure, and third place in an oligopoly is an uncomfortable position."],
  "Sentiment improved sharply through 2026 as Gemini closed the perceived model gap. The remaining bear case is structural: that answers replace links and search economics compress.",
  "Search revenue growth, Gemini adoption, cloud backlog, antitrust remedy rulings, Waymo expansion.",
  (5, 4, 5, 5)),

C("AMZN", "Amazon.com, Inc.", "software", "Seattle, Washington, USA", 1994,
  "Andy Jassy", "Nasdaq", 242.67, 10.75, 45.0, 800.0,
  [0.11, 0.10, 0.09, 0.09, 0.08], 0.10, 0.15, 0.090, 0.030,
  "Founded by Jeff Bezos in 1994 as an online bookstore run out of a Bellevue garage. Andy Jassy, who built AWS, became CEO in 2021. Three engines: North American and International retail, including third-party marketplace and Prime; Amazon Web Services, the largest public cloud, which generates the majority of operating profit; and advertising, now a very large business built on retail search placement. Amazon also designs its own Trainium and Inferentia AI chips and operates Kuiper satellite broadband.",
  [("North America Retail", 60), ("International Retail", 23), ("AWS", 17)],
  ["AWS is the profit engine and its backlog keeps extending as enterprises commit to multi-year AI capacity.",
   "Advertising is a very high margin business bolted onto retail infrastructure that already exists.",
   "Retail margins have been improving for several years as the regional fulfilment redesign matures."],
  ["Capex is enormous and rising, which suppresses free cash flow in exactly the years the market wants to see it.",
   "AWS growth has trailed Azure, raising questions about relative positioning in AI workloads.",
   "Retail is exposed to consumer weakness, and higher oil prices in 2026 are pressuring both consumers and logistics costs."],
  "Broadly favoured as a way to own cloud plus advertising plus retail optionality. The July 2026 quarter answered the central question emphatically: revenue passed $200bn for the first time and AWS grew 37%, its fastest in eighteen quarters. Amazon also raised its 2026 capital plan to roughly $220bn, so the free cash flow drag from the AI build-out remains the main pushback.",
  "AWS growth rate and backlog, advertising revenue, capex guidance, retail operating margin.",
  (5, 4, 4, 4)),

C("META", "Meta Platforms, Inc.", "software", "Menlo Park, California, USA", 2004,
  "Mark Zuckerberg", "Nasdaq", 582.90, 2.52, 15.0, 243.0,
  [0.15, 0.13, 0.11, 0.10, 0.09], 0.24, 0.28, 0.095, 0.028,
  "Founded by Mark Zuckerberg in a Harvard dorm room in 2004 and renamed Meta in 2021. Zuckerberg still controls the company through supervoting shares. It operates Facebook, Instagram, WhatsApp, Messenger and Threads, reaching over three billion daily users, and monetises almost entirely through advertising. Reality Labs builds Quest headsets and Ray-Ban smart glasses at a large annual loss. Meta develops the open-weight Llama model family and, in July 2026, unveiled Meta Compute — a plan to sell surplus AI computing capacity to outside developers, turning part of a roughly $115-135 billion annual infrastructure bill into a potential revenue line.",
  [("Family of Apps advertising", 97), ("Reality Labs & Other", 3)],
  ["Advertising monetisation keeps improving because AI ranking makes each impression more valuable — this is the clearest example of AI paying for itself.",
   "Three billion daily users creates a distribution asset that cannot be replicated at any price.",
   "Instagram Reels and WhatsApp business messaging are still early in monetisation."],
  ["Reality Labs has burned tens of billions with no line of sight to profitability.",
   "Unveiling Meta Compute in July 2026 to resell surplus capacity was read by some as an admission that infrastructure spend has outrun near-term need — the opposite of the message Zuckerberg wants the market to take from record capex.",
   "Regulatory pressure on teen safety and data use is persistent across the US and EU."],
  "Generally well regarded on advertising execution, with the argument concentrated on capital allocation. The July 2026 quarter crystallised it: revenue grew 27% to $60.8bn and beat expectations, yet earnings per share rose only around 1% and the shares fell, because 2026 capital spending guidance was raised again to $125-145bn. Revenue growth without earnings growth is the gap the market is now focused on.",
  "Ad revenue per user, Reality Labs loss trajectory, Meta Compute customer wins, capex guidance.",
  (5, 4, 5, 4)),

C("ORCL", "Oracle Corporation", "software", "Austin, Texas, USA", 1977,
  "Safra Catz", "NYSE", 140.27, 2.85, 95.0, 62.0,
  [0.22, 0.20, 0.17, 0.14, 0.11], 0.14, 0.24, 0.100, 0.030,
  "Founded in 1977 by Larry Ellison, Bob Miner and Ed Oates. Ellison remains chairman and CTO; Safra Catz is CEO. Headquarters moved to Austin, Texas. Oracle sells database software — still the standard for large enterprise transactional systems — plus Fusion and NetSuite cloud applications. Its Oracle Cloud Infrastructure business signed enormous multi-year AI training contracts, taking remaining performance obligations above $520B by the end of fiscal Q2 2026. The stock fell from $328 to $140, one of the largest mega-cap drawdowns of the cycle.",
  [("Cloud Services & License Support", 74), ("Cloud & On-Premise License", 9), ("Hardware & Services", 17)],
  ["A backlog above $520B is contracted revenue, not a forecast, and it is very large relative to the current market cap.",
   "The database franchise is genuinely sticky — migrating a core banking system off Oracle is a multi-year project nobody wants.",
   "After a 57% drawdown from the high, expectations are dramatically lower than they were in 2025."],
  ["Financing the AI data-centre build has pushed debt to roughly $95B net, and rising rates make that more expensive.",
   "Backlog concentration in a small number of AI customers means a single cancellation is material.",
   "Margins on AI infrastructure are structurally lower than on software, so revenue growth flatters the profit picture."],
  "Sharply divided after the drawdown. Bulls treat it as a contracted-backlog story trading at a fraction of its 2025 valuation; bears focus on the debt load and the quality of the counterparties behind that backlog.",
  "Quarterly RPO disclosure, OCI capacity ramp, debt issuance terms, AI contract customer concentration.",
  (4, 4, 3, 2)),

C("CRM", "Salesforce, Inc.", "software", "San Francisco, California, USA", 1999,
  "Marc Benioff", "NYSE", 188.38, 0.96, 5.0, 41.0,
  [0.09, 0.09, 0.08, 0.08, 0.07], 0.31, 0.34, 0.092, 0.028,
  "Founded in 1999 by Marc Benioff and three colleagues in a San Francisco apartment, with the explicit goal of ending packaged enterprise software. Benioff is still CEO. Salesforce is the largest customer relationship management platform, extended by acquisition into Slack, Tableau analytics, MuleSoft integration and Commerce Cloud. Its Agentforce product sells autonomous AI agents that handle customer service and sales tasks, priced by conversation rather than by seat — a deliberate move away from the per-seat model that AI arguably threatens.",
  [("Sales & Service Cloud", 47), ("Platform & Other", 23), ("Marketing & Commerce", 15), ("Data Cloud & Analytics", 15)],
  ["Very high gross retention — CRM is the system of record for the sales organisation and rarely gets ripped out.",
   "Agentforce moves pricing to consumption, which protects against the risk that AI reduces the number of seats needed.",
   "Operating margins have expanded substantially since activist investors arrived in 2023."],
  ["Seat-based software is the category most directly threatened if AI agents reduce headcount in sales and support.",
   "Growth has decelerated into single digits, which makes the multiple hard to defend on growth alone.",
   "A long acquisition history means a large share of profit is adjusted for stock compensation and amortisation."],
  "Increasingly viewed as the most leveraged large-cap bet on the AI capital cycle continuing. Cloud infrastructure revenue grew 93% year over year in the June 2026 quarter and remaining performance obligations reached roughly $638bn, but a meaningful share is tied to prepaid or customer-supplied GPU arrangements. That makes Oracle the name most exposed if hyperscaler spending plateaus, which is precisely the fear that drove the July 2026 selloff.",
  "Agentforce bookings, current remaining performance obligations, operating margin, net revenue retention.",
  (4, 2, 4, 5)),

C("NOW", "ServiceNow, Inc.", "software", "Santa Clara, California, USA", 2004,
  "Bill McDermott", "NYSE", 115.76, 1.12, -4.0, 16.0,
  [0.20, 0.18, 0.16, 0.14, 0.12], 0.31, 0.35, 0.092, 0.030,
  "Founded in 2004 by Fred Luddy, a former CTO who wanted to fix corporate IT ticketing. Bill McDermott, previously CEO of SAP, has run it since 2019 from Santa Clara. ServiceNow started in IT service management and expanded into a general workflow platform covering HR, customer service, security operations and, increasingly, AI agent orchestration. Its Now Assist products embed generative AI into those workflows. Customers are almost entirely large enterprises and governments, on multi-year subscription contracts with unusually high renewal rates. Share count and price here reflect the stock split completed in 2026; the stock has also fallen sharply from its 2025 high.",
  [("Digital Workflows", 42), ("IT Workflows", 38), ("Creator & Other Workflows", 20)],
  ["Renewal rates above 98% are among the best in enterprise software — the platform becomes the connective tissue of internal operations.",
   "Workflow orchestration is arguably where AI agents create demand rather than destroy it, since agents need a system to run inside.",
   "Consistent 20%+ subscription growth at scale with expanding free cash flow margins."],
  ["One of the most expensive large-cap software names on any multiple, which leaves no room for a growth miss.",
   "US federal government exposure is meaningful and subject to budget politics.",
   "Large-deal timing can push revenue between quarters and create sharp share price reactions."],
  "Consistently well regarded operationally; the pushback is almost entirely valuation. Bears argue the multiple already assumes flawless execution through 2030.",
  "Subscription revenue growth, cRPO, Now Assist attach rates, federal renewal cycle.",
  (5, 5, 5, 5)),

C("PLTR", "Palantir Technologies", "software", "Denver, Colorado, USA", 2003,
  "Alex Karp", "Nasdaq", 178.15, 2.45, -5.5, 5.2,
  [0.42, 0.34, 0.27, 0.21, 0.17], 0.36, 0.42, 0.115, 0.032,
  "Founded in 2003 by Peter Thiel, Alex Karp, Joe Lonsdale, Stephen Cohen and Nathan Gettings, initially funded partly by the CIA's venture arm. Karp is CEO; headquarters moved to Denver in 2020. Palantir builds data integration and decision software: Gotham for defence and intelligence, Foundry for commercial enterprises, Apollo for deployment, and AIP, the Artificial Intelligence Platform that connects large language models to a customer's operational data. Its US commercial business has been growing far faster than the government side that originally built the company.",
  [("US Government", 42), ("US Commercial", 33), ("International", 25)],
  ["US commercial revenue has been compounding at extraordinary rates, proving the business is not just a defence contractor.",
   "AIP solves the actual enterprise AI problem — connecting models to messy internal data — and there is no obvious competitor doing it as well.",
   "Government contracts are long, sticky and effectively impossible for a new entrant to win."],
  ["The valuation is one of the most demanding in the entire market on any revenue or earnings measure.",
   "Stock-based compensation is very large relative to revenue and meaningfully dilutes shareholders.",
   "A retail-heavy shareholder base makes the stock unusually volatile — it moved 12.5% in the week to 21 July 2026 alone."],
  "The single most polarising large-cap software name. Bulls treat it as the enterprise AI operating system; bears cannot reconcile any discounted cash flow with the multiple. Our own model here produces a fair value well below the market price, and we show it rather than adjust the assumptions to fit.",
  "US commercial customer count, net dollar retention, government contract awards, stock compensation trend.",
  (4, 5, 4, 5)),

C("SAP", "SAP SE", "software", "Walldorf, Germany", 1972,
  "Christian Klein", "NYSE (ADR) / Frankfurt", 185.99, 1.17, 2.0, 44.0,
  [0.11, 0.11, 0.10, 0.09, 0.08], 0.24, 0.30, 0.086, 0.026,
  "Founded in 1972 by five former IBM engineers in Weinheim, Germany, now headquartered in Walldorf. Christian Klein is CEO. SAP is the dominant enterprise resource planning vendor — the software that runs finance, supply chain, procurement and manufacturing for most large industrial companies in Europe and a large share globally. Its central project is migrating a huge installed base off on-premise ECC systems onto the S/4HANA cloud platform, with the 2027 end-of-maintenance deadline acting as a forcing function. Business AI features are bundled into premium cloud tiers.",
  [("Cloud", 58), ("Software Licenses & Support", 34), ("Services", 8)],
  ["The 2027 ECC maintenance deadline forces a migration decision on thousands of customers with nowhere else realistic to go.",
   "Cloud backlog gives multi-year revenue visibility that is unusual for a company this size.",
   "Europe's most important software asset, and the primary beneficiary of European digital sovereignty policy."],
  ["Migration timelines slip constantly — ERP projects are notorious for running years late.",
   "Growth is solid but not spectacular, so the stock depends on margin expansion delivering.",
   "Currency translation adds noise for dollar-based investors."],
  "Regarded as a steady compounder with a rare structural catalyst in the 2027 deadline. The debate is about migration pace rather than direction.",
  "Current cloud backlog growth, S/4HANA migration wins, operating margin expansion.",
  (5, 3, 5, 5)),

C("NFLX", "Netflix, Inc.", "software", "Los Gatos, California, USA", 1997,
  "Ted Sarandos & Greg Peters", "Nasdaq", 77.65, 4.24, 8.0, 48.0,
  [0.13, 0.12, 0.11, 0.09, 0.08], 0.22, 0.30, 0.090, 0.028,
  "Founded in 1997 by Reed Hastings and Marc Randolph as a DVD-by-mail service, streaming from 2007, original content from 2013. Ted Sarandos and Greg Peters are co-CEOs. Netflix has over 300 million paid memberships and produces content in more than 50 countries. The business has shifted from pure subscription growth to monetisation: paid sharing, a lower-priced advertising tier that is scaling into a meaningful ad business, live events and sports rights, and video games. Note that the share price reflects a stock split completed in 2026.",
  [("Streaming subscriptions", 88), ("Advertising", 10), ("Other", 2)],
  ["The advertising tier is now large enough to matter and carries higher revenue per user than the ad-free plans in most markets.",
   "Content spend is no longer growing faster than revenue, so operating leverage is finally showing up.",
   "Global production capability is a genuine moat — no competitor can commission local-language hits at this scale."],
  ["Streaming competition remains intense and content costs reset upward with every sports rights auction.",
   "Subscriber growth in mature markets is close to saturated, so the story now depends entirely on price and advertising.",
   "Password-sharing enforcement was a one-time boost that cannot be repeated."],
  "Generally viewed as the clear structural winner in streaming, with the debate centred on how much of the advertising ramp is already in the price.",
  "Ad tier revenue disclosure, average revenue per membership, operating margin, live event viewership.",
  (5, 3, 5, 4)),

C("ADBE", "Adobe Inc.", "software", "San Jose, California, USA", 1982,
  "Shantanu Narayen", "Nasdaq", 263.43, 0.42, 2.0, 24.0,
  [0.09, 0.08, 0.08, 0.07, 0.07], 0.36, 0.36, 0.095, 0.026,
  "Founded in 1982 by John Warnock and Charles Geschke, who left Xerox PARC to commercialise PostScript. Shantanu Narayen has been CEO since 2007 and executed the industry's most successful subscription transition. Adobe sells Creative Cloud (Photoshop, Illustrator, Premiere, After Effects), Document Cloud (Acrobat and PDF, a format Adobe invented) and Experience Cloud for enterprise marketing analytics. Its Firefly generative models are trained on licensed content and embedded directly into the creative tools.",
  [("Digital Media", 74), ("Digital Experience", 25), ("Publishing & Other", 1)],
  ["Photoshop and Acrobat are verbs. Professional workflows and file formats are extremely hard to displace.",
   "Firefly's licensed training data is a real commercial advantage for enterprises worried about copyright exposure.",
   "Consistently converts over a third of revenue into free cash flow."],
  ["Generative AI lowers the barrier to creating images and video, which threatens the value of the tools themselves.",
   "Growth has slowed to high single digits and the market has de-rated the stock accordingly.",
   "New AI-native design competitors are winning the low end, where Adobe's pricing is least defensible."],
  "A genuine disagreement about whether AI is a feature Adobe monetises or a force that commoditises its products. The multiple has already compressed substantially.",
  "Digital Media net new annual recurring revenue, Firefly monetisation, pricing changes.",
  (4, 2, 5, 5)),

C("UBER", "Uber Technologies", "software", "San Francisco, California, USA", 2009,
  "Dara Khosrowshahi", "NYSE", 71.2, 2.09, 4.0, 52.0,
  [0.16, 0.15, 0.13, 0.11, 0.10], 0.14, 0.20, 0.098, 0.030,
  "Founded in 2009 by Garrett Camp and Travis Kalanick. Dara Khosrowshahi has been CEO since 2017 and turned a cash-burning growth story into a free-cash-flow generating platform. Uber operates ride-hailing in roughly 70 countries, Uber Eats delivery, and Uber Freight logistics. It also sells advertising against its app surface, a small but very high-margin revenue line. Rather than build its own autonomous vehicles, Uber has partnered with Waymo and other AV developers to put their vehicles on its demand network.",
  [("Mobility", 55), ("Delivery", 35), ("Freight & Other", 10)],
  ["Two-sided network effects in each city — more drivers means shorter waits, which brings more riders.",
   "The AV partnership strategy converts the biggest existential threat into a supply source Uber does not have to fund.",
   "Advertising revenue is high margin and still small relative to the app's reach."],
  ["Driver classification law remains unresolved in several major markets and could add substantial cost.",
   "If autonomous fleets scale, the vehicle owners may capture the economics and relegate Uber to a booking layer.",
   "Delivery is a competitive, low-margin business with well-funded rivals in every region."],
  "Broadly constructive on the free cash flow inflection. The bear case is long-dated and structural: who captures the profit when the driver is removed from the equation.",
  "Gross bookings growth, take rate, AV partnership expansion, advertising revenue disclosure.",
  (4, 4, 4, 4)),

C("SHOP", "Shopify Inc.", "software", "Ottawa, Canada", 2006,
  "Tobias Lütke", "Nasdaq / TSX", 129.17, 1.31, -4.5, 11.5,
  [0.24, 0.21, 0.18, 0.15, 0.13], 0.18, 0.26, 0.105, 0.032,
  "Founded in 2006 in Ottawa by Tobias Lütke, Daniel Weinand and Scott Lake after they failed to find good software for their snowboard shop. Lütke is still CEO. Shopify provides the commerce infrastructure behind millions of merchants: storefronts, checkout, payments through Shopify Payments, capital lending, shipping, point-of-sale hardware for physical retail, and Shop Pay. Its enterprise tier, Shopify Plus, has won large brands away from legacy platforms. Merchant Solutions — the take-rate businesses — now generate far more revenue than subscriptions.",
  [("Merchant Solutions", 74), ("Subscription Solutions", 26)],
  ["Revenue scales with merchant gross merchandise volume rather than seat count, so Shopify grows as its customers grow.",
   "Payments attach rate keeps rising, and payments is where the economics actually are.",
   "Moving upmarket into enterprise brands raises average revenue per merchant substantially."],
  ["Consumer discretionary spending is directly exposed to the 2026 oil shock and tighter financial conditions.",
   "Amazon, and increasingly TikTok and Instagram commerce, compete for the same merchant relationships.",
   "The multiple is high enough that any deceleration in gross merchandise volume gets punished hard."],
  "Seen as the highest-quality commerce infrastructure asset outside Amazon. Valuation and consumer sensitivity are the recurring objections.",
  "Gross merchandise volume growth, payments penetration, Shopify Plus wins, free cash flow margin.",
  (4, 5, 4, 5)),

C("CRWD", "CrowdStrike Holdings", "software", "Austin, Texas, USA", 2011,
  "George Kurtz", "Nasdaq", 520.00, 0.25, -3.5, 5.2,
  [0.24, 0.22, 0.19, 0.16, 0.14], 0.30, 0.36, 0.100, 0.032,
  "Founded in 2011 by George Kurtz, Dmitri Alperovitch and Gregg Marston, with the insight that endpoint security should be delivered from the cloud rather than installed as software. Kurtz is CEO, headquarters in Austin. The Falcon platform uses a single lightweight agent to deliver endpoint detection, identity protection, cloud workload security, log management through Falcon LogScale, and exposure management. Customers add modules over time, which is the core of the business model. CrowdStrike rose 8.5% in the week to 21 July 2026, among the strongest large-cap performers.",
  [("Subscription", 95), ("Professional Services", 5)],
  ["Single-agent architecture means each new module is nearly free to deploy for the customer, driving very high expansion rates.",
   "Security budgets are among the last things enterprises cut, which makes revenue unusually defensive.",
   "Threat intelligence data compounds — more endpoints means better detection, which wins more endpoints."],
  ["Priced for perfection; any slowdown in net new annual recurring revenue triggers sharp de-rating.",
   "The 2024 update outage damaged trust and competitors used it aggressively in renewals.",
   "Microsoft bundles competing security into E5 licences, which is a persistent pricing headwind."],
  "Consistently one of the best-regarded names in security software. The objection is always the multiple rather than the business.",
  "Net new ARR, module attach rates, dollar-based net retention, competitive win rates against Microsoft.",
  (5, 5, 5, 5)),
]
